// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudflare.zeroTrustGateway.inputs;

import com.pulumi.cloudflare.zeroTrustGateway.inputs.SettingsSettingsAntivirusNotificationSettingsArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SettingsSettingsAntivirusArgs extends com.pulumi.resources.ResourceArgs {

    public static final SettingsSettingsAntivirusArgs Empty = new SettingsSettingsAntivirusArgs();

    /**
     * Specify whether to enable anti-virus scanning on downloads.
     * 
     */
    @Import(name="enabledDownloadPhase")
    private @Nullable Output<Boolean> enabledDownloadPhase;

    /**
     * @return Specify whether to enable anti-virus scanning on downloads.
     * 
     */
    public Optional<Output<Boolean>> enabledDownloadPhase() {
        return Optional.ofNullable(this.enabledDownloadPhase);
    }

    /**
     * Specify whether to enable anti-virus scanning on uploads.
     * 
     */
    @Import(name="enabledUploadPhase")
    private @Nullable Output<Boolean> enabledUploadPhase;

    /**
     * @return Specify whether to enable anti-virus scanning on uploads.
     * 
     */
    public Optional<Output<Boolean>> enabledUploadPhase() {
        return Optional.ofNullable(this.enabledUploadPhase);
    }

    /**
     * Specify whether to block requests for unscannable files.
     * 
     */
    @Import(name="failClosed")
    private @Nullable Output<Boolean> failClosed;

    /**
     * @return Specify whether to block requests for unscannable files.
     * 
     */
    public Optional<Output<Boolean>> failClosed() {
        return Optional.ofNullable(this.failClosed);
    }

    /**
     * Configure the message the user&#39;s device shows during an antivirus scan.
     * 
     */
    @Import(name="notificationSettings")
    private @Nullable Output<SettingsSettingsAntivirusNotificationSettingsArgs> notificationSettings;

    /**
     * @return Configure the message the user&#39;s device shows during an antivirus scan.
     * 
     */
    public Optional<Output<SettingsSettingsAntivirusNotificationSettingsArgs>> notificationSettings() {
        return Optional.ofNullable(this.notificationSettings);
    }

    private SettingsSettingsAntivirusArgs() {}

    private SettingsSettingsAntivirusArgs(SettingsSettingsAntivirusArgs $) {
        this.enabledDownloadPhase = $.enabledDownloadPhase;
        this.enabledUploadPhase = $.enabledUploadPhase;
        this.failClosed = $.failClosed;
        this.notificationSettings = $.notificationSettings;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SettingsSettingsAntivirusArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SettingsSettingsAntivirusArgs $;

        public Builder() {
            $ = new SettingsSettingsAntivirusArgs();
        }

        public Builder(SettingsSettingsAntivirusArgs defaults) {
            $ = new SettingsSettingsAntivirusArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param enabledDownloadPhase Specify whether to enable anti-virus scanning on downloads.
         * 
         * @return builder
         * 
         */
        public Builder enabledDownloadPhase(@Nullable Output<Boolean> enabledDownloadPhase) {
            $.enabledDownloadPhase = enabledDownloadPhase;
            return this;
        }

        /**
         * @param enabledDownloadPhase Specify whether to enable anti-virus scanning on downloads.
         * 
         * @return builder
         * 
         */
        public Builder enabledDownloadPhase(Boolean enabledDownloadPhase) {
            return enabledDownloadPhase(Output.of(enabledDownloadPhase));
        }

        /**
         * @param enabledUploadPhase Specify whether to enable anti-virus scanning on uploads.
         * 
         * @return builder
         * 
         */
        public Builder enabledUploadPhase(@Nullable Output<Boolean> enabledUploadPhase) {
            $.enabledUploadPhase = enabledUploadPhase;
            return this;
        }

        /**
         * @param enabledUploadPhase Specify whether to enable anti-virus scanning on uploads.
         * 
         * @return builder
         * 
         */
        public Builder enabledUploadPhase(Boolean enabledUploadPhase) {
            return enabledUploadPhase(Output.of(enabledUploadPhase));
        }

        /**
         * @param failClosed Specify whether to block requests for unscannable files.
         * 
         * @return builder
         * 
         */
        public Builder failClosed(@Nullable Output<Boolean> failClosed) {
            $.failClosed = failClosed;
            return this;
        }

        /**
         * @param failClosed Specify whether to block requests for unscannable files.
         * 
         * @return builder
         * 
         */
        public Builder failClosed(Boolean failClosed) {
            return failClosed(Output.of(failClosed));
        }

        /**
         * @param notificationSettings Configure the message the user&#39;s device shows during an antivirus scan.
         * 
         * @return builder
         * 
         */
        public Builder notificationSettings(@Nullable Output<SettingsSettingsAntivirusNotificationSettingsArgs> notificationSettings) {
            $.notificationSettings = notificationSettings;
            return this;
        }

        /**
         * @param notificationSettings Configure the message the user&#39;s device shows during an antivirus scan.
         * 
         * @return builder
         * 
         */
        public Builder notificationSettings(SettingsSettingsAntivirusNotificationSettingsArgs notificationSettings) {
            return notificationSettings(Output.of(notificationSettings));
        }

        public SettingsSettingsAntivirusArgs build() {
            return $;
        }
    }

}
