// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudflare.callsSfu.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetAppPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetAppPlainArgs Empty = new GetAppPlainArgs();

    /**
     * The account identifier tag.
     * 
     */
    @Import(name="accountId", required=true)
    private String accountId;

    /**
     * @return The account identifier tag.
     * 
     */
    public String accountId() {
        return this.accountId;
    }

    /**
     * A Cloudflare-generated unique identifier for a item.
     * 
     */
    @Import(name="appId", required=true)
    private String appId;

    /**
     * @return A Cloudflare-generated unique identifier for a item.
     * 
     */
    public String appId() {
        return this.appId;
    }

    private GetAppPlainArgs() {}

    private GetAppPlainArgs(GetAppPlainArgs $) {
        this.accountId = $.accountId;
        this.appId = $.appId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetAppPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetAppPlainArgs $;

        public Builder() {
            $ = new GetAppPlainArgs();
        }

        public Builder(GetAppPlainArgs defaults) {
            $ = new GetAppPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param accountId The account identifier tag.
         * 
         * @return builder
         * 
         */
        public Builder accountId(String accountId) {
            $.accountId = accountId;
            return this;
        }

        /**
         * @param appId A Cloudflare-generated unique identifier for a item.
         * 
         * @return builder
         * 
         */
        public Builder appId(String appId) {
            $.appId = appId;
            return this;
        }

        public GetAppPlainArgs build() {
            if ($.accountId == null) {
                throw new MissingRequiredPropertyException("GetAppPlainArgs", "accountId");
            }
            if ($.appId == null) {
                throw new MissingRequiredPropertyException("GetAppPlainArgs", "appId");
            }
            return $;
        }
    }

}
