provider: cloudflare
major-version: 6
makeTemplate: bridged
runner:
  default: pulumi-ubuntu-8core
plugins:
  - name: terraform
    version: "1.0.16"
    kind: converter
  - name: std
    version: "1.6.2"
  - name: gcp
    version: "5.0.0"
  - name: tls
    version: "4.0.0"
env:
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
team: ecosystem
pulumiConvert: 1
registryDocs: true
integrationTestProvider: true
freeDiskSpaceBeforeBuild: true
freeDiskSpaceBeforeSdkBuild: true
freeDiskSpaceBeforeTest: true
