provider: cloudflare
major-version: 6
makeTemplate: bridged
runner:
    default: pulumi-ubuntu-8core
    prerequisites: pulumi-ubuntu-8core
esc:
    enabled: true
env:
    CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
team: ecosystem
pulumiConvert: 1
registryDocs: true
integrationTestProvider: true
freeDiskSpaceBeforeBuild: true
freeDiskSpaceBeforeSdkBuild: true
freeDiskSpaceBeforeTest: true
