// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cloudflare
{
    /// <summary>
    /// Accepted Permissions
    /// 
    /// - `Cloud Email Security: Read`
    /// - `Cloud Email Security: Write`
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Cloudflare = Pulumi.Cloudflare;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var exampleEmailSecurityDomain = new Cloudflare.EmailSecurityDomain("example_email_security_domain", new()
    ///     {
    ///         AccountId = "023e105f4ecef8ad9ca31a8372d0c353",
    ///         AllowedDeliveryModes = new[]
    ///         {
    ///             "DIRECT",
    ///         },
    ///         Domain = "domain",
    ///         DropDispositions = new[]
    ///         {
    ///             "MALICIOUS",
    ///         },
    ///         IpRestrictions = new[]
    ///         {
    ///             "192.0.2.0/24",
    ///             "2001:db8::/32",
    ///         },
    ///         Regions = new[]
    ///         {
    ///             "GLOBAL",
    ///         },
    ///         Folder = "AllItems",
    ///         IntegrationId = "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e",
    ///         LookbackHops = 1,
    ///         RequireTlsInbound = true,
    ///         RequireTlsOutbound = true,
    ///         Transport = "transport",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// ```sh
    /// $ pulumi import cloudflare:index/emailSecurityDomain:EmailSecurityDomain example '&lt;account_id&gt;/&lt;domain_id&gt;'
    /// ```
    /// </summary>
    [CloudflareResourceType("cloudflare:index/emailSecurityDomain:EmailSecurityDomain")]
    public partial class EmailSecurityDomain : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Identifier.
        /// </summary>
        [Output("accountId")]
        public Output<string> AccountId { get; private set; } = null!;

        [Output("allowedDeliveryModes")]
        public Output<ImmutableArray<string>> AllowedDeliveryModes { get; private set; } = null!;

        [Output("authorization")]
        public Output<Outputs.EmailSecurityDomainAuthorization> Authorization { get; private set; } = null!;

        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// Available values: "none", "good", "invalid".
        /// </summary>
        [Output("dmarcStatus")]
        public Output<string> DmarcStatus { get; private set; } = null!;

        [Output("domain")]
        public Output<string> Domain { get; private set; } = null!;

        [Output("dropDispositions")]
        public Output<ImmutableArray<string>> DropDispositions { get; private set; } = null!;

        [Output("emailsProcessed")]
        public Output<Outputs.EmailSecurityDomainEmailsProcessed> EmailsProcessed { get; private set; } = null!;

        /// <summary>
        /// Available values: "AllItems", "Inbox".
        /// </summary>
        [Output("folder")]
        public Output<string> Folder { get; private set; } = null!;

        /// <summary>
        /// Available values: "Microsoft", "Google".
        /// </summary>
        [Output("inboxProvider")]
        public Output<string> InboxProvider { get; private set; } = null!;

        [Output("integrationId")]
        public Output<string?> IntegrationId { get; private set; } = null!;

        [Output("ipRestrictions")]
        public Output<ImmutableArray<string>> IpRestrictions { get; private set; } = null!;

        /// <summary>
        /// Deprecated, use `ModifiedAt` instead. End of life: November 1, 2026.
        /// </summary>
        [Output("lastModified")]
        public Output<string> LastModified { get; private set; } = null!;

        [Output("lookbackHops")]
        public Output<int> LookbackHops { get; private set; } = null!;

        [Output("modifiedAt")]
        public Output<string> ModifiedAt { get; private set; } = null!;

        [Output("o365TenantId")]
        public Output<string> O365TenantId { get; private set; } = null!;

        [Output("regions")]
        public Output<ImmutableArray<string>> Regions { get; private set; } = null!;

        [Output("requireTlsInbound")]
        public Output<bool> RequireTlsInbound { get; private set; } = null!;

        [Output("requireTlsOutbound")]
        public Output<bool> RequireTlsOutbound { get; private set; } = null!;

        /// <summary>
        /// Available values: "none", "good", "neutral", "open", "invalid".
        /// </summary>
        [Output("spfStatus")]
        public Output<string> SpfStatus { get; private set; } = null!;

        /// <summary>
        /// Available values: "PENDING", "ACTIVE", "FAILED", "TIMEOUT".
        /// </summary>
        [Output("status")]
        public Output<string> Status { get; private set; } = null!;

        [Output("transport")]
        public Output<string?> Transport { get; private set; } = null!;


        /// <summary>
        /// Create a EmailSecurityDomain resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public EmailSecurityDomain(string name, EmailSecurityDomainArgs args, CustomResourceOptions? options = null)
            : base("cloudflare:index/emailSecurityDomain:EmailSecurityDomain", name, args ?? new EmailSecurityDomainArgs(), MakeResourceOptions(options, ""))
        {
        }

        private EmailSecurityDomain(string name, Input<string> id, EmailSecurityDomainState? state = null, CustomResourceOptions? options = null)
            : base("cloudflare:index/emailSecurityDomain:EmailSecurityDomain", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing EmailSecurityDomain resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static EmailSecurityDomain Get(string name, Input<string> id, EmailSecurityDomainState? state = null, CustomResourceOptions? options = null)
        {
            return new EmailSecurityDomain(name, id, state, options);
        }
    }

    public sealed class EmailSecurityDomainArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Identifier.
        /// </summary>
        [Input("accountId", required: true)]
        public Input<string> AccountId { get; set; } = null!;

        [Input("allowedDeliveryModes", required: true)]
        private InputList<string>? _allowedDeliveryModes;
        public InputList<string> AllowedDeliveryModes
        {
            get => _allowedDeliveryModes ?? (_allowedDeliveryModes = new InputList<string>());
            set => _allowedDeliveryModes = value;
        }

        [Input("domain", required: true)]
        public Input<string> Domain { get; set; } = null!;

        [Input("dropDispositions", required: true)]
        private InputList<string>? _dropDispositions;
        public InputList<string> DropDispositions
        {
            get => _dropDispositions ?? (_dropDispositions = new InputList<string>());
            set => _dropDispositions = value;
        }

        /// <summary>
        /// Available values: "AllItems", "Inbox".
        /// </summary>
        [Input("folder")]
        public Input<string>? Folder { get; set; }

        [Input("integrationId")]
        public Input<string>? IntegrationId { get; set; }

        [Input("ipRestrictions", required: true)]
        private InputList<string>? _ipRestrictions;
        public InputList<string> IpRestrictions
        {
            get => _ipRestrictions ?? (_ipRestrictions = new InputList<string>());
            set => _ipRestrictions = value;
        }

        [Input("lookbackHops")]
        public Input<int>? LookbackHops { get; set; }

        [Input("regions", required: true)]
        private InputList<string>? _regions;
        public InputList<string> Regions
        {
            get => _regions ?? (_regions = new InputList<string>());
            set => _regions = value;
        }

        [Input("requireTlsInbound")]
        public Input<bool>? RequireTlsInbound { get; set; }

        [Input("requireTlsOutbound")]
        public Input<bool>? RequireTlsOutbound { get; set; }

        [Input("transport")]
        public Input<string>? Transport { get; set; }

        public EmailSecurityDomainArgs()
        {
        }
        public static new EmailSecurityDomainArgs Empty => new EmailSecurityDomainArgs();
    }

    public sealed class EmailSecurityDomainState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Identifier.
        /// </summary>
        [Input("accountId")]
        public Input<string>? AccountId { get; set; }

        [Input("allowedDeliveryModes")]
        private InputList<string>? _allowedDeliveryModes;
        public InputList<string> AllowedDeliveryModes
        {
            get => _allowedDeliveryModes ?? (_allowedDeliveryModes = new InputList<string>());
            set => _allowedDeliveryModes = value;
        }

        [Input("authorization")]
        public Input<Inputs.EmailSecurityDomainAuthorizationGetArgs>? Authorization { get; set; }

        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        /// <summary>
        /// Available values: "none", "good", "invalid".
        /// </summary>
        [Input("dmarcStatus")]
        public Input<string>? DmarcStatus { get; set; }

        [Input("domain")]
        public Input<string>? Domain { get; set; }

        [Input("dropDispositions")]
        private InputList<string>? _dropDispositions;
        public InputList<string> DropDispositions
        {
            get => _dropDispositions ?? (_dropDispositions = new InputList<string>());
            set => _dropDispositions = value;
        }

        [Input("emailsProcessed")]
        public Input<Inputs.EmailSecurityDomainEmailsProcessedGetArgs>? EmailsProcessed { get; set; }

        /// <summary>
        /// Available values: "AllItems", "Inbox".
        /// </summary>
        [Input("folder")]
        public Input<string>? Folder { get; set; }

        /// <summary>
        /// Available values: "Microsoft", "Google".
        /// </summary>
        [Input("inboxProvider")]
        public Input<string>? InboxProvider { get; set; }

        [Input("integrationId")]
        public Input<string>? IntegrationId { get; set; }

        [Input("ipRestrictions")]
        private InputList<string>? _ipRestrictions;
        public InputList<string> IpRestrictions
        {
            get => _ipRestrictions ?? (_ipRestrictions = new InputList<string>());
            set => _ipRestrictions = value;
        }

        /// <summary>
        /// Deprecated, use `ModifiedAt` instead. End of life: November 1, 2026.
        /// </summary>
        [Input("lastModified")]
        public Input<string>? LastModified { get; set; }

        [Input("lookbackHops")]
        public Input<int>? LookbackHops { get; set; }

        [Input("modifiedAt")]
        public Input<string>? ModifiedAt { get; set; }

        [Input("o365TenantId")]
        public Input<string>? O365TenantId { get; set; }

        [Input("regions")]
        private InputList<string>? _regions;
        public InputList<string> Regions
        {
            get => _regions ?? (_regions = new InputList<string>());
            set => _regions = value;
        }

        [Input("requireTlsInbound")]
        public Input<bool>? RequireTlsInbound { get; set; }

        [Input("requireTlsOutbound")]
        public Input<bool>? RequireTlsOutbound { get; set; }

        /// <summary>
        /// Available values: "none", "good", "neutral", "open", "invalid".
        /// </summary>
        [Input("spfStatus")]
        public Input<string>? SpfStatus { get; set; }

        /// <summary>
        /// Available values: "PENDING", "ACTIVE", "FAILED", "TIMEOUT".
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        [Input("transport")]
        public Input<string>? Transport { get; set; }

        public EmailSecurityDomainState()
        {
        }
        public static new EmailSecurityDomainState Empty => new EmailSecurityDomainState();
    }
}
