// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cloudflare
{
    public static class GetEmailSecurityTrustedDomainsList
    {
        /// <summary>
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Cloudflare = Pulumi.Cloudflare;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var exampleEmailSecurityTrustedDomainsList = Cloudflare.GetEmailSecurityTrustedDomainsList.Invoke(new()
        ///     {
        ///         AccountId = "023e105f4ecef8ad9ca31a8372d0c353",
        ///         Direction = "asc",
        ///         IsRecent = true,
        ///         IsSimilarity = true,
        ///         Order = "pattern",
        ///         Search = "search",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetEmailSecurityTrustedDomainsListResult> InvokeAsync(GetEmailSecurityTrustedDomainsListArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetEmailSecurityTrustedDomainsListResult>("cloudflare:index/getEmailSecurityTrustedDomainsList:getEmailSecurityTrustedDomainsList", args ?? new GetEmailSecurityTrustedDomainsListArgs(), options.WithDefaults());

        /// <summary>
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Cloudflare = Pulumi.Cloudflare;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var exampleEmailSecurityTrustedDomainsList = Cloudflare.GetEmailSecurityTrustedDomainsList.Invoke(new()
        ///     {
        ///         AccountId = "023e105f4ecef8ad9ca31a8372d0c353",
        ///         Direction = "asc",
        ///         IsRecent = true,
        ///         IsSimilarity = true,
        ///         Order = "pattern",
        ///         Search = "search",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetEmailSecurityTrustedDomainsListResult> Invoke(GetEmailSecurityTrustedDomainsListInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetEmailSecurityTrustedDomainsListResult>("cloudflare:index/getEmailSecurityTrustedDomainsList:getEmailSecurityTrustedDomainsList", args ?? new GetEmailSecurityTrustedDomainsListInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Cloudflare = Pulumi.Cloudflare;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var exampleEmailSecurityTrustedDomainsList = Cloudflare.GetEmailSecurityTrustedDomainsList.Invoke(new()
        ///     {
        ///         AccountId = "023e105f4ecef8ad9ca31a8372d0c353",
        ///         Direction = "asc",
        ///         IsRecent = true,
        ///         IsSimilarity = true,
        ///         Order = "pattern",
        ///         Search = "search",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetEmailSecurityTrustedDomainsListResult> Invoke(GetEmailSecurityTrustedDomainsListInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetEmailSecurityTrustedDomainsListResult>("cloudflare:index/getEmailSecurityTrustedDomainsList:getEmailSecurityTrustedDomainsList", args ?? new GetEmailSecurityTrustedDomainsListInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetEmailSecurityTrustedDomainsListArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Account Identifier
        /// </summary>
        [Input("accountId", required: true)]
        public string AccountId { get; set; } = null!;

        /// <summary>
        /// The sorting direction.
        /// Available values: "asc", "desc".
        /// </summary>
        [Input("direction")]
        public string? Direction { get; set; }

        [Input("isRecent")]
        public bool? IsRecent { get; set; }

        [Input("isSimilarity")]
        public bool? IsSimilarity { get; set; }

        /// <summary>
        /// Max items to fetch, default: 1000
        /// </summary>
        [Input("maxItems")]
        public int? MaxItems { get; set; }

        /// <summary>
        /// The field to sort by.
        /// Available values: "pattern", "created_at".
        /// </summary>
        [Input("order")]
        public string? Order { get; set; }

        /// <summary>
        /// Allows searching in multiple properties of a record simultaneously.
        /// This parameter is intended for human users, not automation. Its exact
        /// behavior is intentionally left unspecified and is subject to change
        /// in the future.
        /// </summary>
        [Input("search")]
        public string? Search { get; set; }

        public GetEmailSecurityTrustedDomainsListArgs()
        {
        }
        public static new GetEmailSecurityTrustedDomainsListArgs Empty => new GetEmailSecurityTrustedDomainsListArgs();
    }

    public sealed class GetEmailSecurityTrustedDomainsListInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Account Identifier
        /// </summary>
        [Input("accountId", required: true)]
        public Input<string> AccountId { get; set; } = null!;

        /// <summary>
        /// The sorting direction.
        /// Available values: "asc", "desc".
        /// </summary>
        [Input("direction")]
        public Input<string>? Direction { get; set; }

        [Input("isRecent")]
        public Input<bool>? IsRecent { get; set; }

        [Input("isSimilarity")]
        public Input<bool>? IsSimilarity { get; set; }

        /// <summary>
        /// Max items to fetch, default: 1000
        /// </summary>
        [Input("maxItems")]
        public Input<int>? MaxItems { get; set; }

        /// <summary>
        /// The field to sort by.
        /// Available values: "pattern", "created_at".
        /// </summary>
        [Input("order")]
        public Input<string>? Order { get; set; }

        /// <summary>
        /// Allows searching in multiple properties of a record simultaneously.
        /// This parameter is intended for human users, not automation. Its exact
        /// behavior is intentionally left unspecified and is subject to change
        /// in the future.
        /// </summary>
        [Input("search")]
        public Input<string>? Search { get; set; }

        public GetEmailSecurityTrustedDomainsListInvokeArgs()
        {
        }
        public static new GetEmailSecurityTrustedDomainsListInvokeArgs Empty => new GetEmailSecurityTrustedDomainsListInvokeArgs();
    }


    [OutputType]
    public sealed class GetEmailSecurityTrustedDomainsListResult
    {
        /// <summary>
        /// Account Identifier
        /// </summary>
        public readonly string AccountId;
        /// <summary>
        /// The sorting direction.
        /// Available values: "asc", "desc".
        /// </summary>
        public readonly string? Direction;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly bool? IsRecent;
        public readonly bool? IsSimilarity;
        /// <summary>
        /// Max items to fetch, default: 1000
        /// </summary>
        public readonly int? MaxItems;
        /// <summary>
        /// The field to sort by.
        /// Available values: "pattern", "created_at".
        /// </summary>
        public readonly string? Order;
        /// <summary>
        /// The items returned by the data source
        /// </summary>
        public readonly ImmutableArray<Outputs.GetEmailSecurityTrustedDomainsListResultResult> Results;
        /// <summary>
        /// Allows searching in multiple properties of a record simultaneously.
        /// This parameter is intended for human users, not automation. Its exact
        /// behavior is intentionally left unspecified and is subject to change
        /// in the future.
        /// </summary>
        public readonly string? Search;

        [OutputConstructor]
        private GetEmailSecurityTrustedDomainsListResult(
            string accountId,

            string? direction,

            string id,

            bool? isRecent,

            bool? isSimilarity,

            int? maxItems,

            string? order,

            ImmutableArray<Outputs.GetEmailSecurityTrustedDomainsListResultResult> results,

            string? search)
        {
            AccountId = accountId;
            Direction = direction;
            Id = id;
            IsRecent = isRecent;
            IsSimilarity = isSimilarity;
            MaxItems = maxItems;
            Order = order;
            Results = results;
            Search = search;
        }
    }
}
