// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cloudflare
{
    public static class GetSecretsStores
    {
        /// <summary>
        /// Accepted Permissions
        /// 
        /// - `Secrets Store Read`
        /// - `Secrets Store Write`
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Cloudflare = Pulumi.Cloudflare;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var exampleSecretsStores = Cloudflare.GetSecretsStores.Invoke(new()
        ///     {
        ///         AccountId = "985e105f4ecef8ad9ca31a8372d0c353",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetSecretsStoresResult> InvokeAsync(GetSecretsStoresArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSecretsStoresResult>("cloudflare:index/getSecretsStores:getSecretsStores", args ?? new GetSecretsStoresArgs(), options.WithDefaults());

        /// <summary>
        /// Accepted Permissions
        /// 
        /// - `Secrets Store Read`
        /// - `Secrets Store Write`
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Cloudflare = Pulumi.Cloudflare;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var exampleSecretsStores = Cloudflare.GetSecretsStores.Invoke(new()
        ///     {
        ///         AccountId = "985e105f4ecef8ad9ca31a8372d0c353",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetSecretsStoresResult> Invoke(GetSecretsStoresInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSecretsStoresResult>("cloudflare:index/getSecretsStores:getSecretsStores", args ?? new GetSecretsStoresInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Accepted Permissions
        /// 
        /// - `Secrets Store Read`
        /// - `Secrets Store Write`
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Cloudflare = Pulumi.Cloudflare;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var exampleSecretsStores = Cloudflare.GetSecretsStores.Invoke(new()
        ///     {
        ///         AccountId = "985e105f4ecef8ad9ca31a8372d0c353",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetSecretsStoresResult> Invoke(GetSecretsStoresInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetSecretsStoresResult>("cloudflare:index/getSecretsStores:getSecretsStores", args ?? new GetSecretsStoresInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSecretsStoresArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Account Identifier
        /// </summary>
        [Input("accountId", required: true)]
        public string AccountId { get; set; } = null!;

        /// <summary>
        /// Direction to sort objects
        /// Available values: "asc", "desc".
        /// </summary>
        [Input("direction")]
        public string? Direction { get; set; }

        /// <summary>
        /// Max items to fetch, default: 1000
        /// </summary>
        [Input("maxItems")]
        public int? MaxItems { get; set; }

        /// <summary>
        /// Order secrets by values in the given field
        /// Available values: "name", "comment", "created", "modified", "status".
        /// </summary>
        [Input("order")]
        public string? Order { get; set; }

        public GetSecretsStoresArgs()
        {
        }
        public static new GetSecretsStoresArgs Empty => new GetSecretsStoresArgs();
    }

    public sealed class GetSecretsStoresInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Account Identifier
        /// </summary>
        [Input("accountId", required: true)]
        public Input<string> AccountId { get; set; } = null!;

        /// <summary>
        /// Direction to sort objects
        /// Available values: "asc", "desc".
        /// </summary>
        [Input("direction")]
        public Input<string>? Direction { get; set; }

        /// <summary>
        /// Max items to fetch, default: 1000
        /// </summary>
        [Input("maxItems")]
        public Input<int>? MaxItems { get; set; }

        /// <summary>
        /// Order secrets by values in the given field
        /// Available values: "name", "comment", "created", "modified", "status".
        /// </summary>
        [Input("order")]
        public Input<string>? Order { get; set; }

        public GetSecretsStoresInvokeArgs()
        {
        }
        public static new GetSecretsStoresInvokeArgs Empty => new GetSecretsStoresInvokeArgs();
    }


    [OutputType]
    public sealed class GetSecretsStoresResult
    {
        /// <summary>
        /// Account Identifier
        /// </summary>
        public readonly string AccountId;
        /// <summary>
        /// Direction to sort objects
        /// Available values: "asc", "desc".
        /// </summary>
        public readonly string Direction;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Max items to fetch, default: 1000
        /// </summary>
        public readonly int? MaxItems;
        /// <summary>
        /// Order secrets by values in the given field
        /// Available values: "name", "comment", "created", "modified", "status".
        /// </summary>
        public readonly string Order;
        /// <summary>
        /// The items returned by the data source
        /// </summary>
        public readonly ImmutableArray<Outputs.GetSecretsStoresResultResult> Results;

        [OutputConstructor]
        private GetSecretsStoresResult(
            string accountId,

            string direction,

            string id,

            int? maxItems,

            string order,

            ImmutableArray<Outputs.GetSecretsStoresResultResult> results)
        {
            AccountId = accountId;
            Direction = direction;
            Id = id;
            MaxItems = maxItems;
            Order = order;
            Results = results;
        }
    }
}
