// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cloudflare.Modules.Flagship
{
    public static class GetFlags
    {
        /// <summary>
        /// Accepted Permissions
        /// 
        /// - `Flagship Read`
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Cloudflare = Pulumi.Cloudflare;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var exampleFlagshipFlags = Cloudflare.Modules.Flagship.GetFlags.Invoke(new()
        ///     {
        ///         AccountId = "account_id",
        ///         AppId = "app_id",
        ///         Limit = "limit",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetFlagsResult> InvokeAsync(GetFlagsArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetFlagsResult>("cloudflare:flagship/flags:getFlags", args ?? new GetFlagsArgs(), options.WithDefaults());

        /// <summary>
        /// Accepted Permissions
        /// 
        /// - `Flagship Read`
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Cloudflare = Pulumi.Cloudflare;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var exampleFlagshipFlags = Cloudflare.Modules.Flagship.GetFlags.Invoke(new()
        ///     {
        ///         AccountId = "account_id",
        ///         AppId = "app_id",
        ///         Limit = "limit",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetFlagsResult> Invoke(GetFlagsInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetFlagsResult>("cloudflare:flagship/flags:getFlags", args ?? new GetFlagsInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Accepted Permissions
        /// 
        /// - `Flagship Read`
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Cloudflare = Pulumi.Cloudflare;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var exampleFlagshipFlags = Cloudflare.Modules.Flagship.GetFlags.Invoke(new()
        ///     {
        ///         AccountId = "account_id",
        ///         AppId = "app_id",
        ///         Limit = "limit",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetFlagsResult> Invoke(GetFlagsInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetFlagsResult>("cloudflare:flagship/flags:getFlags", args ?? new GetFlagsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetFlagsArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Cloudflare account ID.
        /// </summary>
        [Input("accountId", required: true)]
        public string AccountId { get; set; } = null!;

        /// <summary>
        /// App identifier.
        /// </summary>
        [Input("appId", required: true)]
        public string AppId { get; set; } = null!;

        /// <summary>
        /// Max items to return (1–200).
        /// </summary>
        [Input("limit")]
        public string? Limit { get; set; }

        /// <summary>
        /// Max items to fetch, default: 1000
        /// </summary>
        [Input("maxItems")]
        public int? MaxItems { get; set; }

        public GetFlagsArgs()
        {
        }
        public static new GetFlagsArgs Empty => new GetFlagsArgs();
    }

    public sealed class GetFlagsInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Cloudflare account ID.
        /// </summary>
        [Input("accountId", required: true)]
        public Input<string> AccountId { get; set; } = null!;

        /// <summary>
        /// App identifier.
        /// </summary>
        [Input("appId", required: true)]
        public Input<string> AppId { get; set; } = null!;

        /// <summary>
        /// Max items to return (1–200).
        /// </summary>
        [Input("limit")]
        public Input<string>? Limit { get; set; }

        /// <summary>
        /// Max items to fetch, default: 1000
        /// </summary>
        [Input("maxItems")]
        public Input<int>? MaxItems { get; set; }

        public GetFlagsInvokeArgs()
        {
        }
        public static new GetFlagsInvokeArgs Empty => new GetFlagsInvokeArgs();
    }


    [OutputType]
    public sealed class GetFlagsResult
    {
        /// <summary>
        /// Cloudflare account ID.
        /// </summary>
        public readonly string AccountId;
        /// <summary>
        /// App identifier.
        /// </summary>
        public readonly string AppId;
        /// <summary>
        /// Max items to return (1–200).
        /// </summary>
        public readonly string? Limit;
        /// <summary>
        /// Max items to fetch, default: 1000
        /// </summary>
        public readonly int? MaxItems;
        /// <summary>
        /// The items returned by the data source
        /// </summary>
        public readonly ImmutableArray<Outputs.GetFlagsResultResult> Results;

        [OutputConstructor]
        private GetFlagsResult(
            string accountId,

            string appId,

            string? limit,

            int? maxItems,

            ImmutableArray<Outputs.GetFlagsResultResult> results)
        {
            AccountId = accountId;
            AppId = appId;
            Limit = limit;
            MaxItems = maxItems;
            Results = results;
        }
    }
}
