// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Accepted Permissions
 *
 * - `Zone Settings Read`
 * - `Zone Settings Write`
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cloudflare from "@pulumi/cloudflare";
 *
 * const exampleArgoSmartRouting = cloudflare.argo.getSmartRouting({
 *     zoneId: "023e105f4ecef8ad9ca31a8372d0c353",
 * });
 * ```
 */
export function getSmartRouting(args?: GetSmartRoutingArgs, opts?: pulumi.InvokeOptions): Promise<GetSmartRoutingResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("cloudflare:argo/smartRouting:getSmartRouting", {
        "zoneId": args.zoneId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSmartRouting.
 */
export interface GetSmartRoutingArgs {
    /**
     * Specifies the zone associated with the API call.
     */
    zoneId?: string;
}

/**
 * A collection of values returned by getSmartRouting.
 */
export interface GetSmartRoutingResult {
    /**
     * Specifies if the setting is editable.
     */
    readonly editable: boolean;
    /**
     * Specifies the zone associated with the API call.
     */
    readonly id: string;
    /**
     * Specifies the time when the setting was last modified.
     */
    readonly modifiedOn: string;
    /**
     * Specifies the enablement value of Argo Smart Routing.
     * Available values: "on", "off".
     */
    readonly value: string;
    /**
     * Specifies the zone associated with the API call.
     */
    readonly zoneId?: string;
}
/**
 * Accepted Permissions
 *
 * - `Zone Settings Read`
 * - `Zone Settings Write`
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cloudflare from "@pulumi/cloudflare";
 *
 * const exampleArgoSmartRouting = cloudflare.argo.getSmartRouting({
 *     zoneId: "023e105f4ecef8ad9ca31a8372d0c353",
 * });
 * ```
 */
export function getSmartRoutingOutput(args?: GetSmartRoutingOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSmartRoutingResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("cloudflare:argo/smartRouting:getSmartRouting", {
        "zoneId": args.zoneId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSmartRouting.
 */
export interface GetSmartRoutingOutputArgs {
    /**
     * Specifies the zone associated with the API call.
     */
    zoneId?: pulumi.Input<string | undefined>;
}
