// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudflare.callsSfu;

import com.pulumi.cloudflare.Utilities;
import com.pulumi.cloudflare.callsSfu.inputs.GetAppArgs;
import com.pulumi.cloudflare.callsSfu.inputs.GetAppPlainArgs;
import com.pulumi.cloudflare.callsSfu.inputs.GetAppsArgs;
import com.pulumi.cloudflare.callsSfu.inputs.GetAppsPlainArgs;
import com.pulumi.cloudflare.callsSfu.outputs.GetAppResult;
import com.pulumi.cloudflare.callsSfu.outputs.GetAppsInvokeResult;
import com.pulumi.core.Output;
import com.pulumi.core.TypeShape;
import com.pulumi.deployment.Deployment;
import com.pulumi.deployment.InvokeOptions;
import com.pulumi.deployment.InvokeOutputOptions;
import java.util.concurrent.CompletableFuture;

public final class CallsSfuFunctions {
    /**
     * Accepted Permissions
     * 
     * - `Calls Read`
     * - `Calls Write`
     * 
     * ## Example Usage
     * 
     * <pre>
     * {@code
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.cloudflare.callsSfu.CallsSfuFunctions;
     * import com.pulumi.cloudflare.callsSfu.inputs.GetAppArgs;
     * import java.util.ArrayList;
     * import java.util.Arrays;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var exampleCallsSfuApp = CallsSfuFunctions.getApp(GetAppArgs.builder()
     *             .accountId("023e105f4ecef8ad9ca31a8372d0c353")
     *             .appId("2a95132c15732412d22c1476fa83f27a")
     *             .build());
     * 
     *     }
     * }
     * }
     * </pre>
     * 
     */
    public static Output<GetAppResult> getApp(GetAppArgs args) {
        return getApp(args, InvokeOptions.Empty);
    }
    /**
     * Accepted Permissions
     * 
     * - `Calls Read`
     * - `Calls Write`
     * 
     * ## Example Usage
     * 
     * <pre>
     * {@code
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.cloudflare.callsSfu.CallsSfuFunctions;
     * import com.pulumi.cloudflare.callsSfu.inputs.GetAppArgs;
     * import java.util.ArrayList;
     * import java.util.Arrays;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var exampleCallsSfuApp = CallsSfuFunctions.getApp(GetAppArgs.builder()
     *             .accountId("023e105f4ecef8ad9ca31a8372d0c353")
     *             .appId("2a95132c15732412d22c1476fa83f27a")
     *             .build());
     * 
     *     }
     * }
     * }
     * </pre>
     * 
     */
    public static CompletableFuture<GetAppResult> getAppPlain(GetAppPlainArgs args) {
        return getAppPlain(args, InvokeOptions.Empty);
    }
    /**
     * Accepted Permissions
     * 
     * - `Calls Read`
     * - `Calls Write`
     * 
     * ## Example Usage
     * 
     * <pre>
     * {@code
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.cloudflare.callsSfu.CallsSfuFunctions;
     * import com.pulumi.cloudflare.callsSfu.inputs.GetAppArgs;
     * import java.util.ArrayList;
     * import java.util.Arrays;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var exampleCallsSfuApp = CallsSfuFunctions.getApp(GetAppArgs.builder()
     *             .accountId("023e105f4ecef8ad9ca31a8372d0c353")
     *             .appId("2a95132c15732412d22c1476fa83f27a")
     *             .build());
     * 
     *     }
     * }
     * }
     * </pre>
     * 
     */
    public static Output<GetAppResult> getApp(GetAppArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("cloudflare:callsSfu/app:getApp", TypeShape.of(GetAppResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Accepted Permissions
     * 
     * - `Calls Read`
     * - `Calls Write`
     * 
     * ## Example Usage
     * 
     * <pre>
     * {@code
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.cloudflare.callsSfu.CallsSfuFunctions;
     * import com.pulumi.cloudflare.callsSfu.inputs.GetAppArgs;
     * import java.util.ArrayList;
     * import java.util.Arrays;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var exampleCallsSfuApp = CallsSfuFunctions.getApp(GetAppArgs.builder()
     *             .accountId("023e105f4ecef8ad9ca31a8372d0c353")
     *             .appId("2a95132c15732412d22c1476fa83f27a")
     *             .build());
     * 
     *     }
     * }
     * }
     * </pre>
     * 
     */
    public static Output<GetAppResult> getApp(GetAppArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("cloudflare:callsSfu/app:getApp", TypeShape.of(GetAppResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Accepted Permissions
     * 
     * - `Calls Read`
     * - `Calls Write`
     * 
     * ## Example Usage
     * 
     * <pre>
     * {@code
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.cloudflare.callsSfu.CallsSfuFunctions;
     * import com.pulumi.cloudflare.callsSfu.inputs.GetAppArgs;
     * import java.util.ArrayList;
     * import java.util.Arrays;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var exampleCallsSfuApp = CallsSfuFunctions.getApp(GetAppArgs.builder()
     *             .accountId("023e105f4ecef8ad9ca31a8372d0c353")
     *             .appId("2a95132c15732412d22c1476fa83f27a")
     *             .build());
     * 
     *     }
     * }
     * }
     * </pre>
     * 
     */
    public static CompletableFuture<GetAppResult> getAppPlain(GetAppPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("cloudflare:callsSfu/app:getApp", TypeShape.of(GetAppResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Accepted Permissions
     * 
     * - `Calls Read`
     * - `Calls Write`
     * 
     * ## Example Usage
     * 
     * <pre>
     * {@code
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.cloudflare.callsSfu.CallsSfuFunctions;
     * import com.pulumi.cloudflare.callsSfu.inputs.GetAppsArgs;
     * import java.util.ArrayList;
     * import java.util.Arrays;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var exampleCallsSfuApps = CallsSfuFunctions.getApps(GetAppsArgs.builder()
     *             .accountId("023e105f4ecef8ad9ca31a8372d0c353")
     *             .build());
     * 
     *     }
     * }
     * }
     * </pre>
     * 
     */
    public static Output<GetAppsInvokeResult> getApps() {
        return getApps(GetAppsArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * Accepted Permissions
     * 
     * - `Calls Read`
     * - `Calls Write`
     * 
     * ## Example Usage
     * 
     * <pre>
     * {@code
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.cloudflare.callsSfu.CallsSfuFunctions;
     * import com.pulumi.cloudflare.callsSfu.inputs.GetAppsArgs;
     * import java.util.ArrayList;
     * import java.util.Arrays;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var exampleCallsSfuApps = CallsSfuFunctions.getApps(GetAppsArgs.builder()
     *             .accountId("023e105f4ecef8ad9ca31a8372d0c353")
     *             .build());
     * 
     *     }
     * }
     * }
     * </pre>
     * 
     */
    public static CompletableFuture<GetAppsInvokeResult> getAppsPlain() {
        return getAppsPlain(GetAppsPlainArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * Accepted Permissions
     * 
     * - `Calls Read`
     * - `Calls Write`
     * 
     * ## Example Usage
     * 
     * <pre>
     * {@code
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.cloudflare.callsSfu.CallsSfuFunctions;
     * import com.pulumi.cloudflare.callsSfu.inputs.GetAppsArgs;
     * import java.util.ArrayList;
     * import java.util.Arrays;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var exampleCallsSfuApps = CallsSfuFunctions.getApps(GetAppsArgs.builder()
     *             .accountId("023e105f4ecef8ad9ca31a8372d0c353")
     *             .build());
     * 
     *     }
     * }
     * }
     * </pre>
     * 
     */
    public static Output<GetAppsInvokeResult> getApps(GetAppsArgs args) {
        return getApps(args, InvokeOptions.Empty);
    }
    /**
     * Accepted Permissions
     * 
     * - `Calls Read`
     * - `Calls Write`
     * 
     * ## Example Usage
     * 
     * <pre>
     * {@code
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.cloudflare.callsSfu.CallsSfuFunctions;
     * import com.pulumi.cloudflare.callsSfu.inputs.GetAppsArgs;
     * import java.util.ArrayList;
     * import java.util.Arrays;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var exampleCallsSfuApps = CallsSfuFunctions.getApps(GetAppsArgs.builder()
     *             .accountId("023e105f4ecef8ad9ca31a8372d0c353")
     *             .build());
     * 
     *     }
     * }
     * }
     * </pre>
     * 
     */
    public static CompletableFuture<GetAppsInvokeResult> getAppsPlain(GetAppsPlainArgs args) {
        return getAppsPlain(args, InvokeOptions.Empty);
    }
    /**
     * Accepted Permissions
     * 
     * - `Calls Read`
     * - `Calls Write`
     * 
     * ## Example Usage
     * 
     * <pre>
     * {@code
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.cloudflare.callsSfu.CallsSfuFunctions;
     * import com.pulumi.cloudflare.callsSfu.inputs.GetAppsArgs;
     * import java.util.ArrayList;
     * import java.util.Arrays;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var exampleCallsSfuApps = CallsSfuFunctions.getApps(GetAppsArgs.builder()
     *             .accountId("023e105f4ecef8ad9ca31a8372d0c353")
     *             .build());
     * 
     *     }
     * }
     * }
     * </pre>
     * 
     */
    public static Output<GetAppsInvokeResult> getApps(GetAppsArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("cloudflare:callsSfu/apps:getApps", TypeShape.of(GetAppsInvokeResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Accepted Permissions
     * 
     * - `Calls Read`
     * - `Calls Write`
     * 
     * ## Example Usage
     * 
     * <pre>
     * {@code
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.cloudflare.callsSfu.CallsSfuFunctions;
     * import com.pulumi.cloudflare.callsSfu.inputs.GetAppsArgs;
     * import java.util.ArrayList;
     * import java.util.Arrays;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var exampleCallsSfuApps = CallsSfuFunctions.getApps(GetAppsArgs.builder()
     *             .accountId("023e105f4ecef8ad9ca31a8372d0c353")
     *             .build());
     * 
     *     }
     * }
     * }
     * </pre>
     * 
     */
    public static Output<GetAppsInvokeResult> getApps(GetAppsArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("cloudflare:callsSfu/apps:getApps", TypeShape.of(GetAppsInvokeResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Accepted Permissions
     * 
     * - `Calls Read`
     * - `Calls Write`
     * 
     * ## Example Usage
     * 
     * <pre>
     * {@code
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.cloudflare.callsSfu.CallsSfuFunctions;
     * import com.pulumi.cloudflare.callsSfu.inputs.GetAppsArgs;
     * import java.util.ArrayList;
     * import java.util.Arrays;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var exampleCallsSfuApps = CallsSfuFunctions.getApps(GetAppsArgs.builder()
     *             .accountId("023e105f4ecef8ad9ca31a8372d0c353")
     *             .build());
     * 
     *     }
     * }
     * }
     * </pre>
     * 
     */
    public static CompletableFuture<GetAppsInvokeResult> getAppsPlain(GetAppsPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("cloudflare:callsSfu/apps:getApps", TypeShape.of(GetAppsInvokeResult.class), args, Utilities.withVersion(options));
    }
}
