// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package customorigintrust

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-cloudflare/sdk/v6/go/cloudflare/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type GetStoreFilter struct {
	// Limit to the number of records returned.
	Limit *int `pulumi:"limit"`
	// Offset the results.
	Offset *int `pulumi:"offset"`
}

// GetStoreFilterInput is an input type that accepts GetStoreFilterArgs and GetStoreFilterOutput values.
// You can construct a concrete instance of `GetStoreFilterInput` via:
//
//	GetStoreFilterArgs{...}
type GetStoreFilterInput interface {
	pulumi.Input

	ToGetStoreFilterOutput() GetStoreFilterOutput
	ToGetStoreFilterOutputWithContext(context.Context) GetStoreFilterOutput
}

type GetStoreFilterArgs struct {
	// Limit to the number of records returned.
	Limit pulumi.IntPtrInput `pulumi:"limit"`
	// Offset the results.
	Offset pulumi.IntPtrInput `pulumi:"offset"`
}

func (GetStoreFilterArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetStoreFilter)(nil)).Elem()
}

func (i GetStoreFilterArgs) ToGetStoreFilterOutput() GetStoreFilterOutput {
	return i.ToGetStoreFilterOutputWithContext(context.Background())
}

func (i GetStoreFilterArgs) ToGetStoreFilterOutputWithContext(ctx context.Context) GetStoreFilterOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetStoreFilterOutput)
}

func (i GetStoreFilterArgs) ToGetStoreFilterPtrOutput() GetStoreFilterPtrOutput {
	return i.ToGetStoreFilterPtrOutputWithContext(context.Background())
}

func (i GetStoreFilterArgs) ToGetStoreFilterPtrOutputWithContext(ctx context.Context) GetStoreFilterPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetStoreFilterOutput).ToGetStoreFilterPtrOutputWithContext(ctx)
}

// GetStoreFilterPtrInput is an input type that accepts GetStoreFilterArgs, GetStoreFilterPtr and GetStoreFilterPtrOutput values.
// You can construct a concrete instance of `GetStoreFilterPtrInput` via:
//
//	        GetStoreFilterArgs{...}
//
//	or:
//
//	        nil
type GetStoreFilterPtrInput interface {
	pulumi.Input

	ToGetStoreFilterPtrOutput() GetStoreFilterPtrOutput
	ToGetStoreFilterPtrOutputWithContext(context.Context) GetStoreFilterPtrOutput
}

type getStoreFilterPtrType GetStoreFilterArgs

func GetStoreFilterPtr(v *GetStoreFilterArgs) GetStoreFilterPtrInput {
	return (*getStoreFilterPtrType)(v)
}

func (*getStoreFilterPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**GetStoreFilter)(nil)).Elem()
}

func (i *getStoreFilterPtrType) ToGetStoreFilterPtrOutput() GetStoreFilterPtrOutput {
	return i.ToGetStoreFilterPtrOutputWithContext(context.Background())
}

func (i *getStoreFilterPtrType) ToGetStoreFilterPtrOutputWithContext(ctx context.Context) GetStoreFilterPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetStoreFilterPtrOutput)
}

type GetStoreFilterOutput struct{ *pulumi.OutputState }

func (GetStoreFilterOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetStoreFilter)(nil)).Elem()
}

func (o GetStoreFilterOutput) ToGetStoreFilterOutput() GetStoreFilterOutput {
	return o
}

func (o GetStoreFilterOutput) ToGetStoreFilterOutputWithContext(ctx context.Context) GetStoreFilterOutput {
	return o
}

func (o GetStoreFilterOutput) ToGetStoreFilterPtrOutput() GetStoreFilterPtrOutput {
	return o.ToGetStoreFilterPtrOutputWithContext(context.Background())
}

func (o GetStoreFilterOutput) ToGetStoreFilterPtrOutputWithContext(ctx context.Context) GetStoreFilterPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v GetStoreFilter) *GetStoreFilter {
		return &v
	}).(GetStoreFilterPtrOutput)
}

// Limit to the number of records returned.
func (o GetStoreFilterOutput) Limit() pulumi.IntPtrOutput {
	return o.ApplyT(func(v GetStoreFilter) *int { return v.Limit }).(pulumi.IntPtrOutput)
}

// Offset the results.
func (o GetStoreFilterOutput) Offset() pulumi.IntPtrOutput {
	return o.ApplyT(func(v GetStoreFilter) *int { return v.Offset }).(pulumi.IntPtrOutput)
}

type GetStoreFilterPtrOutput struct{ *pulumi.OutputState }

func (GetStoreFilterPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**GetStoreFilter)(nil)).Elem()
}

func (o GetStoreFilterPtrOutput) ToGetStoreFilterPtrOutput() GetStoreFilterPtrOutput {
	return o
}

func (o GetStoreFilterPtrOutput) ToGetStoreFilterPtrOutputWithContext(ctx context.Context) GetStoreFilterPtrOutput {
	return o
}

func (o GetStoreFilterPtrOutput) Elem() GetStoreFilterOutput {
	return o.ApplyT(func(v *GetStoreFilter) GetStoreFilter {
		if v != nil {
			return *v
		}
		var ret GetStoreFilter
		return ret
	}).(GetStoreFilterOutput)
}

// Limit to the number of records returned.
func (o GetStoreFilterPtrOutput) Limit() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *GetStoreFilter) *int {
		if v == nil {
			return nil
		}
		return v.Limit
	}).(pulumi.IntPtrOutput)
}

// Offset the results.
func (o GetStoreFilterPtrOutput) Offset() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *GetStoreFilter) *int {
		if v == nil {
			return nil
		}
		return v.Offset
	}).(pulumi.IntPtrOutput)
}

type GetStoresResult struct {
	// The root CA certificate in PEM format. Only root CA certificates are accepted; intermediate and leaf certificates are not supported.
	Certificate string `pulumi:"certificate"`
	// When the certificate expires.
	ExpiresOn string `pulumi:"expiresOn"`
	// Identifier.
	Id string `pulumi:"id"`
	// The certificate authority that issued the certificate.
	Issuer string `pulumi:"issuer"`
	// The type of hash used for the certificate.
	Signature string `pulumi:"signature"`
	// Status of the zone's custom SSL.
	// Available values: "initializing", "pending*deployment", "active", "pending*deletion", "deleted", "expired".
	Status string `pulumi:"status"`
	// When the certificate was last modified.
	UpdatedAt string `pulumi:"updatedAt"`
	// When the certificate was uploaded to Cloudflare.
	UploadedOn string `pulumi:"uploadedOn"`
}

// GetStoresResultInput is an input type that accepts GetStoresResultArgs and GetStoresResultOutput values.
// You can construct a concrete instance of `GetStoresResultInput` via:
//
//	GetStoresResultArgs{...}
type GetStoresResultInput interface {
	pulumi.Input

	ToGetStoresResultOutput() GetStoresResultOutput
	ToGetStoresResultOutputWithContext(context.Context) GetStoresResultOutput
}

type GetStoresResultArgs struct {
	// The root CA certificate in PEM format. Only root CA certificates are accepted; intermediate and leaf certificates are not supported.
	Certificate pulumi.StringInput `pulumi:"certificate"`
	// When the certificate expires.
	ExpiresOn pulumi.StringInput `pulumi:"expiresOn"`
	// Identifier.
	Id pulumi.StringInput `pulumi:"id"`
	// The certificate authority that issued the certificate.
	Issuer pulumi.StringInput `pulumi:"issuer"`
	// The type of hash used for the certificate.
	Signature pulumi.StringInput `pulumi:"signature"`
	// Status of the zone's custom SSL.
	// Available values: "initializing", "pending*deployment", "active", "pending*deletion", "deleted", "expired".
	Status pulumi.StringInput `pulumi:"status"`
	// When the certificate was last modified.
	UpdatedAt pulumi.StringInput `pulumi:"updatedAt"`
	// When the certificate was uploaded to Cloudflare.
	UploadedOn pulumi.StringInput `pulumi:"uploadedOn"`
}

func (GetStoresResultArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetStoresResult)(nil)).Elem()
}

func (i GetStoresResultArgs) ToGetStoresResultOutput() GetStoresResultOutput {
	return i.ToGetStoresResultOutputWithContext(context.Background())
}

func (i GetStoresResultArgs) ToGetStoresResultOutputWithContext(ctx context.Context) GetStoresResultOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetStoresResultOutput)
}

// GetStoresResultArrayInput is an input type that accepts GetStoresResultArray and GetStoresResultArrayOutput values.
// You can construct a concrete instance of `GetStoresResultArrayInput` via:
//
//	GetStoresResultArray{ GetStoresResultArgs{...} }
type GetStoresResultArrayInput interface {
	pulumi.Input

	ToGetStoresResultArrayOutput() GetStoresResultArrayOutput
	ToGetStoresResultArrayOutputWithContext(context.Context) GetStoresResultArrayOutput
}

type GetStoresResultArray []GetStoresResultInput

func (GetStoresResultArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetStoresResult)(nil)).Elem()
}

func (i GetStoresResultArray) ToGetStoresResultArrayOutput() GetStoresResultArrayOutput {
	return i.ToGetStoresResultArrayOutputWithContext(context.Background())
}

func (i GetStoresResultArray) ToGetStoresResultArrayOutputWithContext(ctx context.Context) GetStoresResultArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetStoresResultArrayOutput)
}

type GetStoresResultOutput struct{ *pulumi.OutputState }

func (GetStoresResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetStoresResult)(nil)).Elem()
}

func (o GetStoresResultOutput) ToGetStoresResultOutput() GetStoresResultOutput {
	return o
}

func (o GetStoresResultOutput) ToGetStoresResultOutputWithContext(ctx context.Context) GetStoresResultOutput {
	return o
}

// The root CA certificate in PEM format. Only root CA certificates are accepted; intermediate and leaf certificates are not supported.
func (o GetStoresResultOutput) Certificate() pulumi.StringOutput {
	return o.ApplyT(func(v GetStoresResult) string { return v.Certificate }).(pulumi.StringOutput)
}

// When the certificate expires.
func (o GetStoresResultOutput) ExpiresOn() pulumi.StringOutput {
	return o.ApplyT(func(v GetStoresResult) string { return v.ExpiresOn }).(pulumi.StringOutput)
}

// Identifier.
func (o GetStoresResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetStoresResult) string { return v.Id }).(pulumi.StringOutput)
}

// The certificate authority that issued the certificate.
func (o GetStoresResultOutput) Issuer() pulumi.StringOutput {
	return o.ApplyT(func(v GetStoresResult) string { return v.Issuer }).(pulumi.StringOutput)
}

// The type of hash used for the certificate.
func (o GetStoresResultOutput) Signature() pulumi.StringOutput {
	return o.ApplyT(func(v GetStoresResult) string { return v.Signature }).(pulumi.StringOutput)
}

// Status of the zone's custom SSL.
// Available values: "initializing", "pending*deployment", "active", "pending*deletion", "deleted", "expired".
func (o GetStoresResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v GetStoresResult) string { return v.Status }).(pulumi.StringOutput)
}

// When the certificate was last modified.
func (o GetStoresResultOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v GetStoresResult) string { return v.UpdatedAt }).(pulumi.StringOutput)
}

// When the certificate was uploaded to Cloudflare.
func (o GetStoresResultOutput) UploadedOn() pulumi.StringOutput {
	return o.ApplyT(func(v GetStoresResult) string { return v.UploadedOn }).(pulumi.StringOutput)
}

type GetStoresResultArrayOutput struct{ *pulumi.OutputState }

func (GetStoresResultArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetStoresResult)(nil)).Elem()
}

func (o GetStoresResultArrayOutput) ToGetStoresResultArrayOutput() GetStoresResultArrayOutput {
	return o
}

func (o GetStoresResultArrayOutput) ToGetStoresResultArrayOutputWithContext(ctx context.Context) GetStoresResultArrayOutput {
	return o
}

func (o GetStoresResultArrayOutput) Index(i pulumi.IntInput) GetStoresResultOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetStoresResult {
		return vs[0].([]GetStoresResult)[vs[1].(int)]
	}).(GetStoresResultOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*GetStoreFilterInput)(nil)).Elem(), GetStoreFilterArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetStoreFilterPtrInput)(nil)).Elem(), GetStoreFilterArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetStoresResultInput)(nil)).Elem(), GetStoresResultArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetStoresResultArrayInput)(nil)).Elem(), GetStoresResultArray{})
	pulumi.RegisterOutputType(GetStoreFilterOutput{})
	pulumi.RegisterOutputType(GetStoreFilterPtrOutput{})
	pulumi.RegisterOutputType(GetStoresResultOutput{})
	pulumi.RegisterOutputType(GetStoresResultArrayOutput{})
}
