// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cloudflare.Outputs
{

    [OutputType]
    public sealed class GetAccountMembersResultResult
    {
        /// <summary>
        /// The contact email address of the user.
        /// </summary>
        public readonly string Email;
        /// <summary>
        /// Membership identifier tag.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Access policy for the membership
        /// </summary>
        public readonly ImmutableArray<Outputs.GetAccountMembersResultPolicyResult> Policies;
        /// <summary>
        /// Roles assigned to this Member.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetAccountMembersResultRoleResult> Roles;
        /// <summary>
        /// A member's status in the account.
        /// Available values: "accepted", "pending".
        /// </summary>
        public readonly string Status;
        /// <summary>
        /// Details of the user associated to the membership.
        /// </summary>
        public readonly Outputs.GetAccountMembersResultUserResult User;

        [OutputConstructor]
        private GetAccountMembersResultResult(
            string email,

            string id,

            ImmutableArray<Outputs.GetAccountMembersResultPolicyResult> policies,

            ImmutableArray<Outputs.GetAccountMembersResultRoleResult> roles,

            string status,

            Outputs.GetAccountMembersResultUserResult user)
        {
            Email = email;
            Id = id;
            Policies = policies;
            Roles = roles;
            Status = status;
            User = user;
        }
    }
}
