// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudflare.zeroTrustAccess.inputs;

import com.pulumi.cloudflare.zeroTrustAccess.inputs.ApplicationPolicyRequireAnyValidServiceTokenArgs;
import com.pulumi.cloudflare.zeroTrustAccess.inputs.ApplicationPolicyRequireAuthContextArgs;
import com.pulumi.cloudflare.zeroTrustAccess.inputs.ApplicationPolicyRequireAuthMethodArgs;
import com.pulumi.cloudflare.zeroTrustAccess.inputs.ApplicationPolicyRequireAzureAdArgs;
import com.pulumi.cloudflare.zeroTrustAccess.inputs.ApplicationPolicyRequireCertificateArgs;
import com.pulumi.cloudflare.zeroTrustAccess.inputs.ApplicationPolicyRequireCommonNameArgs;
import com.pulumi.cloudflare.zeroTrustAccess.inputs.ApplicationPolicyRequireDevicePostureArgs;
import com.pulumi.cloudflare.zeroTrustAccess.inputs.ApplicationPolicyRequireEmailArgs;
import com.pulumi.cloudflare.zeroTrustAccess.inputs.ApplicationPolicyRequireEmailDomainArgs;
import com.pulumi.cloudflare.zeroTrustAccess.inputs.ApplicationPolicyRequireEmailListArgs;
import com.pulumi.cloudflare.zeroTrustAccess.inputs.ApplicationPolicyRequireEveryoneArgs;
import com.pulumi.cloudflare.zeroTrustAccess.inputs.ApplicationPolicyRequireExternalEvaluationArgs;
import com.pulumi.cloudflare.zeroTrustAccess.inputs.ApplicationPolicyRequireGeoArgs;
import com.pulumi.cloudflare.zeroTrustAccess.inputs.ApplicationPolicyRequireGithubOrganizationArgs;
import com.pulumi.cloudflare.zeroTrustAccess.inputs.ApplicationPolicyRequireGroupArgs;
import com.pulumi.cloudflare.zeroTrustAccess.inputs.ApplicationPolicyRequireGsuiteArgs;
import com.pulumi.cloudflare.zeroTrustAccess.inputs.ApplicationPolicyRequireIpArgs;
import com.pulumi.cloudflare.zeroTrustAccess.inputs.ApplicationPolicyRequireIpListArgs;
import com.pulumi.cloudflare.zeroTrustAccess.inputs.ApplicationPolicyRequireLinkedAppTokenArgs;
import com.pulumi.cloudflare.zeroTrustAccess.inputs.ApplicationPolicyRequireLoginMethodArgs;
import com.pulumi.cloudflare.zeroTrustAccess.inputs.ApplicationPolicyRequireOidcArgs;
import com.pulumi.cloudflare.zeroTrustAccess.inputs.ApplicationPolicyRequireOktaArgs;
import com.pulumi.cloudflare.zeroTrustAccess.inputs.ApplicationPolicyRequireSamlArgs;
import com.pulumi.cloudflare.zeroTrustAccess.inputs.ApplicationPolicyRequireServiceTokenArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ApplicationPolicyRequireArgs extends com.pulumi.resources.ResourceArgs {

    public static final ApplicationPolicyRequireArgs Empty = new ApplicationPolicyRequireArgs();

    /**
     * An empty object which matches on all service tokens.
     * 
     */
    @Import(name="anyValidServiceToken")
    private @Nullable Output<ApplicationPolicyRequireAnyValidServiceTokenArgs> anyValidServiceToken;

    /**
     * @return An empty object which matches on all service tokens.
     * 
     */
    public Optional<Output<ApplicationPolicyRequireAnyValidServiceTokenArgs>> anyValidServiceToken() {
        return Optional.ofNullable(this.anyValidServiceToken);
    }

    @Import(name="authContext")
    private @Nullable Output<ApplicationPolicyRequireAuthContextArgs> authContext;

    public Optional<Output<ApplicationPolicyRequireAuthContextArgs>> authContext() {
        return Optional.ofNullable(this.authContext);
    }

    @Import(name="authMethod")
    private @Nullable Output<ApplicationPolicyRequireAuthMethodArgs> authMethod;

    public Optional<Output<ApplicationPolicyRequireAuthMethodArgs>> authMethod() {
        return Optional.ofNullable(this.authMethod);
    }

    @Import(name="azureAd")
    private @Nullable Output<ApplicationPolicyRequireAzureAdArgs> azureAd;

    public Optional<Output<ApplicationPolicyRequireAzureAdArgs>> azureAd() {
        return Optional.ofNullable(this.azureAd);
    }

    @Import(name="certificate")
    private @Nullable Output<ApplicationPolicyRequireCertificateArgs> certificate;

    public Optional<Output<ApplicationPolicyRequireCertificateArgs>> certificate() {
        return Optional.ofNullable(this.certificate);
    }

    @Import(name="commonName")
    private @Nullable Output<ApplicationPolicyRequireCommonNameArgs> commonName;

    public Optional<Output<ApplicationPolicyRequireCommonNameArgs>> commonName() {
        return Optional.ofNullable(this.commonName);
    }

    @Import(name="devicePosture")
    private @Nullable Output<ApplicationPolicyRequireDevicePostureArgs> devicePosture;

    public Optional<Output<ApplicationPolicyRequireDevicePostureArgs>> devicePosture() {
        return Optional.ofNullable(this.devicePosture);
    }

    @Import(name="email")
    private @Nullable Output<ApplicationPolicyRequireEmailArgs> email;

    public Optional<Output<ApplicationPolicyRequireEmailArgs>> email() {
        return Optional.ofNullable(this.email);
    }

    @Import(name="emailDomain")
    private @Nullable Output<ApplicationPolicyRequireEmailDomainArgs> emailDomain;

    public Optional<Output<ApplicationPolicyRequireEmailDomainArgs>> emailDomain() {
        return Optional.ofNullable(this.emailDomain);
    }

    @Import(name="emailList")
    private @Nullable Output<ApplicationPolicyRequireEmailListArgs> emailList;

    public Optional<Output<ApplicationPolicyRequireEmailListArgs>> emailList() {
        return Optional.ofNullable(this.emailList);
    }

    /**
     * An empty object which matches on all users.
     * 
     */
    @Import(name="everyone")
    private @Nullable Output<ApplicationPolicyRequireEveryoneArgs> everyone;

    /**
     * @return An empty object which matches on all users.
     * 
     */
    public Optional<Output<ApplicationPolicyRequireEveryoneArgs>> everyone() {
        return Optional.ofNullable(this.everyone);
    }

    @Import(name="externalEvaluation")
    private @Nullable Output<ApplicationPolicyRequireExternalEvaluationArgs> externalEvaluation;

    public Optional<Output<ApplicationPolicyRequireExternalEvaluationArgs>> externalEvaluation() {
        return Optional.ofNullable(this.externalEvaluation);
    }

    @Import(name="geo")
    private @Nullable Output<ApplicationPolicyRequireGeoArgs> geo;

    public Optional<Output<ApplicationPolicyRequireGeoArgs>> geo() {
        return Optional.ofNullable(this.geo);
    }

    @Import(name="githubOrganization")
    private @Nullable Output<ApplicationPolicyRequireGithubOrganizationArgs> githubOrganization;

    public Optional<Output<ApplicationPolicyRequireGithubOrganizationArgs>> githubOrganization() {
        return Optional.ofNullable(this.githubOrganization);
    }

    @Import(name="group")
    private @Nullable Output<ApplicationPolicyRequireGroupArgs> group;

    public Optional<Output<ApplicationPolicyRequireGroupArgs>> group() {
        return Optional.ofNullable(this.group);
    }

    @Import(name="gsuite")
    private @Nullable Output<ApplicationPolicyRequireGsuiteArgs> gsuite;

    public Optional<Output<ApplicationPolicyRequireGsuiteArgs>> gsuite() {
        return Optional.ofNullable(this.gsuite);
    }

    @Import(name="ip")
    private @Nullable Output<ApplicationPolicyRequireIpArgs> ip;

    public Optional<Output<ApplicationPolicyRequireIpArgs>> ip() {
        return Optional.ofNullable(this.ip);
    }

    @Import(name="ipList")
    private @Nullable Output<ApplicationPolicyRequireIpListArgs> ipList;

    public Optional<Output<ApplicationPolicyRequireIpListArgs>> ipList() {
        return Optional.ofNullable(this.ipList);
    }

    @Import(name="linkedAppToken")
    private @Nullable Output<ApplicationPolicyRequireLinkedAppTokenArgs> linkedAppToken;

    public Optional<Output<ApplicationPolicyRequireLinkedAppTokenArgs>> linkedAppToken() {
        return Optional.ofNullable(this.linkedAppToken);
    }

    @Import(name="loginMethod")
    private @Nullable Output<ApplicationPolicyRequireLoginMethodArgs> loginMethod;

    public Optional<Output<ApplicationPolicyRequireLoginMethodArgs>> loginMethod() {
        return Optional.ofNullable(this.loginMethod);
    }

    @Import(name="oidc")
    private @Nullable Output<ApplicationPolicyRequireOidcArgs> oidc;

    public Optional<Output<ApplicationPolicyRequireOidcArgs>> oidc() {
        return Optional.ofNullable(this.oidc);
    }

    @Import(name="okta")
    private @Nullable Output<ApplicationPolicyRequireOktaArgs> okta;

    public Optional<Output<ApplicationPolicyRequireOktaArgs>> okta() {
        return Optional.ofNullable(this.okta);
    }

    @Import(name="saml")
    private @Nullable Output<ApplicationPolicyRequireSamlArgs> saml;

    public Optional<Output<ApplicationPolicyRequireSamlArgs>> saml() {
        return Optional.ofNullable(this.saml);
    }

    @Import(name="serviceToken")
    private @Nullable Output<ApplicationPolicyRequireServiceTokenArgs> serviceToken;

    public Optional<Output<ApplicationPolicyRequireServiceTokenArgs>> serviceToken() {
        return Optional.ofNullable(this.serviceToken);
    }

    private ApplicationPolicyRequireArgs() {}

    private ApplicationPolicyRequireArgs(ApplicationPolicyRequireArgs $) {
        this.anyValidServiceToken = $.anyValidServiceToken;
        this.authContext = $.authContext;
        this.authMethod = $.authMethod;
        this.azureAd = $.azureAd;
        this.certificate = $.certificate;
        this.commonName = $.commonName;
        this.devicePosture = $.devicePosture;
        this.email = $.email;
        this.emailDomain = $.emailDomain;
        this.emailList = $.emailList;
        this.everyone = $.everyone;
        this.externalEvaluation = $.externalEvaluation;
        this.geo = $.geo;
        this.githubOrganization = $.githubOrganization;
        this.group = $.group;
        this.gsuite = $.gsuite;
        this.ip = $.ip;
        this.ipList = $.ipList;
        this.linkedAppToken = $.linkedAppToken;
        this.loginMethod = $.loginMethod;
        this.oidc = $.oidc;
        this.okta = $.okta;
        this.saml = $.saml;
        this.serviceToken = $.serviceToken;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ApplicationPolicyRequireArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ApplicationPolicyRequireArgs $;

        public Builder() {
            $ = new ApplicationPolicyRequireArgs();
        }

        public Builder(ApplicationPolicyRequireArgs defaults) {
            $ = new ApplicationPolicyRequireArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param anyValidServiceToken An empty object which matches on all service tokens.
         * 
         * @return builder
         * 
         */
        public Builder anyValidServiceToken(@Nullable Output<ApplicationPolicyRequireAnyValidServiceTokenArgs> anyValidServiceToken) {
            $.anyValidServiceToken = anyValidServiceToken;
            return this;
        }

        /**
         * @param anyValidServiceToken An empty object which matches on all service tokens.
         * 
         * @return builder
         * 
         */
        public Builder anyValidServiceToken(ApplicationPolicyRequireAnyValidServiceTokenArgs anyValidServiceToken) {
            return anyValidServiceToken(Output.of(anyValidServiceToken));
        }

        public Builder authContext(@Nullable Output<ApplicationPolicyRequireAuthContextArgs> authContext) {
            $.authContext = authContext;
            return this;
        }

        public Builder authContext(ApplicationPolicyRequireAuthContextArgs authContext) {
            return authContext(Output.of(authContext));
        }

        public Builder authMethod(@Nullable Output<ApplicationPolicyRequireAuthMethodArgs> authMethod) {
            $.authMethod = authMethod;
            return this;
        }

        public Builder authMethod(ApplicationPolicyRequireAuthMethodArgs authMethod) {
            return authMethod(Output.of(authMethod));
        }

        public Builder azureAd(@Nullable Output<ApplicationPolicyRequireAzureAdArgs> azureAd) {
            $.azureAd = azureAd;
            return this;
        }

        public Builder azureAd(ApplicationPolicyRequireAzureAdArgs azureAd) {
            return azureAd(Output.of(azureAd));
        }

        public Builder certificate(@Nullable Output<ApplicationPolicyRequireCertificateArgs> certificate) {
            $.certificate = certificate;
            return this;
        }

        public Builder certificate(ApplicationPolicyRequireCertificateArgs certificate) {
            return certificate(Output.of(certificate));
        }

        public Builder commonName(@Nullable Output<ApplicationPolicyRequireCommonNameArgs> commonName) {
            $.commonName = commonName;
            return this;
        }

        public Builder commonName(ApplicationPolicyRequireCommonNameArgs commonName) {
            return commonName(Output.of(commonName));
        }

        public Builder devicePosture(@Nullable Output<ApplicationPolicyRequireDevicePostureArgs> devicePosture) {
            $.devicePosture = devicePosture;
            return this;
        }

        public Builder devicePosture(ApplicationPolicyRequireDevicePostureArgs devicePosture) {
            return devicePosture(Output.of(devicePosture));
        }

        public Builder email(@Nullable Output<ApplicationPolicyRequireEmailArgs> email) {
            $.email = email;
            return this;
        }

        public Builder email(ApplicationPolicyRequireEmailArgs email) {
            return email(Output.of(email));
        }

        public Builder emailDomain(@Nullable Output<ApplicationPolicyRequireEmailDomainArgs> emailDomain) {
            $.emailDomain = emailDomain;
            return this;
        }

        public Builder emailDomain(ApplicationPolicyRequireEmailDomainArgs emailDomain) {
            return emailDomain(Output.of(emailDomain));
        }

        public Builder emailList(@Nullable Output<ApplicationPolicyRequireEmailListArgs> emailList) {
            $.emailList = emailList;
            return this;
        }

        public Builder emailList(ApplicationPolicyRequireEmailListArgs emailList) {
            return emailList(Output.of(emailList));
        }

        /**
         * @param everyone An empty object which matches on all users.
         * 
         * @return builder
         * 
         */
        public Builder everyone(@Nullable Output<ApplicationPolicyRequireEveryoneArgs> everyone) {
            $.everyone = everyone;
            return this;
        }

        /**
         * @param everyone An empty object which matches on all users.
         * 
         * @return builder
         * 
         */
        public Builder everyone(ApplicationPolicyRequireEveryoneArgs everyone) {
            return everyone(Output.of(everyone));
        }

        public Builder externalEvaluation(@Nullable Output<ApplicationPolicyRequireExternalEvaluationArgs> externalEvaluation) {
            $.externalEvaluation = externalEvaluation;
            return this;
        }

        public Builder externalEvaluation(ApplicationPolicyRequireExternalEvaluationArgs externalEvaluation) {
            return externalEvaluation(Output.of(externalEvaluation));
        }

        public Builder geo(@Nullable Output<ApplicationPolicyRequireGeoArgs> geo) {
            $.geo = geo;
            return this;
        }

        public Builder geo(ApplicationPolicyRequireGeoArgs geo) {
            return geo(Output.of(geo));
        }

        public Builder githubOrganization(@Nullable Output<ApplicationPolicyRequireGithubOrganizationArgs> githubOrganization) {
            $.githubOrganization = githubOrganization;
            return this;
        }

        public Builder githubOrganization(ApplicationPolicyRequireGithubOrganizationArgs githubOrganization) {
            return githubOrganization(Output.of(githubOrganization));
        }

        public Builder group(@Nullable Output<ApplicationPolicyRequireGroupArgs> group) {
            $.group = group;
            return this;
        }

        public Builder group(ApplicationPolicyRequireGroupArgs group) {
            return group(Output.of(group));
        }

        public Builder gsuite(@Nullable Output<ApplicationPolicyRequireGsuiteArgs> gsuite) {
            $.gsuite = gsuite;
            return this;
        }

        public Builder gsuite(ApplicationPolicyRequireGsuiteArgs gsuite) {
            return gsuite(Output.of(gsuite));
        }

        public Builder ip(@Nullable Output<ApplicationPolicyRequireIpArgs> ip) {
            $.ip = ip;
            return this;
        }

        public Builder ip(ApplicationPolicyRequireIpArgs ip) {
            return ip(Output.of(ip));
        }

        public Builder ipList(@Nullable Output<ApplicationPolicyRequireIpListArgs> ipList) {
            $.ipList = ipList;
            return this;
        }

        public Builder ipList(ApplicationPolicyRequireIpListArgs ipList) {
            return ipList(Output.of(ipList));
        }

        public Builder linkedAppToken(@Nullable Output<ApplicationPolicyRequireLinkedAppTokenArgs> linkedAppToken) {
            $.linkedAppToken = linkedAppToken;
            return this;
        }

        public Builder linkedAppToken(ApplicationPolicyRequireLinkedAppTokenArgs linkedAppToken) {
            return linkedAppToken(Output.of(linkedAppToken));
        }

        public Builder loginMethod(@Nullable Output<ApplicationPolicyRequireLoginMethodArgs> loginMethod) {
            $.loginMethod = loginMethod;
            return this;
        }

        public Builder loginMethod(ApplicationPolicyRequireLoginMethodArgs loginMethod) {
            return loginMethod(Output.of(loginMethod));
        }

        public Builder oidc(@Nullable Output<ApplicationPolicyRequireOidcArgs> oidc) {
            $.oidc = oidc;
            return this;
        }

        public Builder oidc(ApplicationPolicyRequireOidcArgs oidc) {
            return oidc(Output.of(oidc));
        }

        public Builder okta(@Nullable Output<ApplicationPolicyRequireOktaArgs> okta) {
            $.okta = okta;
            return this;
        }

        public Builder okta(ApplicationPolicyRequireOktaArgs okta) {
            return okta(Output.of(okta));
        }

        public Builder saml(@Nullable Output<ApplicationPolicyRequireSamlArgs> saml) {
            $.saml = saml;
            return this;
        }

        public Builder saml(ApplicationPolicyRequireSamlArgs saml) {
            return saml(Output.of(saml));
        }

        public Builder serviceToken(@Nullable Output<ApplicationPolicyRequireServiceTokenArgs> serviceToken) {
            $.serviceToken = serviceToken;
            return this;
        }

        public Builder serviceToken(ApplicationPolicyRequireServiceTokenArgs serviceToken) {
            return serviceToken(Output.of(serviceToken));
        }

        public ApplicationPolicyRequireArgs build() {
            return $;
        }
    }

}
