// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudflare.zeroTrustAccess.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class PolicyRequireGeoArgs extends com.pulumi.resources.ResourceArgs {

    public static final PolicyRequireGeoArgs Empty = new PolicyRequireGeoArgs();

    /**
     * The country code that should be matched.
     * 
     */
    @Import(name="countryCode", required=true)
    private Output<String> countryCode;

    /**
     * @return The country code that should be matched.
     * 
     */
    public Output<String> countryCode() {
        return this.countryCode;
    }

    private PolicyRequireGeoArgs() {}

    private PolicyRequireGeoArgs(PolicyRequireGeoArgs $) {
        this.countryCode = $.countryCode;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PolicyRequireGeoArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PolicyRequireGeoArgs $;

        public Builder() {
            $ = new PolicyRequireGeoArgs();
        }

        public Builder(PolicyRequireGeoArgs defaults) {
            $ = new PolicyRequireGeoArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param countryCode The country code that should be matched.
         * 
         * @return builder
         * 
         */
        public Builder countryCode(Output<String> countryCode) {
            $.countryCode = countryCode;
            return this;
        }

        /**
         * @param countryCode The country code that should be matched.
         * 
         * @return builder
         * 
         */
        public Builder countryCode(String countryCode) {
            return countryCode(Output.of(countryCode));
        }

        public PolicyRequireGeoArgs build() {
            if ($.countryCode == null) {
                throw new MissingRequiredPropertyException("PolicyRequireGeoArgs", "countryCode");
            }
            return $;
        }
    }

}
