// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudflare.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class AccessApplicationPolicyRequireLinkedAppTokenArgs extends com.pulumi.resources.ResourceArgs {

    public static final AccessApplicationPolicyRequireLinkedAppTokenArgs Empty = new AccessApplicationPolicyRequireLinkedAppTokenArgs();

    /**
     * The ID of an Access OIDC SaaS application
     * 
     */
    @Import(name="appUid", required=true)
    private Output<String> appUid;

    /**
     * @return The ID of an Access OIDC SaaS application
     * 
     */
    public Output<String> appUid() {
        return this.appUid;
    }

    private AccessApplicationPolicyRequireLinkedAppTokenArgs() {}

    private AccessApplicationPolicyRequireLinkedAppTokenArgs(AccessApplicationPolicyRequireLinkedAppTokenArgs $) {
        this.appUid = $.appUid;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(AccessApplicationPolicyRequireLinkedAppTokenArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private AccessApplicationPolicyRequireLinkedAppTokenArgs $;

        public Builder() {
            $ = new AccessApplicationPolicyRequireLinkedAppTokenArgs();
        }

        public Builder(AccessApplicationPolicyRequireLinkedAppTokenArgs defaults) {
            $ = new AccessApplicationPolicyRequireLinkedAppTokenArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param appUid The ID of an Access OIDC SaaS application
         * 
         * @return builder
         * 
         */
        public Builder appUid(Output<String> appUid) {
            $.appUid = appUid;
            return this;
        }

        /**
         * @param appUid The ID of an Access OIDC SaaS application
         * 
         * @return builder
         * 
         */
        public Builder appUid(String appUid) {
            return appUid(Output.of(appUid));
        }

        public AccessApplicationPolicyRequireLinkedAppTokenArgs build() {
            if ($.appUid == null) {
                throw new MissingRequiredPropertyException("AccessApplicationPolicyRequireLinkedAppTokenArgs", "appUid");
            }
            return $;
        }
    }

}
