// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudflare.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class AiGatewaySpendLimitsRuleMetadataArgs extends com.pulumi.resources.ResourceArgs {

    public static final AiGatewaySpendLimitsRuleMetadataArgs Empty = new AiGatewaySpendLimitsRuleMetadataArgs();

    /**
     * Available values: &#34;partition&#34;, &#34;filter&#34;.
     * 
     */
    @Import(name="mode", required=true)
    private Output<String> mode;

    /**
     * @return Available values: &#34;partition&#34;, &#34;filter&#34;.
     * 
     */
    public Output<String> mode() {
        return this.mode;
    }

    @Import(name="values")
    private @Nullable Output<List<String>> values;

    public Optional<Output<List<String>>> values() {
        return Optional.ofNullable(this.values);
    }

    private AiGatewaySpendLimitsRuleMetadataArgs() {}

    private AiGatewaySpendLimitsRuleMetadataArgs(AiGatewaySpendLimitsRuleMetadataArgs $) {
        this.mode = $.mode;
        this.values = $.values;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(AiGatewaySpendLimitsRuleMetadataArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private AiGatewaySpendLimitsRuleMetadataArgs $;

        public Builder() {
            $ = new AiGatewaySpendLimitsRuleMetadataArgs();
        }

        public Builder(AiGatewaySpendLimitsRuleMetadataArgs defaults) {
            $ = new AiGatewaySpendLimitsRuleMetadataArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param mode Available values: &#34;partition&#34;, &#34;filter&#34;.
         * 
         * @return builder
         * 
         */
        public Builder mode(Output<String> mode) {
            $.mode = mode;
            return this;
        }

        /**
         * @param mode Available values: &#34;partition&#34;, &#34;filter&#34;.
         * 
         * @return builder
         * 
         */
        public Builder mode(String mode) {
            return mode(Output.of(mode));
        }

        public Builder values(@Nullable Output<List<String>> values) {
            $.values = values;
            return this;
        }

        public Builder values(List<String> values) {
            return values(Output.of(values));
        }

        public Builder values(String... values) {
            return values(List.of(values));
        }

        public AiGatewaySpendLimitsRuleMetadataArgs build() {
            if ($.mode == null) {
                throw new MissingRequiredPropertyException("AiGatewaySpendLimitsRuleMetadataArgs", "mode");
            }
            return $;
        }
    }

}
