// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudflare.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetRulesetPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetRulesetPlainArgs Empty = new GetRulesetPlainArgs();

    /**
     * The unique ID of the account.
     * 
     */
    @Import(name="accountId")
    private @Nullable String accountId;

    /**
     * @return The unique ID of the account.
     * 
     */
    public Optional<String> accountId() {
        return Optional.ofNullable(this.accountId);
    }

    /**
     * The unique ID of the ruleset.
     * 
     */
    @Import(name="id")
    private @Nullable String id;

    /**
     * @return The unique ID of the ruleset.
     * 
     */
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }

    /**
     * The unique ID of the ruleset.
     * 
     * @deprecated
     * Configure id instead. This attribute will be removed in the next major version of the provider.
     * 
     */
    @Deprecated /* Configure id instead. This attribute will be removed in the next major version of the provider. */
    @Import(name="rulesetId")
    private @Nullable String rulesetId;

    /**
     * @return The unique ID of the ruleset.
     * 
     * @deprecated
     * Configure id instead. This attribute will be removed in the next major version of the provider.
     * 
     */
    @Deprecated /* Configure id instead. This attribute will be removed in the next major version of the provider. */
    public Optional<String> rulesetId() {
        return Optional.ofNullable(this.rulesetId);
    }

    /**
     * The unique ID of the zone.
     * 
     */
    @Import(name="zoneId")
    private @Nullable String zoneId;

    /**
     * @return The unique ID of the zone.
     * 
     */
    public Optional<String> zoneId() {
        return Optional.ofNullable(this.zoneId);
    }

    private GetRulesetPlainArgs() {}

    private GetRulesetPlainArgs(GetRulesetPlainArgs $) {
        this.accountId = $.accountId;
        this.id = $.id;
        this.rulesetId = $.rulesetId;
        this.zoneId = $.zoneId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetRulesetPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetRulesetPlainArgs $;

        public Builder() {
            $ = new GetRulesetPlainArgs();
        }

        public Builder(GetRulesetPlainArgs defaults) {
            $ = new GetRulesetPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param accountId The unique ID of the account.
         * 
         * @return builder
         * 
         */
        public Builder accountId(@Nullable String accountId) {
            $.accountId = accountId;
            return this;
        }

        /**
         * @param id The unique ID of the ruleset.
         * 
         * @return builder
         * 
         */
        public Builder id(@Nullable String id) {
            $.id = id;
            return this;
        }

        /**
         * @param rulesetId The unique ID of the ruleset.
         * 
         * @return builder
         * 
         * @deprecated
         * Configure id instead. This attribute will be removed in the next major version of the provider.
         * 
         */
        @Deprecated /* Configure id instead. This attribute will be removed in the next major version of the provider. */
        public Builder rulesetId(@Nullable String rulesetId) {
            $.rulesetId = rulesetId;
            return this;
        }

        /**
         * @param zoneId The unique ID of the zone.
         * 
         * @return builder
         * 
         */
        public Builder zoneId(@Nullable String zoneId) {
            $.zoneId = zoneId;
            return this;
        }

        public GetRulesetPlainArgs build() {
            return $;
        }
    }

}
