// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudflare.inputs;

import com.pulumi.cloudflare.inputs.GetSecretsStoreSecretFilter;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetSecretsStoreSecretPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetSecretsStoreSecretPlainArgs Empty = new GetSecretsStoreSecretPlainArgs();

    /**
     * Account Identifier
     * 
     */
    @Import(name="accountId", required=true)
    private String accountId;

    /**
     * @return Account Identifier
     * 
     */
    public String accountId() {
        return this.accountId;
    }

    @Import(name="filter")
    private @Nullable GetSecretsStoreSecretFilter filter;

    public Optional<GetSecretsStoreSecretFilter> filter() {
        return Optional.ofNullable(this.filter);
    }

    /**
     * Secret identifier tag.
     * 
     */
    @Import(name="secretId")
    private @Nullable String secretId;

    /**
     * @return Secret identifier tag.
     * 
     */
    public Optional<String> secretId() {
        return Optional.ofNullable(this.secretId);
    }

    /**
     * Store Identifier
     * 
     */
    @Import(name="storeId", required=true)
    private String storeId;

    /**
     * @return Store Identifier
     * 
     */
    public String storeId() {
        return this.storeId;
    }

    private GetSecretsStoreSecretPlainArgs() {}

    private GetSecretsStoreSecretPlainArgs(GetSecretsStoreSecretPlainArgs $) {
        this.accountId = $.accountId;
        this.filter = $.filter;
        this.secretId = $.secretId;
        this.storeId = $.storeId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetSecretsStoreSecretPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetSecretsStoreSecretPlainArgs $;

        public Builder() {
            $ = new GetSecretsStoreSecretPlainArgs();
        }

        public Builder(GetSecretsStoreSecretPlainArgs defaults) {
            $ = new GetSecretsStoreSecretPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param accountId Account Identifier
         * 
         * @return builder
         * 
         */
        public Builder accountId(String accountId) {
            $.accountId = accountId;
            return this;
        }

        public Builder filter(@Nullable GetSecretsStoreSecretFilter filter) {
            $.filter = filter;
            return this;
        }

        /**
         * @param secretId Secret identifier tag.
         * 
         * @return builder
         * 
         */
        public Builder secretId(@Nullable String secretId) {
            $.secretId = secretId;
            return this;
        }

        /**
         * @param storeId Store Identifier
         * 
         * @return builder
         * 
         */
        public Builder storeId(String storeId) {
            $.storeId = storeId;
            return this;
        }

        public GetSecretsStoreSecretPlainArgs build() {
            if ($.accountId == null) {
                throw new MissingRequiredPropertyException("GetSecretsStoreSecretPlainArgs", "accountId");
            }
            if ($.storeId == null) {
                throw new MissingRequiredPropertyException("GetSecretsStoreSecretPlainArgs", "storeId");
            }
            return $;
        }
    }

}
