// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudflare.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Double;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class MagicTransitCf1SiteBodyLocationArgs extends com.pulumi.resources.ResourceArgs {

    public static final MagicTransitCf1SiteBodyLocationArgs Empty = new MagicTransitCf1SiteBodyLocationArgs();

    /**
     * Latitude of the CF1 Site.
     * 
     */
    @Import(name="lat")
    private @Nullable Output<Double> lat;

    /**
     * @return Latitude of the CF1 Site.
     * 
     */
    public Optional<Output<Double>> lat() {
        return Optional.ofNullable(this.lat);
    }

    /**
     * Longitude of the CF1 Site.
     * 
     */
    @Import(name="long")
    private @Nullable Output<Double> long_;

    /**
     * @return Longitude of the CF1 Site.
     * 
     */
    public Optional<Output<Double>> long_() {
        return Optional.ofNullable(this.long_);
    }

    /**
     * Name of nearest town, city, or village.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return Name of nearest town, city, or village.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    private MagicTransitCf1SiteBodyLocationArgs() {}

    private MagicTransitCf1SiteBodyLocationArgs(MagicTransitCf1SiteBodyLocationArgs $) {
        this.lat = $.lat;
        this.long_ = $.long_;
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(MagicTransitCf1SiteBodyLocationArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private MagicTransitCf1SiteBodyLocationArgs $;

        public Builder() {
            $ = new MagicTransitCf1SiteBodyLocationArgs();
        }

        public Builder(MagicTransitCf1SiteBodyLocationArgs defaults) {
            $ = new MagicTransitCf1SiteBodyLocationArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param lat Latitude of the CF1 Site.
         * 
         * @return builder
         * 
         */
        public Builder lat(@Nullable Output<Double> lat) {
            $.lat = lat;
            return this;
        }

        /**
         * @param lat Latitude of the CF1 Site.
         * 
         * @return builder
         * 
         */
        public Builder lat(Double lat) {
            return lat(Output.of(lat));
        }

        /**
         * @param long_ Longitude of the CF1 Site.
         * 
         * @return builder
         * 
         */
        public Builder long_(@Nullable Output<Double> long_) {
            $.long_ = long_;
            return this;
        }

        /**
         * @param long_ Longitude of the CF1 Site.
         * 
         * @return builder
         * 
         */
        public Builder long_(Double long_) {
            return long_(Output.of(long_));
        }

        /**
         * @param name Name of nearest town, city, or village.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Name of nearest town, city, or village.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        public MagicTransitCf1SiteBodyLocationArgs build() {
            return $;
        }
    }

}
