// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudflare.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SnippetRulesRuleArgs extends com.pulumi.resources.ResourceArgs {

    public static final SnippetRulesRuleArgs Empty = new SnippetRulesRuleArgs();

    /**
     * Brief summary of the snippet rule and its intended use.
     * 
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return Brief summary of the snippet rule and its intended use.
     * 
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * Whether the headers rule is active.
     * 
     */
    @Import(name="enabled")
    private @Nullable Output<Boolean> enabled;

    /**
     * @return Whether the headers rule is active.
     * 
     */
    public Optional<Output<Boolean>> enabled() {
        return Optional.ofNullable(this.enabled);
    }

    /**
     * Criteria for an HTTP request to trigger the snippet rule. Uses the Firewall Rules expression language based on Wireshark display filters.
     * 
     */
    @Import(name="expression", required=true)
    private Output<String> expression;

    /**
     * @return Criteria for an HTTP request to trigger the snippet rule. Uses the Firewall Rules expression language based on Wireshark display filters.
     * 
     */
    public Output<String> expression() {
        return this.expression;
    }

    /**
     * Name of the snippet invoked by this rule.
     * 
     */
    @Import(name="snippetName", required=true)
    private Output<String> snippetName;

    /**
     * @return Name of the snippet invoked by this rule.
     * 
     */
    public Output<String> snippetName() {
        return this.snippetName;
    }

    private SnippetRulesRuleArgs() {}

    private SnippetRulesRuleArgs(SnippetRulesRuleArgs $) {
        this.description = $.description;
        this.enabled = $.enabled;
        this.expression = $.expression;
        this.snippetName = $.snippetName;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SnippetRulesRuleArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SnippetRulesRuleArgs $;

        public Builder() {
            $ = new SnippetRulesRuleArgs();
        }

        public Builder(SnippetRulesRuleArgs defaults) {
            $ = new SnippetRulesRuleArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param description Brief summary of the snippet rule and its intended use.
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description Brief summary of the snippet rule and its intended use.
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param enabled Whether the headers rule is active.
         * 
         * @return builder
         * 
         */
        public Builder enabled(@Nullable Output<Boolean> enabled) {
            $.enabled = enabled;
            return this;
        }

        /**
         * @param enabled Whether the headers rule is active.
         * 
         * @return builder
         * 
         */
        public Builder enabled(Boolean enabled) {
            return enabled(Output.of(enabled));
        }

        /**
         * @param expression Criteria for an HTTP request to trigger the snippet rule. Uses the Firewall Rules expression language based on Wireshark display filters.
         * 
         * @return builder
         * 
         */
        public Builder expression(Output<String> expression) {
            $.expression = expression;
            return this;
        }

        /**
         * @param expression Criteria for an HTTP request to trigger the snippet rule. Uses the Firewall Rules expression language based on Wireshark display filters.
         * 
         * @return builder
         * 
         */
        public Builder expression(String expression) {
            return expression(Output.of(expression));
        }

        /**
         * @param snippetName Name of the snippet invoked by this rule.
         * 
         * @return builder
         * 
         */
        public Builder snippetName(Output<String> snippetName) {
            $.snippetName = snippetName;
            return this;
        }

        /**
         * @param snippetName Name of the snippet invoked by this rule.
         * 
         * @return builder
         * 
         */
        public Builder snippetName(String snippetName) {
            return snippetName(Output.of(snippetName));
        }

        public SnippetRulesRuleArgs build() {
            if ($.expression == null) {
                throw new MissingRequiredPropertyException("SnippetRulesRuleArgs", "expression");
            }
            if ($.snippetName == null) {
                throw new MissingRequiredPropertyException("SnippetRulesRuleArgs", "snippetName");
            }
            return $;
        }
    }

}
