// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudflare.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ZeroTrustGatewaySettingsSettingsInspectionArgs extends com.pulumi.resources.ResourceArgs {

    public static final ZeroTrustGatewaySettingsSettingsInspectionArgs Empty = new ZeroTrustGatewaySettingsSettingsInspectionArgs();

    /**
     * Defines the mode of inspection the proxy will use.
     * - static: Gateway will use static inspection to inspect HTTP on TCP(80). If TLS decryption is on, Gateway will inspect HTTPS traffic on TCP(443) &amp; UDP(443).
     * - dynamic: Gateway will use protocol detection to dynamically inspect HTTP and HTTPS traffic on any port. TLS decryption must be on to inspect HTTPS traffic.
     *   Available values: &#34;static&#34;, &#34;dynamic&#34;.
     * 
     */
    @Import(name="mode")
    private @Nullable Output<String> mode;

    /**
     * @return Defines the mode of inspection the proxy will use.
     * - static: Gateway will use static inspection to inspect HTTP on TCP(80). If TLS decryption is on, Gateway will inspect HTTPS traffic on TCP(443) &amp; UDP(443).
     * - dynamic: Gateway will use protocol detection to dynamically inspect HTTP and HTTPS traffic on any port. TLS decryption must be on to inspect HTTPS traffic.
     *   Available values: &#34;static&#34;, &#34;dynamic&#34;.
     * 
     */
    public Optional<Output<String>> mode() {
        return Optional.ofNullable(this.mode);
    }

    private ZeroTrustGatewaySettingsSettingsInspectionArgs() {}

    private ZeroTrustGatewaySettingsSettingsInspectionArgs(ZeroTrustGatewaySettingsSettingsInspectionArgs $) {
        this.mode = $.mode;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ZeroTrustGatewaySettingsSettingsInspectionArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ZeroTrustGatewaySettingsSettingsInspectionArgs $;

        public Builder() {
            $ = new ZeroTrustGatewaySettingsSettingsInspectionArgs();
        }

        public Builder(ZeroTrustGatewaySettingsSettingsInspectionArgs defaults) {
            $ = new ZeroTrustGatewaySettingsSettingsInspectionArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param mode Defines the mode of inspection the proxy will use.
         * - static: Gateway will use static inspection to inspect HTTP on TCP(80). If TLS decryption is on, Gateway will inspect HTTPS traffic on TCP(443) &amp; UDP(443).
         * - dynamic: Gateway will use protocol detection to dynamically inspect HTTP and HTTPS traffic on any port. TLS decryption must be on to inspect HTTPS traffic.
         *   Available values: &#34;static&#34;, &#34;dynamic&#34;.
         * 
         * @return builder
         * 
         */
        public Builder mode(@Nullable Output<String> mode) {
            $.mode = mode;
            return this;
        }

        /**
         * @param mode Defines the mode of inspection the proxy will use.
         * - static: Gateway will use static inspection to inspect HTTP on TCP(80). If TLS decryption is on, Gateway will inspect HTTPS traffic on TCP(443) &amp; UDP(443).
         * - dynamic: Gateway will use protocol detection to dynamically inspect HTTP and HTTPS traffic on any port. TLS decryption must be on to inspect HTTPS traffic.
         *   Available values: &#34;static&#34;, &#34;dynamic&#34;.
         * 
         * @return builder
         * 
         */
        public Builder mode(String mode) {
            return mode(Output.of(mode));
        }

        public ZeroTrustGatewaySettingsSettingsInspectionArgs build() {
            return $;
        }
    }

}
