// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudflare.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ZeroTrustGatewaySettingsSettingsBrowserIsolationArgs extends com.pulumi.resources.ResourceArgs {

    public static final ZeroTrustGatewaySettingsSettingsBrowserIsolationArgs Empty = new ZeroTrustGatewaySettingsSettingsBrowserIsolationArgs();

    /**
     * Enable non-identity onramp support for Browser Isolation.
     * 
     */
    @Import(name="nonIdentityEnabled")
    private @Nullable Output<Boolean> nonIdentityEnabled;

    /**
     * @return Enable non-identity onramp support for Browser Isolation.
     * 
     */
    public Optional<Output<Boolean>> nonIdentityEnabled() {
        return Optional.ofNullable(this.nonIdentityEnabled);
    }

    /**
     * Enable Clientless Browser Isolation.
     * 
     */
    @Import(name="urlBrowserIsolationEnabled")
    private @Nullable Output<Boolean> urlBrowserIsolationEnabled;

    /**
     * @return Enable Clientless Browser Isolation.
     * 
     */
    public Optional<Output<Boolean>> urlBrowserIsolationEnabled() {
        return Optional.ofNullable(this.urlBrowserIsolationEnabled);
    }

    private ZeroTrustGatewaySettingsSettingsBrowserIsolationArgs() {}

    private ZeroTrustGatewaySettingsSettingsBrowserIsolationArgs(ZeroTrustGatewaySettingsSettingsBrowserIsolationArgs $) {
        this.nonIdentityEnabled = $.nonIdentityEnabled;
        this.urlBrowserIsolationEnabled = $.urlBrowserIsolationEnabled;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ZeroTrustGatewaySettingsSettingsBrowserIsolationArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ZeroTrustGatewaySettingsSettingsBrowserIsolationArgs $;

        public Builder() {
            $ = new ZeroTrustGatewaySettingsSettingsBrowserIsolationArgs();
        }

        public Builder(ZeroTrustGatewaySettingsSettingsBrowserIsolationArgs defaults) {
            $ = new ZeroTrustGatewaySettingsSettingsBrowserIsolationArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param nonIdentityEnabled Enable non-identity onramp support for Browser Isolation.
         * 
         * @return builder
         * 
         */
        public Builder nonIdentityEnabled(@Nullable Output<Boolean> nonIdentityEnabled) {
            $.nonIdentityEnabled = nonIdentityEnabled;
            return this;
        }

        /**
         * @param nonIdentityEnabled Enable non-identity onramp support for Browser Isolation.
         * 
         * @return builder
         * 
         */
        public Builder nonIdentityEnabled(Boolean nonIdentityEnabled) {
            return nonIdentityEnabled(Output.of(nonIdentityEnabled));
        }

        /**
         * @param urlBrowserIsolationEnabled Enable Clientless Browser Isolation.
         * 
         * @return builder
         * 
         */
        public Builder urlBrowserIsolationEnabled(@Nullable Output<Boolean> urlBrowserIsolationEnabled) {
            $.urlBrowserIsolationEnabled = urlBrowserIsolationEnabled;
            return this;
        }

        /**
         * @param urlBrowserIsolationEnabled Enable Clientless Browser Isolation.
         * 
         * @return builder
         * 
         */
        public Builder urlBrowserIsolationEnabled(Boolean urlBrowserIsolationEnabled) {
            return urlBrowserIsolationEnabled(Output.of(urlBrowserIsolationEnabled));
        }

        public ZeroTrustGatewaySettingsSettingsBrowserIsolationArgs build() {
            return $;
        }
    }

}
