// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudflare.outputs;

import com.pulumi.cloudflare.outputs.AccessApplicationScimConfigMappingOperations;
import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class AccessApplicationScimConfigMapping {
    /**
     * @return Whether or not this mapping is enabled.
     * 
     */
    private @Nullable Boolean enabled;
    /**
     * @return A [SCIM filter expression](https://datatracker.ietf.org/doc/html/rfc7644#section-3.4.2.2) that matches resources that should be provisioned to this application.
     * 
     */
    private @Nullable String filter;
    /**
     * @return Whether or not this mapping applies to creates, updates, or deletes.
     * 
     */
    private @Nullable AccessApplicationScimConfigMappingOperations operations;
    /**
     * @return Which SCIM resource type this mapping applies to.
     * 
     */
    private String schema;
    /**
     * @return How strictly to adhere to outbound resource schemas when provisioning to this mapping. &#34;strict&#34; will remove unknown values when provisioning, while &#34;passthrough&#34; will pass unknown values to the target.
     * 
     */
    private @Nullable String strictness;
    /**
     * @return A [JSONata](https://jsonata.org/) expression that transforms the resource before provisioning it in the application.
     * 
     */
    private @Nullable String transformJsonata;

    private AccessApplicationScimConfigMapping() {}
    /**
     * @return Whether or not this mapping is enabled.
     * 
     */
    public Optional<Boolean> enabled() {
        return Optional.ofNullable(this.enabled);
    }
    /**
     * @return A [SCIM filter expression](https://datatracker.ietf.org/doc/html/rfc7644#section-3.4.2.2) that matches resources that should be provisioned to this application.
     * 
     */
    public Optional<String> filter() {
        return Optional.ofNullable(this.filter);
    }
    /**
     * @return Whether or not this mapping applies to creates, updates, or deletes.
     * 
     */
    public Optional<AccessApplicationScimConfigMappingOperations> operations() {
        return Optional.ofNullable(this.operations);
    }
    /**
     * @return Which SCIM resource type this mapping applies to.
     * 
     */
    public String schema() {
        return this.schema;
    }
    /**
     * @return How strictly to adhere to outbound resource schemas when provisioning to this mapping. &#34;strict&#34; will remove unknown values when provisioning, while &#34;passthrough&#34; will pass unknown values to the target.
     * 
     */
    public Optional<String> strictness() {
        return Optional.ofNullable(this.strictness);
    }
    /**
     * @return A [JSONata](https://jsonata.org/) expression that transforms the resource before provisioning it in the application.
     * 
     */
    public Optional<String> transformJsonata() {
        return Optional.ofNullable(this.transformJsonata);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(AccessApplicationScimConfigMapping defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Boolean enabled;
        private @Nullable String filter;
        private @Nullable AccessApplicationScimConfigMappingOperations operations;
        private String schema;
        private @Nullable String strictness;
        private @Nullable String transformJsonata;
        public Builder() {}
        public Builder(AccessApplicationScimConfigMapping defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.enabled = defaults.enabled;
    	      this.filter = defaults.filter;
    	      this.operations = defaults.operations;
    	      this.schema = defaults.schema;
    	      this.strictness = defaults.strictness;
    	      this.transformJsonata = defaults.transformJsonata;
        }

        @CustomType.Setter
        public Builder enabled(@Nullable Boolean enabled) {

            this.enabled = enabled;
            return this;
        }
        @CustomType.Setter
        public Builder filter(@Nullable String filter) {

            this.filter = filter;
            return this;
        }
        @CustomType.Setter
        public Builder operations(@Nullable AccessApplicationScimConfigMappingOperations operations) {

            this.operations = operations;
            return this;
        }
        @CustomType.Setter
        public Builder schema(String schema) {
            if (schema == null) {
              throw new MissingRequiredPropertyException("AccessApplicationScimConfigMapping", "schema");
            }
            this.schema = schema;
            return this;
        }
        @CustomType.Setter
        public Builder strictness(@Nullable String strictness) {

            this.strictness = strictness;
            return this;
        }
        @CustomType.Setter
        public Builder transformJsonata(@Nullable String transformJsonata) {

            this.transformJsonata = transformJsonata;
            return this;
        }
        public AccessApplicationScimConfigMapping build() {
            final var _resultValue = new AccessApplicationScimConfigMapping();
            _resultValue.enabled = enabled;
            _resultValue.filter = filter;
            _resultValue.operations = operations;
            _resultValue.schema = schema;
            _resultValue.strictness = strictness;
            _resultValue.transformJsonata = transformJsonata;
            return _resultValue;
        }
    }
}
