// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudflare.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Double;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class EmailRoutingDnsResultErrorMissing {
    /**
     * @return DNS record content.
     * 
     */
    private @Nullable String content;
    /**
     * @return DNS record name (or {@literal @} for the zone apex).
     * 
     */
    private @Nullable String name;
    /**
     * @return Required for MX, SRV and URI records. Unused by other record types. Records with lower priorities are preferred.
     * 
     */
    private @Nullable Double priority;
    /**
     * @return Time to live, in seconds, of the DNS record. Must be between 60 and 86400, or 1 for &#39;automatic&#39;.
     * 
     */
    private @Nullable Double ttl;
    /**
     * @return DNS record type.
     * 
     */
    private @Nullable String type;

    private EmailRoutingDnsResultErrorMissing() {}
    /**
     * @return DNS record content.
     * 
     */
    public Optional<String> content() {
        return Optional.ofNullable(this.content);
    }
    /**
     * @return DNS record name (or {@literal @} for the zone apex).
     * 
     */
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }
    /**
     * @return Required for MX, SRV and URI records. Unused by other record types. Records with lower priorities are preferred.
     * 
     */
    public Optional<Double> priority() {
        return Optional.ofNullable(this.priority);
    }
    /**
     * @return Time to live, in seconds, of the DNS record. Must be between 60 and 86400, or 1 for &#39;automatic&#39;.
     * 
     */
    public Optional<Double> ttl() {
        return Optional.ofNullable(this.ttl);
    }
    /**
     * @return DNS record type.
     * 
     */
    public Optional<String> type() {
        return Optional.ofNullable(this.type);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(EmailRoutingDnsResultErrorMissing defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String content;
        private @Nullable String name;
        private @Nullable Double priority;
        private @Nullable Double ttl;
        private @Nullable String type;
        public Builder() {}
        public Builder(EmailRoutingDnsResultErrorMissing defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.content = defaults.content;
    	      this.name = defaults.name;
    	      this.priority = defaults.priority;
    	      this.ttl = defaults.ttl;
    	      this.type = defaults.type;
        }

        @CustomType.Setter
        public Builder content(@Nullable String content) {

            this.content = content;
            return this;
        }
        @CustomType.Setter
        public Builder name(@Nullable String name) {

            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder priority(@Nullable Double priority) {

            this.priority = priority;
            return this;
        }
        @CustomType.Setter
        public Builder ttl(@Nullable Double ttl) {

            this.ttl = ttl;
            return this;
        }
        @CustomType.Setter
        public Builder type(@Nullable String type) {

            this.type = type;
            return this;
        }
        public EmailRoutingDnsResultErrorMissing build() {
            final var _resultValue = new EmailRoutingDnsResultErrorMissing();
            _resultValue.content = content;
            _resultValue.name = name;
            _resultValue.priority = priority;
            _resultValue.ttl = ttl;
            _resultValue.type = type;
            return _resultValue;
        }
    }
}
