// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudflare.outputs;

import com.pulumi.cloudflare.outputs.GetAiGatewaysResultSpendLimitsRuleAiGatewayProvider;
import com.pulumi.cloudflare.outputs.GetAiGatewaysResultSpendLimitsRuleMetadata;
import com.pulumi.cloudflare.outputs.GetAiGatewaysResultSpendLimitsRuleModel;
import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.Integer;
import java.lang.String;
import java.util.Map;
import java.util.Objects;

@CustomType
public final class GetAiGatewaysResultSpendLimitsRule {
    private GetAiGatewaysResultSpendLimitsRuleAiGatewayProvider aiGatewayProvider;
    private Boolean enabled;
    private String id;
    private Double limit;
    /**
     * @return Available values: &#34;cost&#34;.
     * 
     */
    private String limitType;
    private Map<String,GetAiGatewaysResultSpendLimitsRuleMetadata> metadata;
    private GetAiGatewaysResultSpendLimitsRuleModel model;
    /**
     * @return Available values: &#34;fixed&#34;, &#34;sliding&#34;.
     * 
     */
    private String technique;
    private Integer window;

    private GetAiGatewaysResultSpendLimitsRule() {}
    public GetAiGatewaysResultSpendLimitsRuleAiGatewayProvider aiGatewayProvider() {
        return this.aiGatewayProvider;
    }
    public Boolean enabled() {
        return this.enabled;
    }
    public String id() {
        return this.id;
    }
    public Double limit() {
        return this.limit;
    }
    /**
     * @return Available values: &#34;cost&#34;.
     * 
     */
    public String limitType() {
        return this.limitType;
    }
    public Map<String,GetAiGatewaysResultSpendLimitsRuleMetadata> metadata() {
        return this.metadata;
    }
    public GetAiGatewaysResultSpendLimitsRuleModel model() {
        return this.model;
    }
    /**
     * @return Available values: &#34;fixed&#34;, &#34;sliding&#34;.
     * 
     */
    public String technique() {
        return this.technique;
    }
    public Integer window() {
        return this.window;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetAiGatewaysResultSpendLimitsRule defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private GetAiGatewaysResultSpendLimitsRuleAiGatewayProvider aiGatewayProvider;
        private Boolean enabled;
        private String id;
        private Double limit;
        private String limitType;
        private Map<String,GetAiGatewaysResultSpendLimitsRuleMetadata> metadata;
        private GetAiGatewaysResultSpendLimitsRuleModel model;
        private String technique;
        private Integer window;
        public Builder() {}
        public Builder(GetAiGatewaysResultSpendLimitsRule defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.aiGatewayProvider = defaults.aiGatewayProvider;
    	      this.enabled = defaults.enabled;
    	      this.id = defaults.id;
    	      this.limit = defaults.limit;
    	      this.limitType = defaults.limitType;
    	      this.metadata = defaults.metadata;
    	      this.model = defaults.model;
    	      this.technique = defaults.technique;
    	      this.window = defaults.window;
        }

        @CustomType.Setter
        public Builder aiGatewayProvider(GetAiGatewaysResultSpendLimitsRuleAiGatewayProvider aiGatewayProvider) {
            if (aiGatewayProvider == null) {
              throw new MissingRequiredPropertyException("GetAiGatewaysResultSpendLimitsRule", "aiGatewayProvider");
            }
            this.aiGatewayProvider = aiGatewayProvider;
            return this;
        }
        @CustomType.Setter
        public Builder enabled(Boolean enabled) {
            if (enabled == null) {
              throw new MissingRequiredPropertyException("GetAiGatewaysResultSpendLimitsRule", "enabled");
            }
            this.enabled = enabled;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetAiGatewaysResultSpendLimitsRule", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder limit(Double limit) {
            if (limit == null) {
              throw new MissingRequiredPropertyException("GetAiGatewaysResultSpendLimitsRule", "limit");
            }
            this.limit = limit;
            return this;
        }
        @CustomType.Setter
        public Builder limitType(String limitType) {
            if (limitType == null) {
              throw new MissingRequiredPropertyException("GetAiGatewaysResultSpendLimitsRule", "limitType");
            }
            this.limitType = limitType;
            return this;
        }
        @CustomType.Setter
        public Builder metadata(Map<String,GetAiGatewaysResultSpendLimitsRuleMetadata> metadata) {
            if (metadata == null) {
              throw new MissingRequiredPropertyException("GetAiGatewaysResultSpendLimitsRule", "metadata");
            }
            this.metadata = metadata;
            return this;
        }
        @CustomType.Setter
        public Builder model(GetAiGatewaysResultSpendLimitsRuleModel model) {
            if (model == null) {
              throw new MissingRequiredPropertyException("GetAiGatewaysResultSpendLimitsRule", "model");
            }
            this.model = model;
            return this;
        }
        @CustomType.Setter
        public Builder technique(String technique) {
            if (technique == null) {
              throw new MissingRequiredPropertyException("GetAiGatewaysResultSpendLimitsRule", "technique");
            }
            this.technique = technique;
            return this;
        }
        @CustomType.Setter
        public Builder window(Integer window) {
            if (window == null) {
              throw new MissingRequiredPropertyException("GetAiGatewaysResultSpendLimitsRule", "window");
            }
            this.window = window;
            return this;
        }
        public GetAiGatewaysResultSpendLimitsRule build() {
            final var _resultValue = new GetAiGatewaysResultSpendLimitsRule();
            _resultValue.aiGatewayProvider = aiGatewayProvider;
            _resultValue.enabled = enabled;
            _resultValue.id = id;
            _resultValue.limit = limit;
            _resultValue.limitType = limitType;
            _resultValue.metadata = metadata;
            _resultValue.model = model;
            _resultValue.technique = technique;
            _resultValue.window = window;
            return _resultValue;
        }
    }
}
