// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudflare.outputs;

import com.pulumi.cloudflare.outputs.GetAiSearchInstancesResultCustomMetadata;
import com.pulumi.cloudflare.outputs.GetAiSearchInstancesResultIndexMethod;
import com.pulumi.cloudflare.outputs.GetAiSearchInstancesResultIndexingOptions;
import com.pulumi.cloudflare.outputs.GetAiSearchInstancesResultMetadata;
import com.pulumi.cloudflare.outputs.GetAiSearchInstancesResultPublicEndpointParams;
import com.pulumi.cloudflare.outputs.GetAiSearchInstancesResultRetrievalOptions;
import com.pulumi.cloudflare.outputs.GetAiSearchInstancesResultSourceParams;
import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetAiSearchInstancesResult {
    private String aiGatewayId;
    /**
     * @return Available values: &#34;{@literal @}cf/meta/llama-3.3-70b-instruct-fp8-fast&#34;, &#34;{@literal @}cf/zai-org/glm-4.7-flash&#34;, &#34;{@literal @}cf/meta/llama-3.1-8b-instruct-fast&#34;, &#34;{@literal @}cf/meta/llama-3.1-8b-instruct-fp8&#34;, &#34;{@literal @}cf/meta/llama-4-scout-17b-16e-instruct&#34;, &#34;{@literal @}cf/qwen/qwen3-30b-a3b-fp8&#34;, &#34;{@literal @}cf/deepseek-ai/deepseek-r1-distill-qwen-32b&#34;, &#34;{@literal @}cf/moonshotai/kimi-k2-instruct&#34;, &#34;{@literal @}cf/google/gemma-3-12b-it&#34;, &#34;{@literal @}cf/google/gemma-4-26b-a4b-it&#34;, &#34;{@literal @}cf/moonshotai/kimi-k2.5&#34;, &#34;anthropic/claude-3-7-sonnet&#34;, &#34;anthropic/claude-sonnet-4&#34;, &#34;anthropic/claude-opus-4&#34;, &#34;anthropic/claude-3-5-haiku&#34;, &#34;cerebras/qwen-3-235b-a22b-instruct&#34;, &#34;cerebras/qwen-3-235b-a22b-thinking&#34;, &#34;cerebras/llama-3.3-70b&#34;, &#34;cerebras/llama-4-maverick-17b-128e-instruct&#34;, &#34;cerebras/llama-4-scout-17b-16e-instruct&#34;, &#34;cerebras/gpt-oss-120b&#34;, &#34;google-ai-studio/gemini-2.5-flash&#34;, &#34;google-ai-studio/gemini-2.5-pro&#34;, &#34;grok/grok-4&#34;, &#34;groq/llama-3.3-70b-versatile&#34;, &#34;groq/llama-3.1-8b-instant&#34;, &#34;openai/gpt-5&#34;, &#34;openai/gpt-5-mini&#34;, &#34;openai/gpt-5-nano&#34;, &#34;&#34;.
     * 
     */
    private String aisearchModel;
    private Boolean cache;
    /**
     * @return Available values: &#34;super*strict*match&#34;, &#34;close*enough&#34;, &#34;flexible*friend&#34;, &#34;anythingGoes&#34;.
     * 
     */
    private String cacheThreshold;
    private Integer chunkOverlap;
    private Integer chunkSize;
    private String createdAt;
    private String createdBy;
    private List<GetAiSearchInstancesResultCustomMetadata> customMetadatas;
    /**
     * @return Available values: &#34;{@literal @}cf/qwen/qwen3-embedding-0.6b&#34;, &#34;{@literal @}cf/baai/bge-m3&#34;, &#34;{@literal @}cf/baai/bge-large-en-v1.5&#34;, &#34;{@literal @}cf/google/embeddinggemma-300m&#34;, &#34;google-ai-studio/gemini-embedding-001&#34;, &#34;google-ai-studio/gemini-embedding-2-preview&#34;, &#34;openai/text-embedding-3-small&#34;, &#34;openai/text-embedding-3-large&#34;, &#34;&#34;.
     * 
     */
    private String embeddingModel;
    private Boolean enable;
    private Double engineVersion;
    /**
     * @return Available values: &#34;max&#34;, &#34;rrf&#34;.
     * 
     */
    private String fusionMethod;
    /**
     * @return Deprecated — use indexMethod instead.
     * 
     * @deprecated
     * This attribute is deprecated.
     * 
     */
    @Deprecated /* This attribute is deprecated. */
    private Boolean hybridSearchEnabled;
    /**
     * @return AI Search instance ID. Lowercase alphanumeric, hyphens, and underscores.
     * 
     */
    private String id;
    /**
     * @return Controls which storage backends are used during indexing. Defaults to vector-only.
     * 
     */
    private GetAiSearchInstancesResultIndexMethod indexMethod;
    private GetAiSearchInstancesResultIndexingOptions indexingOptions;
    private String lastActivity;
    private Integer maxNumResults;
    private GetAiSearchInstancesResultMetadata metadata;
    private String modifiedAt;
    private String modifiedBy;
    private String namespace;
    private Boolean paused;
    private String publicEndpointId;
    private GetAiSearchInstancesResultPublicEndpointParams publicEndpointParams;
    private Boolean reranking;
    /**
     * @return Available values: &#34;{@literal @}cf/baai/bge-reranker-base&#34;, &#34;&#34;.
     * 
     */
    private String rerankingModel;
    private GetAiSearchInstancesResultRetrievalOptions retrievalOptions;
    /**
     * @return Available values: &#34;{@literal @}cf/meta/llama-3.3-70b-instruct-fp8-fast&#34;, &#34;{@literal @}cf/zai-org/glm-4.7-flash&#34;, &#34;{@literal @}cf/meta/llama-3.1-8b-instruct-fast&#34;, &#34;{@literal @}cf/meta/llama-3.1-8b-instruct-fp8&#34;, &#34;{@literal @}cf/meta/llama-4-scout-17b-16e-instruct&#34;, &#34;{@literal @}cf/qwen/qwen3-30b-a3b-fp8&#34;, &#34;{@literal @}cf/deepseek-ai/deepseek-r1-distill-qwen-32b&#34;, &#34;{@literal @}cf/moonshotai/kimi-k2-instruct&#34;, &#34;{@literal @}cf/google/gemma-3-12b-it&#34;, &#34;{@literal @}cf/google/gemma-4-26b-a4b-it&#34;, &#34;{@literal @}cf/moonshotai/kimi-k2.5&#34;, &#34;anthropic/claude-3-7-sonnet&#34;, &#34;anthropic/claude-sonnet-4&#34;, &#34;anthropic/claude-opus-4&#34;, &#34;anthropic/claude-3-5-haiku&#34;, &#34;cerebras/qwen-3-235b-a22b-instruct&#34;, &#34;cerebras/qwen-3-235b-a22b-thinking&#34;, &#34;cerebras/llama-3.3-70b&#34;, &#34;cerebras/llama-4-maverick-17b-128e-instruct&#34;, &#34;cerebras/llama-4-scout-17b-16e-instruct&#34;, &#34;cerebras/gpt-oss-120b&#34;, &#34;google-ai-studio/gemini-2.5-flash&#34;, &#34;google-ai-studio/gemini-2.5-pro&#34;, &#34;grok/grok-4&#34;, &#34;groq/llama-3.3-70b-versatile&#34;, &#34;groq/llama-3.1-8b-instant&#34;, &#34;openai/gpt-5&#34;, &#34;openai/gpt-5-mini&#34;, &#34;openai/gpt-5-nano&#34;, &#34;&#34;.
     * 
     */
    private String rewriteModel;
    private Boolean rewriteQuery;
    private Double scoreThreshold;
    private String source;
    private GetAiSearchInstancesResultSourceParams sourceParams;
    private String status;
    /**
     * @return Interval between automatic syncs, in seconds. Allowed values: 900 (15min), 1800 (30min), 3600 (1h), 7200 (2h), 14400 (4h), 21600 (6h), 43200 (12h), 86400 (24h).
     * Available values: 900, 1800, 3600, 7200, 14400, 21600, 43200, 86400.
     * 
     */
    private Double syncInterval;
    private String tokenId;
    /**
     * @return Available values: &#34;r2&#34;, &#34;web-crawler&#34;.
     * 
     */
    private String type;

    private GetAiSearchInstancesResult() {}
    public String aiGatewayId() {
        return this.aiGatewayId;
    }
    /**
     * @return Available values: &#34;{@literal @}cf/meta/llama-3.3-70b-instruct-fp8-fast&#34;, &#34;{@literal @}cf/zai-org/glm-4.7-flash&#34;, &#34;{@literal @}cf/meta/llama-3.1-8b-instruct-fast&#34;, &#34;{@literal @}cf/meta/llama-3.1-8b-instruct-fp8&#34;, &#34;{@literal @}cf/meta/llama-4-scout-17b-16e-instruct&#34;, &#34;{@literal @}cf/qwen/qwen3-30b-a3b-fp8&#34;, &#34;{@literal @}cf/deepseek-ai/deepseek-r1-distill-qwen-32b&#34;, &#34;{@literal @}cf/moonshotai/kimi-k2-instruct&#34;, &#34;{@literal @}cf/google/gemma-3-12b-it&#34;, &#34;{@literal @}cf/google/gemma-4-26b-a4b-it&#34;, &#34;{@literal @}cf/moonshotai/kimi-k2.5&#34;, &#34;anthropic/claude-3-7-sonnet&#34;, &#34;anthropic/claude-sonnet-4&#34;, &#34;anthropic/claude-opus-4&#34;, &#34;anthropic/claude-3-5-haiku&#34;, &#34;cerebras/qwen-3-235b-a22b-instruct&#34;, &#34;cerebras/qwen-3-235b-a22b-thinking&#34;, &#34;cerebras/llama-3.3-70b&#34;, &#34;cerebras/llama-4-maverick-17b-128e-instruct&#34;, &#34;cerebras/llama-4-scout-17b-16e-instruct&#34;, &#34;cerebras/gpt-oss-120b&#34;, &#34;google-ai-studio/gemini-2.5-flash&#34;, &#34;google-ai-studio/gemini-2.5-pro&#34;, &#34;grok/grok-4&#34;, &#34;groq/llama-3.3-70b-versatile&#34;, &#34;groq/llama-3.1-8b-instant&#34;, &#34;openai/gpt-5&#34;, &#34;openai/gpt-5-mini&#34;, &#34;openai/gpt-5-nano&#34;, &#34;&#34;.
     * 
     */
    public String aisearchModel() {
        return this.aisearchModel;
    }
    public Boolean cache() {
        return this.cache;
    }
    /**
     * @return Available values: &#34;super*strict*match&#34;, &#34;close*enough&#34;, &#34;flexible*friend&#34;, &#34;anythingGoes&#34;.
     * 
     */
    public String cacheThreshold() {
        return this.cacheThreshold;
    }
    public Integer chunkOverlap() {
        return this.chunkOverlap;
    }
    public Integer chunkSize() {
        return this.chunkSize;
    }
    public String createdAt() {
        return this.createdAt;
    }
    public String createdBy() {
        return this.createdBy;
    }
    public List<GetAiSearchInstancesResultCustomMetadata> customMetadatas() {
        return this.customMetadatas;
    }
    /**
     * @return Available values: &#34;{@literal @}cf/qwen/qwen3-embedding-0.6b&#34;, &#34;{@literal @}cf/baai/bge-m3&#34;, &#34;{@literal @}cf/baai/bge-large-en-v1.5&#34;, &#34;{@literal @}cf/google/embeddinggemma-300m&#34;, &#34;google-ai-studio/gemini-embedding-001&#34;, &#34;google-ai-studio/gemini-embedding-2-preview&#34;, &#34;openai/text-embedding-3-small&#34;, &#34;openai/text-embedding-3-large&#34;, &#34;&#34;.
     * 
     */
    public String embeddingModel() {
        return this.embeddingModel;
    }
    public Boolean enable() {
        return this.enable;
    }
    public Double engineVersion() {
        return this.engineVersion;
    }
    /**
     * @return Available values: &#34;max&#34;, &#34;rrf&#34;.
     * 
     */
    public String fusionMethod() {
        return this.fusionMethod;
    }
    /**
     * @return Deprecated — use indexMethod instead.
     * 
     * @deprecated
     * This attribute is deprecated.
     * 
     */
    @Deprecated /* This attribute is deprecated. */
    public Boolean hybridSearchEnabled() {
        return this.hybridSearchEnabled;
    }
    /**
     * @return AI Search instance ID. Lowercase alphanumeric, hyphens, and underscores.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return Controls which storage backends are used during indexing. Defaults to vector-only.
     * 
     */
    public GetAiSearchInstancesResultIndexMethod indexMethod() {
        return this.indexMethod;
    }
    public GetAiSearchInstancesResultIndexingOptions indexingOptions() {
        return this.indexingOptions;
    }
    public String lastActivity() {
        return this.lastActivity;
    }
    public Integer maxNumResults() {
        return this.maxNumResults;
    }
    public GetAiSearchInstancesResultMetadata metadata() {
        return this.metadata;
    }
    public String modifiedAt() {
        return this.modifiedAt;
    }
    public String modifiedBy() {
        return this.modifiedBy;
    }
    public String namespace() {
        return this.namespace;
    }
    public Boolean paused() {
        return this.paused;
    }
    public String publicEndpointId() {
        return this.publicEndpointId;
    }
    public GetAiSearchInstancesResultPublicEndpointParams publicEndpointParams() {
        return this.publicEndpointParams;
    }
    public Boolean reranking() {
        return this.reranking;
    }
    /**
     * @return Available values: &#34;{@literal @}cf/baai/bge-reranker-base&#34;, &#34;&#34;.
     * 
     */
    public String rerankingModel() {
        return this.rerankingModel;
    }
    public GetAiSearchInstancesResultRetrievalOptions retrievalOptions() {
        return this.retrievalOptions;
    }
    /**
     * @return Available values: &#34;{@literal @}cf/meta/llama-3.3-70b-instruct-fp8-fast&#34;, &#34;{@literal @}cf/zai-org/glm-4.7-flash&#34;, &#34;{@literal @}cf/meta/llama-3.1-8b-instruct-fast&#34;, &#34;{@literal @}cf/meta/llama-3.1-8b-instruct-fp8&#34;, &#34;{@literal @}cf/meta/llama-4-scout-17b-16e-instruct&#34;, &#34;{@literal @}cf/qwen/qwen3-30b-a3b-fp8&#34;, &#34;{@literal @}cf/deepseek-ai/deepseek-r1-distill-qwen-32b&#34;, &#34;{@literal @}cf/moonshotai/kimi-k2-instruct&#34;, &#34;{@literal @}cf/google/gemma-3-12b-it&#34;, &#34;{@literal @}cf/google/gemma-4-26b-a4b-it&#34;, &#34;{@literal @}cf/moonshotai/kimi-k2.5&#34;, &#34;anthropic/claude-3-7-sonnet&#34;, &#34;anthropic/claude-sonnet-4&#34;, &#34;anthropic/claude-opus-4&#34;, &#34;anthropic/claude-3-5-haiku&#34;, &#34;cerebras/qwen-3-235b-a22b-instruct&#34;, &#34;cerebras/qwen-3-235b-a22b-thinking&#34;, &#34;cerebras/llama-3.3-70b&#34;, &#34;cerebras/llama-4-maverick-17b-128e-instruct&#34;, &#34;cerebras/llama-4-scout-17b-16e-instruct&#34;, &#34;cerebras/gpt-oss-120b&#34;, &#34;google-ai-studio/gemini-2.5-flash&#34;, &#34;google-ai-studio/gemini-2.5-pro&#34;, &#34;grok/grok-4&#34;, &#34;groq/llama-3.3-70b-versatile&#34;, &#34;groq/llama-3.1-8b-instant&#34;, &#34;openai/gpt-5&#34;, &#34;openai/gpt-5-mini&#34;, &#34;openai/gpt-5-nano&#34;, &#34;&#34;.
     * 
     */
    public String rewriteModel() {
        return this.rewriteModel;
    }
    public Boolean rewriteQuery() {
        return this.rewriteQuery;
    }
    public Double scoreThreshold() {
        return this.scoreThreshold;
    }
    public String source() {
        return this.source;
    }
    public GetAiSearchInstancesResultSourceParams sourceParams() {
        return this.sourceParams;
    }
    public String status() {
        return this.status;
    }
    /**
     * @return Interval between automatic syncs, in seconds. Allowed values: 900 (15min), 1800 (30min), 3600 (1h), 7200 (2h), 14400 (4h), 21600 (6h), 43200 (12h), 86400 (24h).
     * Available values: 900, 1800, 3600, 7200, 14400, 21600, 43200, 86400.
     * 
     */
    public Double syncInterval() {
        return this.syncInterval;
    }
    public String tokenId() {
        return this.tokenId;
    }
    /**
     * @return Available values: &#34;r2&#34;, &#34;web-crawler&#34;.
     * 
     */
    public String type() {
        return this.type;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetAiSearchInstancesResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String aiGatewayId;
        private String aisearchModel;
        private Boolean cache;
        private String cacheThreshold;
        private Integer chunkOverlap;
        private Integer chunkSize;
        private String createdAt;
        private String createdBy;
        private List<GetAiSearchInstancesResultCustomMetadata> customMetadatas;
        private String embeddingModel;
        private Boolean enable;
        private Double engineVersion;
        private String fusionMethod;
        private Boolean hybridSearchEnabled;
        private String id;
        private GetAiSearchInstancesResultIndexMethod indexMethod;
        private GetAiSearchInstancesResultIndexingOptions indexingOptions;
        private String lastActivity;
        private Integer maxNumResults;
        private GetAiSearchInstancesResultMetadata metadata;
        private String modifiedAt;
        private String modifiedBy;
        private String namespace;
        private Boolean paused;
        private String publicEndpointId;
        private GetAiSearchInstancesResultPublicEndpointParams publicEndpointParams;
        private Boolean reranking;
        private String rerankingModel;
        private GetAiSearchInstancesResultRetrievalOptions retrievalOptions;
        private String rewriteModel;
        private Boolean rewriteQuery;
        private Double scoreThreshold;
        private String source;
        private GetAiSearchInstancesResultSourceParams sourceParams;
        private String status;
        private Double syncInterval;
        private String tokenId;
        private String type;
        public Builder() {}
        public Builder(GetAiSearchInstancesResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.aiGatewayId = defaults.aiGatewayId;
    	      this.aisearchModel = defaults.aisearchModel;
    	      this.cache = defaults.cache;
    	      this.cacheThreshold = defaults.cacheThreshold;
    	      this.chunkOverlap = defaults.chunkOverlap;
    	      this.chunkSize = defaults.chunkSize;
    	      this.createdAt = defaults.createdAt;
    	      this.createdBy = defaults.createdBy;
    	      this.customMetadatas = defaults.customMetadatas;
    	      this.embeddingModel = defaults.embeddingModel;
    	      this.enable = defaults.enable;
    	      this.engineVersion = defaults.engineVersion;
    	      this.fusionMethod = defaults.fusionMethod;
    	      this.hybridSearchEnabled = defaults.hybridSearchEnabled;
    	      this.id = defaults.id;
    	      this.indexMethod = defaults.indexMethod;
    	      this.indexingOptions = defaults.indexingOptions;
    	      this.lastActivity = defaults.lastActivity;
    	      this.maxNumResults = defaults.maxNumResults;
    	      this.metadata = defaults.metadata;
    	      this.modifiedAt = defaults.modifiedAt;
    	      this.modifiedBy = defaults.modifiedBy;
    	      this.namespace = defaults.namespace;
    	      this.paused = defaults.paused;
    	      this.publicEndpointId = defaults.publicEndpointId;
    	      this.publicEndpointParams = defaults.publicEndpointParams;
    	      this.reranking = defaults.reranking;
    	      this.rerankingModel = defaults.rerankingModel;
    	      this.retrievalOptions = defaults.retrievalOptions;
    	      this.rewriteModel = defaults.rewriteModel;
    	      this.rewriteQuery = defaults.rewriteQuery;
    	      this.scoreThreshold = defaults.scoreThreshold;
    	      this.source = defaults.source;
    	      this.sourceParams = defaults.sourceParams;
    	      this.status = defaults.status;
    	      this.syncInterval = defaults.syncInterval;
    	      this.tokenId = defaults.tokenId;
    	      this.type = defaults.type;
        }

        @CustomType.Setter
        public Builder aiGatewayId(String aiGatewayId) {
            if (aiGatewayId == null) {
              throw new MissingRequiredPropertyException("GetAiSearchInstancesResult", "aiGatewayId");
            }
            this.aiGatewayId = aiGatewayId;
            return this;
        }
        @CustomType.Setter
        public Builder aisearchModel(String aisearchModel) {
            if (aisearchModel == null) {
              throw new MissingRequiredPropertyException("GetAiSearchInstancesResult", "aisearchModel");
            }
            this.aisearchModel = aisearchModel;
            return this;
        }
        @CustomType.Setter
        public Builder cache(Boolean cache) {
            if (cache == null) {
              throw new MissingRequiredPropertyException("GetAiSearchInstancesResult", "cache");
            }
            this.cache = cache;
            return this;
        }
        @CustomType.Setter
        public Builder cacheThreshold(String cacheThreshold) {
            if (cacheThreshold == null) {
              throw new MissingRequiredPropertyException("GetAiSearchInstancesResult", "cacheThreshold");
            }
            this.cacheThreshold = cacheThreshold;
            return this;
        }
        @CustomType.Setter
        public Builder chunkOverlap(Integer chunkOverlap) {
            if (chunkOverlap == null) {
              throw new MissingRequiredPropertyException("GetAiSearchInstancesResult", "chunkOverlap");
            }
            this.chunkOverlap = chunkOverlap;
            return this;
        }
        @CustomType.Setter
        public Builder chunkSize(Integer chunkSize) {
            if (chunkSize == null) {
              throw new MissingRequiredPropertyException("GetAiSearchInstancesResult", "chunkSize");
            }
            this.chunkSize = chunkSize;
            return this;
        }
        @CustomType.Setter
        public Builder createdAt(String createdAt) {
            if (createdAt == null) {
              throw new MissingRequiredPropertyException("GetAiSearchInstancesResult", "createdAt");
            }
            this.createdAt = createdAt;
            return this;
        }
        @CustomType.Setter
        public Builder createdBy(String createdBy) {
            if (createdBy == null) {
              throw new MissingRequiredPropertyException("GetAiSearchInstancesResult", "createdBy");
            }
            this.createdBy = createdBy;
            return this;
        }
        @CustomType.Setter
        public Builder customMetadatas(List<GetAiSearchInstancesResultCustomMetadata> customMetadatas) {
            if (customMetadatas == null) {
              throw new MissingRequiredPropertyException("GetAiSearchInstancesResult", "customMetadatas");
            }
            this.customMetadatas = customMetadatas;
            return this;
        }
        public Builder customMetadatas(GetAiSearchInstancesResultCustomMetadata... customMetadatas) {
            return customMetadatas(List.of(customMetadatas));
        }
        @CustomType.Setter
        public Builder embeddingModel(String embeddingModel) {
            if (embeddingModel == null) {
              throw new MissingRequiredPropertyException("GetAiSearchInstancesResult", "embeddingModel");
            }
            this.embeddingModel = embeddingModel;
            return this;
        }
        @CustomType.Setter
        public Builder enable(Boolean enable) {
            if (enable == null) {
              throw new MissingRequiredPropertyException("GetAiSearchInstancesResult", "enable");
            }
            this.enable = enable;
            return this;
        }
        @CustomType.Setter
        public Builder engineVersion(Double engineVersion) {
            if (engineVersion == null) {
              throw new MissingRequiredPropertyException("GetAiSearchInstancesResult", "engineVersion");
            }
            this.engineVersion = engineVersion;
            return this;
        }
        @CustomType.Setter
        public Builder fusionMethod(String fusionMethod) {
            if (fusionMethod == null) {
              throw new MissingRequiredPropertyException("GetAiSearchInstancesResult", "fusionMethod");
            }
            this.fusionMethod = fusionMethod;
            return this;
        }
        @CustomType.Setter
        public Builder hybridSearchEnabled(Boolean hybridSearchEnabled) {
            if (hybridSearchEnabled == null) {
              throw new MissingRequiredPropertyException("GetAiSearchInstancesResult", "hybridSearchEnabled");
            }
            this.hybridSearchEnabled = hybridSearchEnabled;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetAiSearchInstancesResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder indexMethod(GetAiSearchInstancesResultIndexMethod indexMethod) {
            if (indexMethod == null) {
              throw new MissingRequiredPropertyException("GetAiSearchInstancesResult", "indexMethod");
            }
            this.indexMethod = indexMethod;
            return this;
        }
        @CustomType.Setter
        public Builder indexingOptions(GetAiSearchInstancesResultIndexingOptions indexingOptions) {
            if (indexingOptions == null) {
              throw new MissingRequiredPropertyException("GetAiSearchInstancesResult", "indexingOptions");
            }
            this.indexingOptions = indexingOptions;
            return this;
        }
        @CustomType.Setter
        public Builder lastActivity(String lastActivity) {
            if (lastActivity == null) {
              throw new MissingRequiredPropertyException("GetAiSearchInstancesResult", "lastActivity");
            }
            this.lastActivity = lastActivity;
            return this;
        }
        @CustomType.Setter
        public Builder maxNumResults(Integer maxNumResults) {
            if (maxNumResults == null) {
              throw new MissingRequiredPropertyException("GetAiSearchInstancesResult", "maxNumResults");
            }
            this.maxNumResults = maxNumResults;
            return this;
        }
        @CustomType.Setter
        public Builder metadata(GetAiSearchInstancesResultMetadata metadata) {
            if (metadata == null) {
              throw new MissingRequiredPropertyException("GetAiSearchInstancesResult", "metadata");
            }
            this.metadata = metadata;
            return this;
        }
        @CustomType.Setter
        public Builder modifiedAt(String modifiedAt) {
            if (modifiedAt == null) {
              throw new MissingRequiredPropertyException("GetAiSearchInstancesResult", "modifiedAt");
            }
            this.modifiedAt = modifiedAt;
            return this;
        }
        @CustomType.Setter
        public Builder modifiedBy(String modifiedBy) {
            if (modifiedBy == null) {
              throw new MissingRequiredPropertyException("GetAiSearchInstancesResult", "modifiedBy");
            }
            this.modifiedBy = modifiedBy;
            return this;
        }
        @CustomType.Setter
        public Builder namespace(String namespace) {
            if (namespace == null) {
              throw new MissingRequiredPropertyException("GetAiSearchInstancesResult", "namespace");
            }
            this.namespace = namespace;
            return this;
        }
        @CustomType.Setter
        public Builder paused(Boolean paused) {
            if (paused == null) {
              throw new MissingRequiredPropertyException("GetAiSearchInstancesResult", "paused");
            }
            this.paused = paused;
            return this;
        }
        @CustomType.Setter
        public Builder publicEndpointId(String publicEndpointId) {
            if (publicEndpointId == null) {
              throw new MissingRequiredPropertyException("GetAiSearchInstancesResult", "publicEndpointId");
            }
            this.publicEndpointId = publicEndpointId;
            return this;
        }
        @CustomType.Setter
        public Builder publicEndpointParams(GetAiSearchInstancesResultPublicEndpointParams publicEndpointParams) {
            if (publicEndpointParams == null) {
              throw new MissingRequiredPropertyException("GetAiSearchInstancesResult", "publicEndpointParams");
            }
            this.publicEndpointParams = publicEndpointParams;
            return this;
        }
        @CustomType.Setter
        public Builder reranking(Boolean reranking) {
            if (reranking == null) {
              throw new MissingRequiredPropertyException("GetAiSearchInstancesResult", "reranking");
            }
            this.reranking = reranking;
            return this;
        }
        @CustomType.Setter
        public Builder rerankingModel(String rerankingModel) {
            if (rerankingModel == null) {
              throw new MissingRequiredPropertyException("GetAiSearchInstancesResult", "rerankingModel");
            }
            this.rerankingModel = rerankingModel;
            return this;
        }
        @CustomType.Setter
        public Builder retrievalOptions(GetAiSearchInstancesResultRetrievalOptions retrievalOptions) {
            if (retrievalOptions == null) {
              throw new MissingRequiredPropertyException("GetAiSearchInstancesResult", "retrievalOptions");
            }
            this.retrievalOptions = retrievalOptions;
            return this;
        }
        @CustomType.Setter
        public Builder rewriteModel(String rewriteModel) {
            if (rewriteModel == null) {
              throw new MissingRequiredPropertyException("GetAiSearchInstancesResult", "rewriteModel");
            }
            this.rewriteModel = rewriteModel;
            return this;
        }
        @CustomType.Setter
        public Builder rewriteQuery(Boolean rewriteQuery) {
            if (rewriteQuery == null) {
              throw new MissingRequiredPropertyException("GetAiSearchInstancesResult", "rewriteQuery");
            }
            this.rewriteQuery = rewriteQuery;
            return this;
        }
        @CustomType.Setter
        public Builder scoreThreshold(Double scoreThreshold) {
            if (scoreThreshold == null) {
              throw new MissingRequiredPropertyException("GetAiSearchInstancesResult", "scoreThreshold");
            }
            this.scoreThreshold = scoreThreshold;
            return this;
        }
        @CustomType.Setter
        public Builder source(String source) {
            if (source == null) {
              throw new MissingRequiredPropertyException("GetAiSearchInstancesResult", "source");
            }
            this.source = source;
            return this;
        }
        @CustomType.Setter
        public Builder sourceParams(GetAiSearchInstancesResultSourceParams sourceParams) {
            if (sourceParams == null) {
              throw new MissingRequiredPropertyException("GetAiSearchInstancesResult", "sourceParams");
            }
            this.sourceParams = sourceParams;
            return this;
        }
        @CustomType.Setter
        public Builder status(String status) {
            if (status == null) {
              throw new MissingRequiredPropertyException("GetAiSearchInstancesResult", "status");
            }
            this.status = status;
            return this;
        }
        @CustomType.Setter
        public Builder syncInterval(Double syncInterval) {
            if (syncInterval == null) {
              throw new MissingRequiredPropertyException("GetAiSearchInstancesResult", "syncInterval");
            }
            this.syncInterval = syncInterval;
            return this;
        }
        @CustomType.Setter
        public Builder tokenId(String tokenId) {
            if (tokenId == null) {
              throw new MissingRequiredPropertyException("GetAiSearchInstancesResult", "tokenId");
            }
            this.tokenId = tokenId;
            return this;
        }
        @CustomType.Setter
        public Builder type(String type) {
            if (type == null) {
              throw new MissingRequiredPropertyException("GetAiSearchInstancesResult", "type");
            }
            this.type = type;
            return this;
        }
        public GetAiSearchInstancesResult build() {
            final var _resultValue = new GetAiSearchInstancesResult();
            _resultValue.aiGatewayId = aiGatewayId;
            _resultValue.aisearchModel = aisearchModel;
            _resultValue.cache = cache;
            _resultValue.cacheThreshold = cacheThreshold;
            _resultValue.chunkOverlap = chunkOverlap;
            _resultValue.chunkSize = chunkSize;
            _resultValue.createdAt = createdAt;
            _resultValue.createdBy = createdBy;
            _resultValue.customMetadatas = customMetadatas;
            _resultValue.embeddingModel = embeddingModel;
            _resultValue.enable = enable;
            _resultValue.engineVersion = engineVersion;
            _resultValue.fusionMethod = fusionMethod;
            _resultValue.hybridSearchEnabled = hybridSearchEnabled;
            _resultValue.id = id;
            _resultValue.indexMethod = indexMethod;
            _resultValue.indexingOptions = indexingOptions;
            _resultValue.lastActivity = lastActivity;
            _resultValue.maxNumResults = maxNumResults;
            _resultValue.metadata = metadata;
            _resultValue.modifiedAt = modifiedAt;
            _resultValue.modifiedBy = modifiedBy;
            _resultValue.namespace = namespace;
            _resultValue.paused = paused;
            _resultValue.publicEndpointId = publicEndpointId;
            _resultValue.publicEndpointParams = publicEndpointParams;
            _resultValue.reranking = reranking;
            _resultValue.rerankingModel = rerankingModel;
            _resultValue.retrievalOptions = retrievalOptions;
            _resultValue.rewriteModel = rewriteModel;
            _resultValue.rewriteQuery = rewriteQuery;
            _resultValue.scoreThreshold = scoreThreshold;
            _resultValue.source = source;
            _resultValue.sourceParams = sourceParams;
            _resultValue.status = status;
            _resultValue.syncInterval = syncInterval;
            _resultValue.tokenId = tokenId;
            _resultValue.type = type;
            return _resultValue;
        }
    }
}
