// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudflare.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetCloudforceOneRequestAssetResult {
    /**
     * @return Identifier
     * 
     */
    private String accountIdentifier;
    /**
     * @return UUID
     * 
     */
    private String assetIdentifer;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    /**
     * @return UUID
     * 
     */
    private String requestIdentifier;

    private GetCloudforceOneRequestAssetResult() {}
    /**
     * @return Identifier
     * 
     */
    public String accountIdentifier() {
        return this.accountIdentifier;
    }
    /**
     * @return UUID
     * 
     */
    public String assetIdentifer() {
        return this.assetIdentifer;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return UUID
     * 
     */
    public String requestIdentifier() {
        return this.requestIdentifier;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetCloudforceOneRequestAssetResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String accountIdentifier;
        private String assetIdentifer;
        private String id;
        private String requestIdentifier;
        public Builder() {}
        public Builder(GetCloudforceOneRequestAssetResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.accountIdentifier = defaults.accountIdentifier;
    	      this.assetIdentifer = defaults.assetIdentifer;
    	      this.id = defaults.id;
    	      this.requestIdentifier = defaults.requestIdentifier;
        }

        @CustomType.Setter
        public Builder accountIdentifier(String accountIdentifier) {
            if (accountIdentifier == null) {
              throw new MissingRequiredPropertyException("GetCloudforceOneRequestAssetResult", "accountIdentifier");
            }
            this.accountIdentifier = accountIdentifier;
            return this;
        }
        @CustomType.Setter
        public Builder assetIdentifer(String assetIdentifer) {
            if (assetIdentifer == null) {
              throw new MissingRequiredPropertyException("GetCloudforceOneRequestAssetResult", "assetIdentifer");
            }
            this.assetIdentifer = assetIdentifer;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetCloudforceOneRequestAssetResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder requestIdentifier(String requestIdentifier) {
            if (requestIdentifier == null) {
              throw new MissingRequiredPropertyException("GetCloudforceOneRequestAssetResult", "requestIdentifier");
            }
            this.requestIdentifier = requestIdentifier;
            return this;
        }
        public GetCloudforceOneRequestAssetResult build() {
            final var _resultValue = new GetCloudforceOneRequestAssetResult();
            _resultValue.accountIdentifier = accountIdentifier;
            _resultValue.assetIdentifer = assetIdentifer;
            _resultValue.id = id;
            _resultValue.requestIdentifier = requestIdentifier;
            return _resultValue;
        }
    }
}
