// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudflare.outputs;

import com.pulumi.cloudflare.outputs.GetMagicTransitCf1SitesResultLocation;
import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetMagicTransitCf1SitesResult {
    private String createdOn;
    /**
     * @return A human-provided description of the CF1 Site.
     * 
     */
    private String description;
    /**
     * @return Identifier
     * 
     */
    private String id;
    private GetMagicTransitCf1SitesResultLocation location;
    private String modifiedOn;
    /**
     * @return A human-provided name describing the CF1 Site that should be unique within the account.
     * 
     */
    private String name;

    private GetMagicTransitCf1SitesResult() {}
    public String createdOn() {
        return this.createdOn;
    }
    /**
     * @return A human-provided description of the CF1 Site.
     * 
     */
    public String description() {
        return this.description;
    }
    /**
     * @return Identifier
     * 
     */
    public String id() {
        return this.id;
    }
    public GetMagicTransitCf1SitesResultLocation location() {
        return this.location;
    }
    public String modifiedOn() {
        return this.modifiedOn;
    }
    /**
     * @return A human-provided name describing the CF1 Site that should be unique within the account.
     * 
     */
    public String name() {
        return this.name;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetMagicTransitCf1SitesResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String createdOn;
        private String description;
        private String id;
        private GetMagicTransitCf1SitesResultLocation location;
        private String modifiedOn;
        private String name;
        public Builder() {}
        public Builder(GetMagicTransitCf1SitesResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.createdOn = defaults.createdOn;
    	      this.description = defaults.description;
    	      this.id = defaults.id;
    	      this.location = defaults.location;
    	      this.modifiedOn = defaults.modifiedOn;
    	      this.name = defaults.name;
        }

        @CustomType.Setter
        public Builder createdOn(String createdOn) {
            if (createdOn == null) {
              throw new MissingRequiredPropertyException("GetMagicTransitCf1SitesResult", "createdOn");
            }
            this.createdOn = createdOn;
            return this;
        }
        @CustomType.Setter
        public Builder description(String description) {
            if (description == null) {
              throw new MissingRequiredPropertyException("GetMagicTransitCf1SitesResult", "description");
            }
            this.description = description;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetMagicTransitCf1SitesResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder location(GetMagicTransitCf1SitesResultLocation location) {
            if (location == null) {
              throw new MissingRequiredPropertyException("GetMagicTransitCf1SitesResult", "location");
            }
            this.location = location;
            return this;
        }
        @CustomType.Setter
        public Builder modifiedOn(String modifiedOn) {
            if (modifiedOn == null) {
              throw new MissingRequiredPropertyException("GetMagicTransitCf1SitesResult", "modifiedOn");
            }
            this.modifiedOn = modifiedOn;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetMagicTransitCf1SitesResult", "name");
            }
            this.name = name;
            return this;
        }
        public GetMagicTransitCf1SitesResult build() {
            final var _resultValue = new GetMagicTransitCf1SitesResult();
            _resultValue.createdOn = createdOn;
            _resultValue.description = description;
            _resultValue.id = id;
            _resultValue.location = location;
            _resultValue.modifiedOn = modifiedOn;
            _resultValue.name = name;
            return _resultValue;
        }
    }
}
