// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudflare.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetPagesProjectDeploymentConfigsProductionEnvVars {
    /**
     * @return Available values: &#34;plain*text&#34;, &#34;secret*text&#34;.
     * 
     */
    private String type;
    /**
     * @return Environment variable value.
     * 
     */
    private String value;

    private GetPagesProjectDeploymentConfigsProductionEnvVars() {}
    /**
     * @return Available values: &#34;plain*text&#34;, &#34;secret*text&#34;.
     * 
     */
    public String type() {
        return this.type;
    }
    /**
     * @return Environment variable value.
     * 
     */
    public String value() {
        return this.value;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetPagesProjectDeploymentConfigsProductionEnvVars defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String type;
        private String value;
        public Builder() {}
        public Builder(GetPagesProjectDeploymentConfigsProductionEnvVars defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.type = defaults.type;
    	      this.value = defaults.value;
        }

        @CustomType.Setter
        public Builder type(String type) {
            if (type == null) {
              throw new MissingRequiredPropertyException("GetPagesProjectDeploymentConfigsProductionEnvVars", "type");
            }
            this.type = type;
            return this;
        }
        @CustomType.Setter
        public Builder value(String value) {
            if (value == null) {
              throw new MissingRequiredPropertyException("GetPagesProjectDeploymentConfigsProductionEnvVars", "value");
            }
            this.value = value;
            return this;
        }
        public GetPagesProjectDeploymentConfigsProductionEnvVars build() {
            final var _resultValue = new GetPagesProjectDeploymentConfigsProductionEnvVars();
            _resultValue.type = type;
            _resultValue.value = value;
            return _resultValue;
        }
    }
}
