// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudflare.outputs;

import com.pulumi.cloudflare.outputs.GetWorkersSecretsResult;
import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetWorkersSecretsInvokeResult {
    /**
     * @return Identifier
     * 
     */
    private String accountId;
    /**
     * @return Name of the Workers for Platforms dispatch namespace.
     * 
     */
    private String dispatchNamespace;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    /**
     * @return Max items to fetch, default: 1000
     * 
     */
    private @Nullable Integer maxItems;
    /**
     * @return The items returned by the data source
     * 
     */
    private List<GetWorkersSecretsResult> results;
    /**
     * @return Name of the script, used in URLs and route configuration.
     * 
     */
    private String scriptName;

    private GetWorkersSecretsInvokeResult() {}
    /**
     * @return Identifier
     * 
     */
    public String accountId() {
        return this.accountId;
    }
    /**
     * @return Name of the Workers for Platforms dispatch namespace.
     * 
     */
    public String dispatchNamespace() {
        return this.dispatchNamespace;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return Max items to fetch, default: 1000
     * 
     */
    public Optional<Integer> maxItems() {
        return Optional.ofNullable(this.maxItems);
    }
    /**
     * @return The items returned by the data source
     * 
     */
    public List<GetWorkersSecretsResult> results() {
        return this.results;
    }
    /**
     * @return Name of the script, used in URLs and route configuration.
     * 
     */
    public String scriptName() {
        return this.scriptName;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetWorkersSecretsInvokeResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String accountId;
        private String dispatchNamespace;
        private String id;
        private @Nullable Integer maxItems;
        private List<GetWorkersSecretsResult> results;
        private String scriptName;
        public Builder() {}
        public Builder(GetWorkersSecretsInvokeResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.accountId = defaults.accountId;
    	      this.dispatchNamespace = defaults.dispatchNamespace;
    	      this.id = defaults.id;
    	      this.maxItems = defaults.maxItems;
    	      this.results = defaults.results;
    	      this.scriptName = defaults.scriptName;
        }

        @CustomType.Setter
        public Builder accountId(String accountId) {
            if (accountId == null) {
              throw new MissingRequiredPropertyException("GetWorkersSecretsInvokeResult", "accountId");
            }
            this.accountId = accountId;
            return this;
        }
        @CustomType.Setter
        public Builder dispatchNamespace(String dispatchNamespace) {
            if (dispatchNamespace == null) {
              throw new MissingRequiredPropertyException("GetWorkersSecretsInvokeResult", "dispatchNamespace");
            }
            this.dispatchNamespace = dispatchNamespace;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetWorkersSecretsInvokeResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder maxItems(@Nullable Integer maxItems) {

            this.maxItems = maxItems;
            return this;
        }
        @CustomType.Setter
        public Builder results(List<GetWorkersSecretsResult> results) {
            if (results == null) {
              throw new MissingRequiredPropertyException("GetWorkersSecretsInvokeResult", "results");
            }
            this.results = results;
            return this;
        }
        public Builder results(GetWorkersSecretsResult... results) {
            return results(List.of(results));
        }
        @CustomType.Setter
        public Builder scriptName(String scriptName) {
            if (scriptName == null) {
              throw new MissingRequiredPropertyException("GetWorkersSecretsInvokeResult", "scriptName");
            }
            this.scriptName = scriptName;
            return this;
        }
        public GetWorkersSecretsInvokeResult build() {
            final var _resultValue = new GetWorkersSecretsInvokeResult();
            _resultValue.accountId = accountId;
            _resultValue.dispatchNamespace = dispatchNamespace;
            _resultValue.id = id;
            _resultValue.maxItems = maxItems;
            _resultValue.results = results;
            _resultValue.scriptName = scriptName;
            return _resultValue;
        }
    }
}
