// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudflare.outputs;

import com.pulumi.cloudflare.outputs.GetZeroTrustDlpCustomEntriesResultConfidence;
import com.pulumi.cloudflare.outputs.GetZeroTrustDlpCustomEntriesResultPattern;
import com.pulumi.cloudflare.outputs.GetZeroTrustDlpCustomEntriesResultVariant;
import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetZeroTrustDlpCustomEntriesResult {
    /**
     * @return Only applies to custom word lists.
     * Determines if the words should be matched in a case-sensitive manner
     * Cannot be set to false if secret is true
     * 
     */
    private Boolean caseSensitive;
    private GetZeroTrustDlpCustomEntriesResultConfidence confidence;
    private String createdAt;
    private Boolean enabled;
    private String id;
    private String name;
    private GetZeroTrustDlpCustomEntriesResultPattern pattern;
    private String profileId;
    private Boolean secret;
    /**
     * @return Available values: &#34;custom&#34;, &#34;predefined&#34;, &#34;integration&#34;, &#34;exact*data&#34;, &#34;document*fingerprint&#34;, &#34;wordList&#34;.
     * 
     */
    private String type;
    private String updatedAt;
    /**
     * @return Available values: &#34;empty&#34;, &#34;uploading&#34;, &#34;pending&#34;, &#34;processing&#34;, &#34;failed&#34;, &#34;complete&#34;.
     * 
     */
    private String uploadStatus;
    private GetZeroTrustDlpCustomEntriesResultVariant variant;
    private String wordList;

    private GetZeroTrustDlpCustomEntriesResult() {}
    /**
     * @return Only applies to custom word lists.
     * Determines if the words should be matched in a case-sensitive manner
     * Cannot be set to false if secret is true
     * 
     */
    public Boolean caseSensitive() {
        return this.caseSensitive;
    }
    public GetZeroTrustDlpCustomEntriesResultConfidence confidence() {
        return this.confidence;
    }
    public String createdAt() {
        return this.createdAt;
    }
    public Boolean enabled() {
        return this.enabled;
    }
    public String id() {
        return this.id;
    }
    public String name() {
        return this.name;
    }
    public GetZeroTrustDlpCustomEntriesResultPattern pattern() {
        return this.pattern;
    }
    public String profileId() {
        return this.profileId;
    }
    public Boolean secret() {
        return this.secret;
    }
    /**
     * @return Available values: &#34;custom&#34;, &#34;predefined&#34;, &#34;integration&#34;, &#34;exact*data&#34;, &#34;document*fingerprint&#34;, &#34;wordList&#34;.
     * 
     */
    public String type() {
        return this.type;
    }
    public String updatedAt() {
        return this.updatedAt;
    }
    /**
     * @return Available values: &#34;empty&#34;, &#34;uploading&#34;, &#34;pending&#34;, &#34;processing&#34;, &#34;failed&#34;, &#34;complete&#34;.
     * 
     */
    public String uploadStatus() {
        return this.uploadStatus;
    }
    public GetZeroTrustDlpCustomEntriesResultVariant variant() {
        return this.variant;
    }
    public String wordList() {
        return this.wordList;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetZeroTrustDlpCustomEntriesResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Boolean caseSensitive;
        private GetZeroTrustDlpCustomEntriesResultConfidence confidence;
        private String createdAt;
        private Boolean enabled;
        private String id;
        private String name;
        private GetZeroTrustDlpCustomEntriesResultPattern pattern;
        private String profileId;
        private Boolean secret;
        private String type;
        private String updatedAt;
        private String uploadStatus;
        private GetZeroTrustDlpCustomEntriesResultVariant variant;
        private String wordList;
        public Builder() {}
        public Builder(GetZeroTrustDlpCustomEntriesResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.caseSensitive = defaults.caseSensitive;
    	      this.confidence = defaults.confidence;
    	      this.createdAt = defaults.createdAt;
    	      this.enabled = defaults.enabled;
    	      this.id = defaults.id;
    	      this.name = defaults.name;
    	      this.pattern = defaults.pattern;
    	      this.profileId = defaults.profileId;
    	      this.secret = defaults.secret;
    	      this.type = defaults.type;
    	      this.updatedAt = defaults.updatedAt;
    	      this.uploadStatus = defaults.uploadStatus;
    	      this.variant = defaults.variant;
    	      this.wordList = defaults.wordList;
        }

        @CustomType.Setter
        public Builder caseSensitive(Boolean caseSensitive) {
            if (caseSensitive == null) {
              throw new MissingRequiredPropertyException("GetZeroTrustDlpCustomEntriesResult", "caseSensitive");
            }
            this.caseSensitive = caseSensitive;
            return this;
        }
        @CustomType.Setter
        public Builder confidence(GetZeroTrustDlpCustomEntriesResultConfidence confidence) {
            if (confidence == null) {
              throw new MissingRequiredPropertyException("GetZeroTrustDlpCustomEntriesResult", "confidence");
            }
            this.confidence = confidence;
            return this;
        }
        @CustomType.Setter
        public Builder createdAt(String createdAt) {
            if (createdAt == null) {
              throw new MissingRequiredPropertyException("GetZeroTrustDlpCustomEntriesResult", "createdAt");
            }
            this.createdAt = createdAt;
            return this;
        }
        @CustomType.Setter
        public Builder enabled(Boolean enabled) {
            if (enabled == null) {
              throw new MissingRequiredPropertyException("GetZeroTrustDlpCustomEntriesResult", "enabled");
            }
            this.enabled = enabled;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetZeroTrustDlpCustomEntriesResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetZeroTrustDlpCustomEntriesResult", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder pattern(GetZeroTrustDlpCustomEntriesResultPattern pattern) {
            if (pattern == null) {
              throw new MissingRequiredPropertyException("GetZeroTrustDlpCustomEntriesResult", "pattern");
            }
            this.pattern = pattern;
            return this;
        }
        @CustomType.Setter
        public Builder profileId(String profileId) {
            if (profileId == null) {
              throw new MissingRequiredPropertyException("GetZeroTrustDlpCustomEntriesResult", "profileId");
            }
            this.profileId = profileId;
            return this;
        }
        @CustomType.Setter
        public Builder secret(Boolean secret) {
            if (secret == null) {
              throw new MissingRequiredPropertyException("GetZeroTrustDlpCustomEntriesResult", "secret");
            }
            this.secret = secret;
            return this;
        }
        @CustomType.Setter
        public Builder type(String type) {
            if (type == null) {
              throw new MissingRequiredPropertyException("GetZeroTrustDlpCustomEntriesResult", "type");
            }
            this.type = type;
            return this;
        }
        @CustomType.Setter
        public Builder updatedAt(String updatedAt) {
            if (updatedAt == null) {
              throw new MissingRequiredPropertyException("GetZeroTrustDlpCustomEntriesResult", "updatedAt");
            }
            this.updatedAt = updatedAt;
            return this;
        }
        @CustomType.Setter
        public Builder uploadStatus(String uploadStatus) {
            if (uploadStatus == null) {
              throw new MissingRequiredPropertyException("GetZeroTrustDlpCustomEntriesResult", "uploadStatus");
            }
            this.uploadStatus = uploadStatus;
            return this;
        }
        @CustomType.Setter
        public Builder variant(GetZeroTrustDlpCustomEntriesResultVariant variant) {
            if (variant == null) {
              throw new MissingRequiredPropertyException("GetZeroTrustDlpCustomEntriesResult", "variant");
            }
            this.variant = variant;
            return this;
        }
        @CustomType.Setter
        public Builder wordList(String wordList) {
            if (wordList == null) {
              throw new MissingRequiredPropertyException("GetZeroTrustDlpCustomEntriesResult", "wordList");
            }
            this.wordList = wordList;
            return this;
        }
        public GetZeroTrustDlpCustomEntriesResult build() {
            final var _resultValue = new GetZeroTrustDlpCustomEntriesResult();
            _resultValue.caseSensitive = caseSensitive;
            _resultValue.confidence = confidence;
            _resultValue.createdAt = createdAt;
            _resultValue.enabled = enabled;
            _resultValue.id = id;
            _resultValue.name = name;
            _resultValue.pattern = pattern;
            _resultValue.profileId = profileId;
            _resultValue.secret = secret;
            _resultValue.type = type;
            _resultValue.updatedAt = updatedAt;
            _resultValue.uploadStatus = uploadStatus;
            _resultValue.variant = variant;
            _resultValue.wordList = wordList;
            return _resultValue;
        }
    }
}
