// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudflare.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Double;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetZeroTrustAccessPoliciesResultApprovalGroup {
    /**
     * @return The number of approvals needed to obtain access.
     * 
     */
    private Double approvalsNeeded;
    /**
     * @return A list of emails that can approve the access request.
     * 
     */
    private List<String> emailAddresses;
    /**
     * @return The UUID of an re-usable email list.
     * 
     */
    private String emailListUuid;

    private GetZeroTrustAccessPoliciesResultApprovalGroup() {}
    /**
     * @return The number of approvals needed to obtain access.
     * 
     */
    public Double approvalsNeeded() {
        return this.approvalsNeeded;
    }
    /**
     * @return A list of emails that can approve the access request.
     * 
     */
    public List<String> emailAddresses() {
        return this.emailAddresses;
    }
    /**
     * @return The UUID of an re-usable email list.
     * 
     */
    public String emailListUuid() {
        return this.emailListUuid;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetZeroTrustAccessPoliciesResultApprovalGroup defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Double approvalsNeeded;
        private List<String> emailAddresses;
        private String emailListUuid;
        public Builder() {}
        public Builder(GetZeroTrustAccessPoliciesResultApprovalGroup defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.approvalsNeeded = defaults.approvalsNeeded;
    	      this.emailAddresses = defaults.emailAddresses;
    	      this.emailListUuid = defaults.emailListUuid;
        }

        @CustomType.Setter
        public Builder approvalsNeeded(Double approvalsNeeded) {
            if (approvalsNeeded == null) {
              throw new MissingRequiredPropertyException("GetZeroTrustAccessPoliciesResultApprovalGroup", "approvalsNeeded");
            }
            this.approvalsNeeded = approvalsNeeded;
            return this;
        }
        @CustomType.Setter
        public Builder emailAddresses(List<String> emailAddresses) {
            if (emailAddresses == null) {
              throw new MissingRequiredPropertyException("GetZeroTrustAccessPoliciesResultApprovalGroup", "emailAddresses");
            }
            this.emailAddresses = emailAddresses;
            return this;
        }
        public Builder emailAddresses(String... emailAddresses) {
            return emailAddresses(List.of(emailAddresses));
        }
        @CustomType.Setter
        public Builder emailListUuid(String emailListUuid) {
            if (emailListUuid == null) {
              throw new MissingRequiredPropertyException("GetZeroTrustAccessPoliciesResultApprovalGroup", "emailListUuid");
            }
            this.emailListUuid = emailListUuid;
            return this;
        }
        public GetZeroTrustAccessPoliciesResultApprovalGroup build() {
            final var _resultValue = new GetZeroTrustAccessPoliciesResultApprovalGroup();
            _resultValue.approvalsNeeded = approvalsNeeded;
            _resultValue.emailAddresses = emailAddresses;
            _resultValue.emailListUuid = emailListUuid;
            return _resultValue;
        }
    }
}
