// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudflare.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class MagicWanGreTunnelHealthCheckTarget {
    /**
     * @return The effective health check target. If &#39;saved&#39; is empty, then this field will be populated with the calculated default value on GET requests. Ignored in POST, PUT, and PATCH requests.
     * 
     */
    private @Nullable String effective;
    /**
     * @return The saved health check target. Setting the value to the empty string indicates that the calculated default value will be used.
     * 
     */
    private @Nullable String saved;

    private MagicWanGreTunnelHealthCheckTarget() {}
    /**
     * @return The effective health check target. If &#39;saved&#39; is empty, then this field will be populated with the calculated default value on GET requests. Ignored in POST, PUT, and PATCH requests.
     * 
     */
    public Optional<String> effective() {
        return Optional.ofNullable(this.effective);
    }
    /**
     * @return The saved health check target. Setting the value to the empty string indicates that the calculated default value will be used.
     * 
     */
    public Optional<String> saved() {
        return Optional.ofNullable(this.saved);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(MagicWanGreTunnelHealthCheckTarget defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String effective;
        private @Nullable String saved;
        public Builder() {}
        public Builder(MagicWanGreTunnelHealthCheckTarget defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.effective = defaults.effective;
    	      this.saved = defaults.saved;
        }

        @CustomType.Setter
        public Builder effective(@Nullable String effective) {

            this.effective = effective;
            return this;
        }
        @CustomType.Setter
        public Builder saved(@Nullable String saved) {

            this.saved = saved;
            return this;
        }
        public MagicWanGreTunnelHealthCheckTarget build() {
            final var _resultValue = new MagicWanGreTunnelHealthCheckTarget();
            _resultValue.effective = effective;
            _resultValue.saved = saved;
            return _resultValue;
        }
    }
}
