// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudflare.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class PagesProjectDeploymentConfigsPreviewD1Databases {
    /**
     * @return UUID of the D1 database.
     * 
     */
    private @Nullable String id;

    private PagesProjectDeploymentConfigsPreviewD1Databases() {}
    /**
     * @return UUID of the D1 database.
     * 
     */
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(PagesProjectDeploymentConfigsPreviewD1Databases defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String id;
        public Builder() {}
        public Builder(PagesProjectDeploymentConfigsPreviewD1Databases defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.id = defaults.id;
        }

        @CustomType.Setter
        public Builder id(@Nullable String id) {

            this.id = id;
            return this;
        }
        public PagesProjectDeploymentConfigsPreviewD1Databases build() {
            final var _resultValue = new PagesProjectDeploymentConfigsPreviewD1Databases();
            _resultValue.id = id;
            return _resultValue;
        }
    }
}
