// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudflare.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.util.Objects;

@CustomType
public final class TeamsAccountAntivirus {
    /**
     * @return Scan on file download.
     * 
     */
    private Boolean enabledDownloadPhase;
    /**
     * @return Scan on file upload.
     * 
     */
    private Boolean enabledUploadPhase;
    /**
     * @return Block requests for files that cannot be scanned.
     * 
     */
    private Boolean failClosed;

    private TeamsAccountAntivirus() {}
    /**
     * @return Scan on file download.
     * 
     */
    public Boolean enabledDownloadPhase() {
        return this.enabledDownloadPhase;
    }
    /**
     * @return Scan on file upload.
     * 
     */
    public Boolean enabledUploadPhase() {
        return this.enabledUploadPhase;
    }
    /**
     * @return Block requests for files that cannot be scanned.
     * 
     */
    public Boolean failClosed() {
        return this.failClosed;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(TeamsAccountAntivirus defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Boolean enabledDownloadPhase;
        private Boolean enabledUploadPhase;
        private Boolean failClosed;
        public Builder() {}
        public Builder(TeamsAccountAntivirus defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.enabledDownloadPhase = defaults.enabledDownloadPhase;
    	      this.enabledUploadPhase = defaults.enabledUploadPhase;
    	      this.failClosed = defaults.failClosed;
        }

        @CustomType.Setter
        public Builder enabledDownloadPhase(Boolean enabledDownloadPhase) {
            this.enabledDownloadPhase = Objects.requireNonNull(enabledDownloadPhase);
            return this;
        }
        @CustomType.Setter
        public Builder enabledUploadPhase(Boolean enabledUploadPhase) {
            this.enabledUploadPhase = Objects.requireNonNull(enabledUploadPhase);
            return this;
        }
        @CustomType.Setter
        public Builder failClosed(Boolean failClosed) {
            this.failClosed = Objects.requireNonNull(failClosed);
            return this;
        }
        public TeamsAccountAntivirus build() {
            final var _resultValue = new TeamsAccountAntivirus();
            _resultValue.enabledDownloadPhase = enabledDownloadPhase;
            _resultValue.enabledUploadPhase = enabledUploadPhase;
            _resultValue.failClosed = failClosed;
            return _resultValue;
        }
    }
}
