// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cloudflare.Modules.Custom
{
    public static class GetSsl
    {
        /// <summary>
        /// Accepted Permissions
        /// 
        /// - `Access: Mutual TLS Certificates Read`
        /// - `Access: Mutual TLS Certificates Write`
        /// - `SSL and Certificates Read`
        /// - `SSL and Certificates Write`
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Cloudflare = Pulumi.Cloudflare;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var exampleCustomSsl = Cloudflare.Modules.Custom.GetSsl.Invoke(new()
        ///     {
        ///         ZoneId = "023e105f4ecef8ad9ca31a8372d0c353",
        ///         CustomCertificateId = "023e105f4ecef8ad9ca31a8372d0c353",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetSslResult> InvokeAsync(GetSslArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSslResult>("cloudflare:custom/ssl:getSsl", args ?? new GetSslArgs(), options.WithDefaults());

        /// <summary>
        /// Accepted Permissions
        /// 
        /// - `Access: Mutual TLS Certificates Read`
        /// - `Access: Mutual TLS Certificates Write`
        /// - `SSL and Certificates Read`
        /// - `SSL and Certificates Write`
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Cloudflare = Pulumi.Cloudflare;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var exampleCustomSsl = Cloudflare.Modules.Custom.GetSsl.Invoke(new()
        ///     {
        ///         ZoneId = "023e105f4ecef8ad9ca31a8372d0c353",
        ///         CustomCertificateId = "023e105f4ecef8ad9ca31a8372d0c353",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetSslResult> Invoke(GetSslInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSslResult>("cloudflare:custom/ssl:getSsl", args ?? new GetSslInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Accepted Permissions
        /// 
        /// - `Access: Mutual TLS Certificates Read`
        /// - `Access: Mutual TLS Certificates Write`
        /// - `SSL and Certificates Read`
        /// - `SSL and Certificates Write`
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Cloudflare = Pulumi.Cloudflare;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var exampleCustomSsl = Cloudflare.Modules.Custom.GetSsl.Invoke(new()
        ///     {
        ///         ZoneId = "023e105f4ecef8ad9ca31a8372d0c353",
        ///         CustomCertificateId = "023e105f4ecef8ad9ca31a8372d0c353",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetSslResult> Invoke(GetSslInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetSslResult>("cloudflare:custom/ssl:getSsl", args ?? new GetSslInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSslArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Identifier.
        /// </summary>
        [Input("customCertificateId")]
        public string? CustomCertificateId { get; set; }

        [Input("filter")]
        public Inputs.GetSslFilterArgs? Filter { get; set; }

        /// <summary>
        /// Identifier.
        /// </summary>
        [Input("zoneId")]
        public string? ZoneId { get; set; }

        public GetSslArgs()
        {
        }
        public static new GetSslArgs Empty => new GetSslArgs();
    }

    public sealed class GetSslInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Identifier.
        /// </summary>
        [Input("customCertificateId")]
        public Input<string>? CustomCertificateId { get; set; }

        [Input("filter")]
        public Input<Inputs.GetSslFilterInputArgs>? Filter { get; set; }

        /// <summary>
        /// Identifier.
        /// </summary>
        [Input("zoneId")]
        public Input<string>? ZoneId { get; set; }

        public GetSslInvokeArgs()
        {
        }
        public static new GetSslInvokeArgs Empty => new GetSslInvokeArgs();
    }


    [OutputType]
    public sealed class GetSslResult
    {
        /// <summary>
        /// A ubiquitous bundle has the highest probability of being verified everywhere, even by clients using outdated or unusual trust stores. An optimal bundle uses the shortest chain and newest intermediates. And the force bundle verifies the chain, but does not otherwise modify it.
        /// Available values: "ubiquitous", "optimal", "force".
        /// </summary>
        public readonly string BundleMethod;
        /// <summary>
        /// Identifier.
        /// </summary>
        public readonly string? CustomCertificateId;
        /// <summary>
        /// The identifier for the Custom CSR that was used.
        /// </summary>
        public readonly string CustomCsrId;
        /// <summary>
        /// When the certificate from the authority expires.
        /// </summary>
        public readonly string ExpiresOn;
        public readonly Outputs.GetSslFilterResult? Filter;
        /// <summary>
        /// Specify the region where your private key can be held locally for optimal TLS performance. HTTPS connections to any excluded data center will still be fully encrypted, but will incur some latency while Keyless SSL is used to complete the handshake with the nearest allowed data center. Options allow distribution to only to U.S. data centers, only to E.U. data centers, or only to highest security data centers. Default distribution is to all Cloudflare datacenters, for optimal performance.
        /// </summary>
        public readonly Outputs.GetSslGeoRestrictionsResult GeoRestrictions;
        public readonly ImmutableArray<string> Hosts;
        /// <summary>
        /// Identifier.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The certificate authority that issued the certificate.
        /// </summary>
        public readonly string Issuer;
        public readonly Outputs.GetSslKeylessServerResult KeylessServer;
        /// <summary>
        /// When the certificate was last modified.
        /// </summary>
        public readonly string ModifiedOn;
        /// <summary>
        /// The policy restrictions returned by the API. This field is returned in responses
        /// when a policy has been set. The API accepts the "policy" field in requests but
        /// returns this field as "PolicyRestrictions" in responses.
        /// </summary>
        public readonly string PolicyRestrictions;
        public readonly double Priority;
        public readonly string Signature;
        public readonly string Status;
        public readonly string UploadedOn;
        /// <summary>
        /// Identifier.
        /// </summary>
        public readonly string? ZoneId;

        [OutputConstructor]
        private GetSslResult(
            string bundleMethod,

            string? customCertificateId,

            string customCsrId,

            string expiresOn,

            Outputs.GetSslFilterResult? filter,

            Outputs.GetSslGeoRestrictionsResult geoRestrictions,

            ImmutableArray<string> hosts,

            string id,

            string issuer,

            Outputs.GetSslKeylessServerResult keylessServer,

            string modifiedOn,

            string policyRestrictions,

            double priority,

            string signature,

            string status,

            string uploadedOn,

            string? zoneId)
        {
            BundleMethod = bundleMethod;
            CustomCertificateId = customCertificateId;
            CustomCsrId = customCsrId;
            ExpiresOn = expiresOn;
            Filter = filter;
            GeoRestrictions = geoRestrictions;
            Hosts = hosts;
            Id = id;
            Issuer = issuer;
            KeylessServer = keylessServer;
            ModifiedOn = modifiedOn;
            PolicyRestrictions = policyRestrictions;
            Priority = priority;
            Signature = signature;
            Status = status;
            UploadedOn = uploadedOn;
            ZoneId = zoneId;
        }
    }
}
