// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cloudflare

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Use this data source to get the [IP ranges](https://www.cloudflare.com/ips/) of Cloudflare network.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-cloudflare/sdk/v5/go/cloudflare"
//	"github.com/pulumi/pulumi-example/sdk/v1/go/example"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			cloudflare, err := cloudflare.GetIpRanges(ctx, nil, nil)
//			if err != nil {
//				return err
//			}
//			_, err = index.NewExample_firewall_resource(ctx, "example", &index.Example_firewall_resourceArgs{
//				Name:         "from-cloudflare",
//				Network:      "default",
//				SourceRanges: cloudflare.Ipv4CidrBlocks,
//				Allow: []map[string]interface{}{
//					map[string]interface{}{
//						"ports":    "443",
//						"protocol": "tcp",
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func GetIpRanges(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetIpRangesResult, error) {
	var rv GetIpRangesResult
	err := ctx.Invoke("cloudflare:index/getIpRanges:getIpRanges", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getIpRanges.
type GetIpRangesResult struct {
	// The lexically ordered list of only the IPv4 China CIDR blocks.
	ChinaIpv4CidrBlocks []string `pulumi:"chinaIpv4CidrBlocks"`
	// The lexically ordered list of only the IPv6 China CIDR blocks.
	ChinaIpv6CidrBlocks []string `pulumi:"chinaIpv6CidrBlocks"`
	// The lexically ordered list of all non-China CIDR blocks.
	CidrBlocks []string `pulumi:"cidrBlocks"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// The lexically ordered list of only the IPv4 CIDR blocks.
	Ipv4CidrBlocks []string `pulumi:"ipv4CidrBlocks"`
	// The lexically ordered list of only the IPv6 CIDR blocks.
	Ipv6CidrBlocks []string `pulumi:"ipv6CidrBlocks"`
}
