// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cloudflare

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-cloudflare/sdk/v6/go/cloudflare/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-cloudflare/sdk/v6/go/cloudflare"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := cloudflare.NewMagicWanBgpFilterProfile(ctx, "example_magic_wan_bgp_filter_profile", &cloudflare.MagicWanBgpFilterProfileArgs{
//				AccountId:   pulumi.String("023e105f4ecef8ad9ca31a8372d0c353"),
//				MatchAction: pulumi.String("allow"),
//				Name:        pulumi.String("Allowed On-Prem Imports"),
//				Targets: pulumi.StringArray{
//					pulumi.String("10.0.0.0/8{8,32}"),
//				},
//				Description: pulumi.String("Allowed corporate subnets from on-premises"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// ```sh
// $ pulumi import cloudflare:index/magicWanBgpFilterProfile:MagicWanBgpFilterProfile example '<account_id>/<profile_id>'
// ```
type MagicWanBgpFilterProfile struct {
	pulumi.CustomResourceState

	// Identifier
	AccountId pulumi.StringOutput `pulumi:"accountId"`
	CreatedOn pulumi.StringOutput `pulumi:"createdOn"`
	// Description of the filter profile
	Description pulumi.StringOutput `pulumi:"description"`
	// Action to take when a route matches one of the targets in this profile
	// Available values: "allow", "deny".
	MatchAction pulumi.StringOutput `pulumi:"matchAction"`
	ModifiedOn  pulumi.StringOutput `pulumi:"modifiedOn"`
	// Friendly name for the filter profile
	Name pulumi.StringOutput `pulumi:"name"`
	// List of CIDR prefixes. Each entry may carry an optional suffix that specifies which prefix lengths to match relative to the prefix length N: '{X,Y}' matches prefix lengths in the inclusive range [X, Y] where N <= X <= Y <= max (max is 32 for IPv4, 128 for IPv6), '{X}' matches exactly length X (equivalent to {X,X}), '+' is shorthand for {N, max} (the prefix and all more-specific subnets, including at length N itself; valid even when N is the maximum length). Omit the suffix to match the prefix exactly at length N.
	Targets pulumi.StringArrayOutput `pulumi:"targets"`
}

// NewMagicWanBgpFilterProfile registers a new resource with the given unique name, arguments, and options.
func NewMagicWanBgpFilterProfile(ctx *pulumi.Context,
	name string, args *MagicWanBgpFilterProfileArgs, opts ...pulumi.ResourceOption) (*MagicWanBgpFilterProfile, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.AccountId == nil {
		return nil, errors.New("invalid value for required argument 'AccountId'")
	}
	if args.MatchAction == nil {
		return nil, errors.New("invalid value for required argument 'MatchAction'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.Targets == nil {
		return nil, errors.New("invalid value for required argument 'Targets'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource MagicWanBgpFilterProfile
	err := ctx.RegisterResource("cloudflare:index/magicWanBgpFilterProfile:MagicWanBgpFilterProfile", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetMagicWanBgpFilterProfile gets an existing MagicWanBgpFilterProfile resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetMagicWanBgpFilterProfile(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *MagicWanBgpFilterProfileState, opts ...pulumi.ResourceOption) (*MagicWanBgpFilterProfile, error) {
	var resource MagicWanBgpFilterProfile
	err := ctx.ReadResource("cloudflare:index/magicWanBgpFilterProfile:MagicWanBgpFilterProfile", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering MagicWanBgpFilterProfile resources.
type magicWanBgpFilterProfileState struct {
	// Identifier
	AccountId *string `pulumi:"accountId"`
	CreatedOn *string `pulumi:"createdOn"`
	// Description of the filter profile
	Description *string `pulumi:"description"`
	// Action to take when a route matches one of the targets in this profile
	// Available values: "allow", "deny".
	MatchAction *string `pulumi:"matchAction"`
	ModifiedOn  *string `pulumi:"modifiedOn"`
	// Friendly name for the filter profile
	Name *string `pulumi:"name"`
	// List of CIDR prefixes. Each entry may carry an optional suffix that specifies which prefix lengths to match relative to the prefix length N: '{X,Y}' matches prefix lengths in the inclusive range [X, Y] where N <= X <= Y <= max (max is 32 for IPv4, 128 for IPv6), '{X}' matches exactly length X (equivalent to {X,X}), '+' is shorthand for {N, max} (the prefix and all more-specific subnets, including at length N itself; valid even when N is the maximum length). Omit the suffix to match the prefix exactly at length N.
	Targets []string `pulumi:"targets"`
}

type MagicWanBgpFilterProfileState struct {
	// Identifier
	AccountId pulumi.StringPtrInput
	CreatedOn pulumi.StringPtrInput
	// Description of the filter profile
	Description pulumi.StringPtrInput
	// Action to take when a route matches one of the targets in this profile
	// Available values: "allow", "deny".
	MatchAction pulumi.StringPtrInput
	ModifiedOn  pulumi.StringPtrInput
	// Friendly name for the filter profile
	Name pulumi.StringPtrInput
	// List of CIDR prefixes. Each entry may carry an optional suffix that specifies which prefix lengths to match relative to the prefix length N: '{X,Y}' matches prefix lengths in the inclusive range [X, Y] where N <= X <= Y <= max (max is 32 for IPv4, 128 for IPv6), '{X}' matches exactly length X (equivalent to {X,X}), '+' is shorthand for {N, max} (the prefix and all more-specific subnets, including at length N itself; valid even when N is the maximum length). Omit the suffix to match the prefix exactly at length N.
	Targets pulumi.StringArrayInput
}

func (MagicWanBgpFilterProfileState) ElementType() reflect.Type {
	return reflect.TypeOf((*magicWanBgpFilterProfileState)(nil)).Elem()
}

type magicWanBgpFilterProfileArgs struct {
	// Identifier
	AccountId string `pulumi:"accountId"`
	// Description of the filter profile
	Description *string `pulumi:"description"`
	// Action to take when a route matches one of the targets in this profile
	// Available values: "allow", "deny".
	MatchAction string `pulumi:"matchAction"`
	// Friendly name for the filter profile
	Name string `pulumi:"name"`
	// List of CIDR prefixes. Each entry may carry an optional suffix that specifies which prefix lengths to match relative to the prefix length N: '{X,Y}' matches prefix lengths in the inclusive range [X, Y] where N <= X <= Y <= max (max is 32 for IPv4, 128 for IPv6), '{X}' matches exactly length X (equivalent to {X,X}), '+' is shorthand for {N, max} (the prefix and all more-specific subnets, including at length N itself; valid even when N is the maximum length). Omit the suffix to match the prefix exactly at length N.
	Targets []string `pulumi:"targets"`
}

// The set of arguments for constructing a MagicWanBgpFilterProfile resource.
type MagicWanBgpFilterProfileArgs struct {
	// Identifier
	AccountId pulumi.StringInput
	// Description of the filter profile
	Description pulumi.StringPtrInput
	// Action to take when a route matches one of the targets in this profile
	// Available values: "allow", "deny".
	MatchAction pulumi.StringInput
	// Friendly name for the filter profile
	Name pulumi.StringInput
	// List of CIDR prefixes. Each entry may carry an optional suffix that specifies which prefix lengths to match relative to the prefix length N: '{X,Y}' matches prefix lengths in the inclusive range [X, Y] where N <= X <= Y <= max (max is 32 for IPv4, 128 for IPv6), '{X}' matches exactly length X (equivalent to {X,X}), '+' is shorthand for {N, max} (the prefix and all more-specific subnets, including at length N itself; valid even when N is the maximum length). Omit the suffix to match the prefix exactly at length N.
	Targets pulumi.StringArrayInput
}

func (MagicWanBgpFilterProfileArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*magicWanBgpFilterProfileArgs)(nil)).Elem()
}

type MagicWanBgpFilterProfileInput interface {
	pulumi.Input

	ToMagicWanBgpFilterProfileOutput() MagicWanBgpFilterProfileOutput
	ToMagicWanBgpFilterProfileOutputWithContext(ctx context.Context) MagicWanBgpFilterProfileOutput
}

func (*MagicWanBgpFilterProfile) ElementType() reflect.Type {
	return reflect.TypeOf((**MagicWanBgpFilterProfile)(nil)).Elem()
}

func (i *MagicWanBgpFilterProfile) ToMagicWanBgpFilterProfileOutput() MagicWanBgpFilterProfileOutput {
	return i.ToMagicWanBgpFilterProfileOutputWithContext(context.Background())
}

func (i *MagicWanBgpFilterProfile) ToMagicWanBgpFilterProfileOutputWithContext(ctx context.Context) MagicWanBgpFilterProfileOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MagicWanBgpFilterProfileOutput)
}

// MagicWanBgpFilterProfileArrayInput is an input type that accepts MagicWanBgpFilterProfileArray and MagicWanBgpFilterProfileArrayOutput values.
// You can construct a concrete instance of `MagicWanBgpFilterProfileArrayInput` via:
//
//	MagicWanBgpFilterProfileArray{ MagicWanBgpFilterProfileArgs{...} }
type MagicWanBgpFilterProfileArrayInput interface {
	pulumi.Input

	ToMagicWanBgpFilterProfileArrayOutput() MagicWanBgpFilterProfileArrayOutput
	ToMagicWanBgpFilterProfileArrayOutputWithContext(context.Context) MagicWanBgpFilterProfileArrayOutput
}

type MagicWanBgpFilterProfileArray []MagicWanBgpFilterProfileInput

func (MagicWanBgpFilterProfileArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*MagicWanBgpFilterProfile)(nil)).Elem()
}

func (i MagicWanBgpFilterProfileArray) ToMagicWanBgpFilterProfileArrayOutput() MagicWanBgpFilterProfileArrayOutput {
	return i.ToMagicWanBgpFilterProfileArrayOutputWithContext(context.Background())
}

func (i MagicWanBgpFilterProfileArray) ToMagicWanBgpFilterProfileArrayOutputWithContext(ctx context.Context) MagicWanBgpFilterProfileArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MagicWanBgpFilterProfileArrayOutput)
}

// MagicWanBgpFilterProfileMapInput is an input type that accepts MagicWanBgpFilterProfileMap and MagicWanBgpFilterProfileMapOutput values.
// You can construct a concrete instance of `MagicWanBgpFilterProfileMapInput` via:
//
//	MagicWanBgpFilterProfileMap{ "key": MagicWanBgpFilterProfileArgs{...} }
type MagicWanBgpFilterProfileMapInput interface {
	pulumi.Input

	ToMagicWanBgpFilterProfileMapOutput() MagicWanBgpFilterProfileMapOutput
	ToMagicWanBgpFilterProfileMapOutputWithContext(context.Context) MagicWanBgpFilterProfileMapOutput
}

type MagicWanBgpFilterProfileMap map[string]MagicWanBgpFilterProfileInput

func (MagicWanBgpFilterProfileMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*MagicWanBgpFilterProfile)(nil)).Elem()
}

func (i MagicWanBgpFilterProfileMap) ToMagicWanBgpFilterProfileMapOutput() MagicWanBgpFilterProfileMapOutput {
	return i.ToMagicWanBgpFilterProfileMapOutputWithContext(context.Background())
}

func (i MagicWanBgpFilterProfileMap) ToMagicWanBgpFilterProfileMapOutputWithContext(ctx context.Context) MagicWanBgpFilterProfileMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MagicWanBgpFilterProfileMapOutput)
}

type MagicWanBgpFilterProfileOutput struct{ *pulumi.OutputState }

func (MagicWanBgpFilterProfileOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**MagicWanBgpFilterProfile)(nil)).Elem()
}

func (o MagicWanBgpFilterProfileOutput) ToMagicWanBgpFilterProfileOutput() MagicWanBgpFilterProfileOutput {
	return o
}

func (o MagicWanBgpFilterProfileOutput) ToMagicWanBgpFilterProfileOutputWithContext(ctx context.Context) MagicWanBgpFilterProfileOutput {
	return o
}

// Identifier
func (o MagicWanBgpFilterProfileOutput) AccountId() pulumi.StringOutput {
	return o.ApplyT(func(v *MagicWanBgpFilterProfile) pulumi.StringOutput { return v.AccountId }).(pulumi.StringOutput)
}

func (o MagicWanBgpFilterProfileOutput) CreatedOn() pulumi.StringOutput {
	return o.ApplyT(func(v *MagicWanBgpFilterProfile) pulumi.StringOutput { return v.CreatedOn }).(pulumi.StringOutput)
}

// Description of the filter profile
func (o MagicWanBgpFilterProfileOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *MagicWanBgpFilterProfile) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

// Action to take when a route matches one of the targets in this profile
// Available values: "allow", "deny".
func (o MagicWanBgpFilterProfileOutput) MatchAction() pulumi.StringOutput {
	return o.ApplyT(func(v *MagicWanBgpFilterProfile) pulumi.StringOutput { return v.MatchAction }).(pulumi.StringOutput)
}

func (o MagicWanBgpFilterProfileOutput) ModifiedOn() pulumi.StringOutput {
	return o.ApplyT(func(v *MagicWanBgpFilterProfile) pulumi.StringOutput { return v.ModifiedOn }).(pulumi.StringOutput)
}

// Friendly name for the filter profile
func (o MagicWanBgpFilterProfileOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *MagicWanBgpFilterProfile) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// List of CIDR prefixes. Each entry may carry an optional suffix that specifies which prefix lengths to match relative to the prefix length N: '{X,Y}' matches prefix lengths in the inclusive range [X, Y] where N <= X <= Y <= max (max is 32 for IPv4, 128 for IPv6), '{X}' matches exactly length X (equivalent to {X,X}), '+' is shorthand for {N, max} (the prefix and all more-specific subnets, including at length N itself; valid even when N is the maximum length). Omit the suffix to match the prefix exactly at length N.
func (o MagicWanBgpFilterProfileOutput) Targets() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *MagicWanBgpFilterProfile) pulumi.StringArrayOutput { return v.Targets }).(pulumi.StringArrayOutput)
}

type MagicWanBgpFilterProfileArrayOutput struct{ *pulumi.OutputState }

func (MagicWanBgpFilterProfileArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*MagicWanBgpFilterProfile)(nil)).Elem()
}

func (o MagicWanBgpFilterProfileArrayOutput) ToMagicWanBgpFilterProfileArrayOutput() MagicWanBgpFilterProfileArrayOutput {
	return o
}

func (o MagicWanBgpFilterProfileArrayOutput) ToMagicWanBgpFilterProfileArrayOutputWithContext(ctx context.Context) MagicWanBgpFilterProfileArrayOutput {
	return o
}

func (o MagicWanBgpFilterProfileArrayOutput) Index(i pulumi.IntInput) MagicWanBgpFilterProfileOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *MagicWanBgpFilterProfile {
		return vs[0].([]*MagicWanBgpFilterProfile)[vs[1].(int)]
	}).(MagicWanBgpFilterProfileOutput)
}

type MagicWanBgpFilterProfileMapOutput struct{ *pulumi.OutputState }

func (MagicWanBgpFilterProfileMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*MagicWanBgpFilterProfile)(nil)).Elem()
}

func (o MagicWanBgpFilterProfileMapOutput) ToMagicWanBgpFilterProfileMapOutput() MagicWanBgpFilterProfileMapOutput {
	return o
}

func (o MagicWanBgpFilterProfileMapOutput) ToMagicWanBgpFilterProfileMapOutputWithContext(ctx context.Context) MagicWanBgpFilterProfileMapOutput {
	return o
}

func (o MagicWanBgpFilterProfileMapOutput) MapIndex(k pulumi.StringInput) MagicWanBgpFilterProfileOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *MagicWanBgpFilterProfile {
		return vs[0].(map[string]*MagicWanBgpFilterProfile)[vs[1].(string)]
	}).(MagicWanBgpFilterProfileOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*MagicWanBgpFilterProfileInput)(nil)).Elem(), &MagicWanBgpFilterProfile{})
	pulumi.RegisterInputType(reflect.TypeOf((*MagicWanBgpFilterProfileArrayInput)(nil)).Elem(), MagicWanBgpFilterProfileArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*MagicWanBgpFilterProfileMapInput)(nil)).Elem(), MagicWanBgpFilterProfileMap{})
	pulumi.RegisterOutputType(MagicWanBgpFilterProfileOutput{})
	pulumi.RegisterOutputType(MagicWanBgpFilterProfileArrayOutput{})
	pulumi.RegisterOutputType(MagicWanBgpFilterProfileMapOutput{})
}
