// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cloudflare

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-cloudflare/sdk/v6/go/cloudflare/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The provider type for the cloudflare package. By default, resources use package-wide configuration
// settings, however an explicit `Provider` instance may be created and passed during resource
// construction to achieve fine-grained programmatic control over provider settings. See the
// [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
type Provider struct {
	pulumi.ProviderResourceState

	// The API key for operations. Alternatively, can be configured using the `CLOUDFLARE_API_KEY` environment variable. API
	// keys are [now considered legacy by
	// Cloudflare](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations), API tokens should be used
	// instead. Must provide only one of `apiKey`, `apiToken`, `apiUserServiceKey`.
	ApiKey pulumi.StringPtrOutput `pulumi:"apiKey"`
	// The API Token for operations. Alternatively, can be configured using the `CLOUDFLARE_API_TOKEN` environment variable.
	// Must provide only one of `apiKey`, `apiToken`, `apiUserServiceKey`.
	ApiToken pulumi.StringPtrOutput `pulumi:"apiToken"`
	// A special Cloudflare API key good for a restricted set of endpoints. Alternatively, can be configured using the
	// `CLOUDFLARE_API_USER_SERVICE_KEY` environment variable. Must provide only one of `apiKey`, `apiToken`,
	// `apiUserServiceKey`.
	ApiUserServiceKey pulumi.StringPtrOutput `pulumi:"apiUserServiceKey"`
	// Value to override the default HTTP client base URL. Alternatively, can be configured using the `baseUrl` environment
	// variable.
	BaseUrl pulumi.StringPtrOutput `pulumi:"baseUrl"`
	// A registered Cloudflare email address. Alternatively, can be configured using the `CLOUDFLARE_EMAIL` environment
	// variable. Required when using `apiKey`. Conflicts with `apiToken`.
	Email                   pulumi.StringPtrOutput `pulumi:"email"`
	UserAgentOperatorSuffix pulumi.StringPtrOutput `pulumi:"userAgentOperatorSuffix"`
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *pulumi.Context,
	name string, args *ProviderArgs, opts ...pulumi.ResourceOption) (*Provider, error) {
	if args == nil {
		args = &ProviderArgs{}
	}

	if args.ApiKey != nil {
		args.ApiKey = pulumi.ToSecret(args.ApiKey).(pulumi.StringPtrInput)
	}
	if args.ApiToken != nil {
		args.ApiToken = pulumi.ToSecret(args.ApiToken).(pulumi.StringPtrInput)
	}
	if args.ApiUserServiceKey != nil {
		args.ApiUserServiceKey = pulumi.ToSecret(args.ApiUserServiceKey).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"apiKey",
		"apiToken",
		"apiUserServiceKey",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Provider
	err := ctx.RegisterResource("pulumi:providers:cloudflare", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	// The API key for operations. Alternatively, can be configured using the `CLOUDFLARE_API_KEY` environment variable. API
	// keys are [now considered legacy by
	// Cloudflare](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations), API tokens should be used
	// instead. Must provide only one of `apiKey`, `apiToken`, `apiUserServiceKey`.
	ApiKey *string `pulumi:"apiKey"`
	// The API Token for operations. Alternatively, can be configured using the `CLOUDFLARE_API_TOKEN` environment variable.
	// Must provide only one of `apiKey`, `apiToken`, `apiUserServiceKey`.
	ApiToken *string `pulumi:"apiToken"`
	// A special Cloudflare API key good for a restricted set of endpoints. Alternatively, can be configured using the
	// `CLOUDFLARE_API_USER_SERVICE_KEY` environment variable. Must provide only one of `apiKey`, `apiToken`,
	// `apiUserServiceKey`.
	ApiUserServiceKey *string `pulumi:"apiUserServiceKey"`
	// Value to override the default HTTP client base URL. Alternatively, can be configured using the `baseUrl` environment
	// variable.
	BaseUrl *string `pulumi:"baseUrl"`
	// A registered Cloudflare email address. Alternatively, can be configured using the `CLOUDFLARE_EMAIL` environment
	// variable. Required when using `apiKey`. Conflicts with `apiToken`.
	Email                   *string `pulumi:"email"`
	UserAgentOperatorSuffix *string `pulumi:"userAgentOperatorSuffix"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	// The API key for operations. Alternatively, can be configured using the `CLOUDFLARE_API_KEY` environment variable. API
	// keys are [now considered legacy by
	// Cloudflare](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations), API tokens should be used
	// instead. Must provide only one of `apiKey`, `apiToken`, `apiUserServiceKey`.
	ApiKey pulumi.StringPtrInput
	// The API Token for operations. Alternatively, can be configured using the `CLOUDFLARE_API_TOKEN` environment variable.
	// Must provide only one of `apiKey`, `apiToken`, `apiUserServiceKey`.
	ApiToken pulumi.StringPtrInput
	// A special Cloudflare API key good for a restricted set of endpoints. Alternatively, can be configured using the
	// `CLOUDFLARE_API_USER_SERVICE_KEY` environment variable. Must provide only one of `apiKey`, `apiToken`,
	// `apiUserServiceKey`.
	ApiUserServiceKey pulumi.StringPtrInput
	// Value to override the default HTTP client base URL. Alternatively, can be configured using the `baseUrl` environment
	// variable.
	BaseUrl pulumi.StringPtrInput
	// A registered Cloudflare email address. Alternatively, can be configured using the `CLOUDFLARE_EMAIL` environment
	// variable. Required when using `apiKey`. Conflicts with `apiToken`.
	Email                   pulumi.StringPtrInput
	UserAgentOperatorSuffix pulumi.StringPtrInput
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}

// This function returns a Terraform config object with terraform-namecased keys,to be used with the Terraform Module Provider.
func (r *Provider) TerraformConfig(ctx *pulumi.Context) (ProviderTerraformConfigResultOutput, error) {
	out, err := ctx.Call("pulumi:providers:cloudflare/terraformConfig", nil, ProviderTerraformConfigResultOutput{}, r)
	if err != nil {
		return ProviderTerraformConfigResultOutput{}, err
	}
	return out.(ProviderTerraformConfigResultOutput), nil
}

type ProviderTerraformConfigResult struct {
	Result map[string]interface{} `pulumi:"result"`
}

type ProviderTerraformConfigResultOutput struct{ *pulumi.OutputState }

func (ProviderTerraformConfigResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ProviderTerraformConfigResult)(nil)).Elem()
}

func (o ProviderTerraformConfigResultOutput) Result() pulumi.MapOutput {
	return o.ApplyT(func(v ProviderTerraformConfigResult) map[string]interface{} { return v.Result }).(pulumi.MapOutput)
}

type ProviderInput interface {
	pulumi.Input

	ToProviderOutput() ProviderOutput
	ToProviderOutputWithContext(ctx context.Context) ProviderOutput
}

func (*Provider) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (i *Provider) ToProviderOutput() ProviderOutput {
	return i.ToProviderOutputWithContext(context.Background())
}

func (i *Provider) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderOutput)
}

type ProviderOutput struct{ *pulumi.OutputState }

func (ProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (o ProviderOutput) ToProviderOutput() ProviderOutput {
	return o
}

func (o ProviderOutput) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return o
}

// The API key for operations. Alternatively, can be configured using the `CLOUDFLARE_API_KEY` environment variable. API
// keys are [now considered legacy by
// Cloudflare](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations), API tokens should be used
// instead. Must provide only one of `apiKey`, `apiToken`, `apiUserServiceKey`.
func (o ProviderOutput) ApiKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.ApiKey }).(pulumi.StringPtrOutput)
}

// The API Token for operations. Alternatively, can be configured using the `CLOUDFLARE_API_TOKEN` environment variable.
// Must provide only one of `apiKey`, `apiToken`, `apiUserServiceKey`.
func (o ProviderOutput) ApiToken() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.ApiToken }).(pulumi.StringPtrOutput)
}

// A special Cloudflare API key good for a restricted set of endpoints. Alternatively, can be configured using the
// `CLOUDFLARE_API_USER_SERVICE_KEY` environment variable. Must provide only one of `apiKey`, `apiToken`,
// `apiUserServiceKey`.
func (o ProviderOutput) ApiUserServiceKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.ApiUserServiceKey }).(pulumi.StringPtrOutput)
}

// Value to override the default HTTP client base URL. Alternatively, can be configured using the `baseUrl` environment
// variable.
func (o ProviderOutput) BaseUrl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.BaseUrl }).(pulumi.StringPtrOutput)
}

// A registered Cloudflare email address. Alternatively, can be configured using the `CLOUDFLARE_EMAIL` environment
// variable. Required when using `apiKey`. Conflicts with `apiToken`.
func (o ProviderOutput) Email() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.Email }).(pulumi.StringPtrOutput)
}

func (o ProviderOutput) UserAgentOperatorSuffix() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.UserAgentOperatorSuffix }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProviderInput)(nil)).Elem(), &Provider{})
	pulumi.RegisterOutputType(ProviderOutput{})
	pulumi.RegisterOutputType(ProviderTerraformConfigResultOutput{})
}
