// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudflare.r2Bucket.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetCorsArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetCorsArgs Empty = new GetCorsArgs();

    /**
     * Account ID.
     * 
     */
    @Import(name="accountId", required=true)
    private Output<String> accountId;

    /**
     * @return Account ID.
     * 
     */
    public Output<String> accountId() {
        return this.accountId;
    }

    /**
     * Name of the bucket.
     * 
     */
    @Import(name="bucketName", required=true)
    private Output<String> bucketName;

    /**
     * @return Name of the bucket.
     * 
     */
    public Output<String> bucketName() {
        return this.bucketName;
    }

    private GetCorsArgs() {}

    private GetCorsArgs(GetCorsArgs $) {
        this.accountId = $.accountId;
        this.bucketName = $.bucketName;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetCorsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetCorsArgs $;

        public Builder() {
            $ = new GetCorsArgs();
        }

        public Builder(GetCorsArgs defaults) {
            $ = new GetCorsArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param accountId Account ID.
         * 
         * @return builder
         * 
         */
        public Builder accountId(Output<String> accountId) {
            $.accountId = accountId;
            return this;
        }

        /**
         * @param accountId Account ID.
         * 
         * @return builder
         * 
         */
        public Builder accountId(String accountId) {
            return accountId(Output.of(accountId));
        }

        /**
         * @param bucketName Name of the bucket.
         * 
         * @return builder
         * 
         */
        public Builder bucketName(Output<String> bucketName) {
            $.bucketName = bucketName;
            return this;
        }

        /**
         * @param bucketName Name of the bucket.
         * 
         * @return builder
         * 
         */
        public Builder bucketName(String bucketName) {
            return bucketName(Output.of(bucketName));
        }

        public GetCorsArgs build() {
            if ($.accountId == null) {
                throw new MissingRequiredPropertyException("GetCorsArgs", "accountId");
            }
            if ($.bucketName == null) {
                throw new MissingRequiredPropertyException("GetCorsArgs", "bucketName");
            }
            return $;
        }
    }

}
