// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cloudflare.Inputs
{

    public sealed class AiSearchInstanceRetrievalOptionsGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("boostBies")]
        private InputList<Inputs.AiSearchInstanceRetrievalOptionsBoostByGetArgs>? _boostBies;

        /// <summary>
        /// Metadata fields to boost search results by. Each entry specifies a metadata field and an optional direction. Direction defaults to 'asc' for numeric fields and 'exists' for text/boolean fields. Fields must match 'timestamp' or a defined custom*metadata field.
        /// </summary>
        public InputList<Inputs.AiSearchInstanceRetrievalOptionsBoostByGetArgs> BoostBies
        {
            get => _boostBies ?? (_boostBies = new InputList<Inputs.AiSearchInstanceRetrievalOptionsBoostByGetArgs>());
            set => _boostBies = value;
        }

        /// <summary>
        /// Controls which documents are candidates for BM25 scoring. 'and' restricts candidates to documents containing all query terms; 'or' includes any document containing at least one term, ranked by BM25 relevance. Defaults to 'and'.
        /// Available values: "and", "or".
        /// </summary>
        [Input("keywordMatchMode")]
        public Input<string>? KeywordMatchMode { get; set; }

        public AiSearchInstanceRetrievalOptionsGetArgs()
        {
        }
        public static new AiSearchInstanceRetrievalOptionsGetArgs Empty => new AiSearchInstanceRetrievalOptionsGetArgs();
    }
}
