// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cloudflare.Inputs
{

    public sealed class AiSearchInstanceSourceParamsWebCrawlerArgs : global::Pulumi.ResourceArgs
    {
        [Input("crawlOptions")]
        public Input<Inputs.AiSearchInstanceSourceParamsWebCrawlerCrawlOptionsArgs>? CrawlOptions { get; set; }

        [Input("parseOptions")]
        public Input<Inputs.AiSearchInstanceSourceParamsWebCrawlerParseOptionsArgs>? ParseOptions { get; set; }

        /// <summary>
        /// Available values: "sitemap", "feed-rss", "crawl".
        /// </summary>
        [Input("parseType")]
        public Input<string>? ParseType { get; set; }

        [Input("storeOptions")]
        public Input<Inputs.AiSearchInstanceSourceParamsWebCrawlerStoreOptionsArgs>? StoreOptions { get; set; }

        public AiSearchInstanceSourceParamsWebCrawlerArgs()
        {
        }
        public static new AiSearchInstanceSourceParamsWebCrawlerArgs Empty => new AiSearchInstanceSourceParamsWebCrawlerArgs();
    }
}
