// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cloudflare.Inputs
{

    public sealed class EmailRoutingCatchAllMatcherArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Type of matcher. Default is 'all'.
        /// Available values: "all".
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public EmailRoutingCatchAllMatcherArgs()
        {
        }
        public static new EmailRoutingCatchAllMatcherArgs Empty => new EmailRoutingCatchAllMatcherArgs();
    }
}
