// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cloudflare.Inputs
{

    public sealed class RulesetRuleActionParameterUriArgs : global::Pulumi.ResourceArgs
    {
        [Input("origin", required: true)]
        public Input<bool> Origin { get; set; } = null!;

        [Input("paths", required: true)]
        private InputList<Inputs.RulesetRuleActionParameterUriPathArgs>? _paths;
        public InputList<Inputs.RulesetRuleActionParameterUriPathArgs> Paths
        {
            get => _paths ?? (_paths = new InputList<Inputs.RulesetRuleActionParameterUriPathArgs>());
            set => _paths = value;
        }

        [Input("queries", required: true)]
        private InputList<Inputs.RulesetRuleActionParameterUriQueryArgs>? _queries;
        public InputList<Inputs.RulesetRuleActionParameterUriQueryArgs> Queries
        {
            get => _queries ?? (_queries = new InputList<Inputs.RulesetRuleActionParameterUriQueryArgs>());
            set => _queries = value;
        }

        public RulesetRuleActionParameterUriArgs()
        {
        }
        public static new RulesetRuleActionParameterUriArgs Empty => new RulesetRuleActionParameterUriArgs();
    }
}
