// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cloudflare from "@pulumi/cloudflare";
 *
 * const exampleCustomHostnameFallbackOrigin = new cloudflare.CustomHostnameFallbackOrigin("example_custom_hostname_fallback_origin", {
 *     zoneId: "023e105f4ecef8ad9ca31a8372d0c353",
 *     origin: "fallback.example.com",
 * });
 * ```
 *
 * ## Import
 *
 * ```sh
 * $ pulumi import cloudflare:index/customHostnameFallbackOrigin:CustomHostnameFallbackOrigin example '<zone_id>'
 * ```
 */
export class CustomHostnameFallbackOrigin extends pulumi.CustomResource {
    /**
     * Get an existing CustomHostnameFallbackOrigin resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CustomHostnameFallbackOriginState, opts?: pulumi.CustomResourceOptions): CustomHostnameFallbackOrigin {
        return new CustomHostnameFallbackOrigin(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'cloudflare:index/customHostnameFallbackOrigin:CustomHostnameFallbackOrigin';

    /**
     * Returns true if the given object is an instance of CustomHostnameFallbackOrigin.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CustomHostnameFallbackOrigin {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CustomHostnameFallbackOrigin.__pulumiType;
    }

    /**
     * This is the time the fallback origin was created.
     */
    public /*out*/ readonly createdAt!: pulumi.Output<string>;
    /**
     * These are errors that were encountered while trying to activate a fallback origin.
     */
    public /*out*/ readonly errors!: pulumi.Output<string[]>;
    /**
     * Your origin hostname that requests to your custom hostnames will be sent to.
     */
    public readonly origin!: pulumi.Output<string>;
    /**
     * Status of the fallback origin's activation.
     */
    public /*out*/ readonly status!: pulumi.Output<string>;
    /**
     * This is the time the fallback origin was updated.
     */
    public /*out*/ readonly updatedAt!: pulumi.Output<string>;
    /**
     * Identifier
     */
    public readonly zoneId!: pulumi.Output<string>;

    /**
     * Create a CustomHostnameFallbackOrigin resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CustomHostnameFallbackOriginArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CustomHostnameFallbackOriginArgs | CustomHostnameFallbackOriginState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as CustomHostnameFallbackOriginState | undefined;
            resourceInputs["createdAt"] = state ? state.createdAt : undefined;
            resourceInputs["errors"] = state ? state.errors : undefined;
            resourceInputs["origin"] = state ? state.origin : undefined;
            resourceInputs["status"] = state ? state.status : undefined;
            resourceInputs["updatedAt"] = state ? state.updatedAt : undefined;
            resourceInputs["zoneId"] = state ? state.zoneId : undefined;
        } else {
            const args = argsOrState as CustomHostnameFallbackOriginArgs | undefined;
            if ((!args || args.origin === undefined) && !opts.urn) {
                throw new Error("Missing required property 'origin'");
            }
            if ((!args || args.zoneId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'zoneId'");
            }
            resourceInputs["origin"] = args ? args.origin : undefined;
            resourceInputs["zoneId"] = args ? args.zoneId : undefined;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["errors"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(CustomHostnameFallbackOrigin.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering CustomHostnameFallbackOrigin resources.
 */
export interface CustomHostnameFallbackOriginState {
    /**
     * This is the time the fallback origin was created.
     */
    createdAt?: pulumi.Input<string>;
    /**
     * These are errors that were encountered while trying to activate a fallback origin.
     */
    errors?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Your origin hostname that requests to your custom hostnames will be sent to.
     */
    origin?: pulumi.Input<string>;
    /**
     * Status of the fallback origin's activation.
     */
    status?: pulumi.Input<string>;
    /**
     * This is the time the fallback origin was updated.
     */
    updatedAt?: pulumi.Input<string>;
    /**
     * Identifier
     */
    zoneId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a CustomHostnameFallbackOrigin resource.
 */
export interface CustomHostnameFallbackOriginArgs {
    /**
     * Your origin hostname that requests to your custom hostnames will be sent to.
     */
    origin: pulumi.Input<string>;
    /**
     * Identifier
     */
    zoneId: pulumi.Input<string>;
}
