// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Accepted Permissions
 *
 * - `Account Firewall Access Rules Read`
 * - `Account Firewall Access Rules Write`
 * - `Account Settings Read`
 * - `Account Settings Write`
 * - `Billing Read`
 * - `Billing Write`
 * - `DDoS Botnet Feed Read`
 * - `DDoS Botnet Feed Write`
 * - `DDoS Protection Read`
 * - `DDoS Protection Write`
 * - `DNS Firewall Read`
 * - `DNS Firewall Write`
 * - `DNS View Read`
 * - `DNS View Write`
 * - `Load Balancers Account Read`
 * - `Load Balancers Account Write`
 * - `Load Balancing: Monitors and Pools Read`
 * - `Load Balancing: Monitors and Pools Write`
 * - `SCIM Provisioning`
 * - `Trust and Safety Read`
 * - `Trust and Safety Write`
 * - `Workers KV Storage Read`
 * - `Workers KV Storage Write`
 * - `Workers R2 Storage Read`
 * - `Workers R2 Storage Write`
 * - `Workers Scripts Read`
 * - `Workers Scripts Write`
 * - `Workers Tail Read`
 * - `Zero Trust: PII Read`
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cloudflare from "@pulumi/cloudflare";
 *
 * const exampleFlagshipApp = new cloudflare.FlagshipApp("example_flagship_app", {
 *     accountId: "account_id",
 *     name: "x",
 * });
 * ```
 *
 * ## Import
 *
 * ```sh
 * $ pulumi import cloudflare:index/flagshipApp:FlagshipApp example '<account_id>/<app_id>'
 * ```
 */
export class FlagshipApp extends pulumi.CustomResource {
    /**
     * Get an existing FlagshipApp resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: FlagshipAppState, opts?: pulumi.CustomResourceOptions): FlagshipApp {
        return new FlagshipApp(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'cloudflare:index/flagshipApp:FlagshipApp';

    /**
     * Returns true if the given object is an instance of FlagshipApp.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is FlagshipApp {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === FlagshipApp.__pulumiType;
    }

    /**
     * Cloudflare account ID.
     */
    declare public readonly accountId: pulumi.Output<string>;
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    declare public readonly name: pulumi.Output<string>;
    declare public /*out*/ readonly updatedAt: pulumi.Output<string>;
    /**
     * Email of the actor who last modified the app, or `edge-gateway` for gateway-authenticated changes.
     */
    declare public /*out*/ readonly updatedBy: pulumi.Output<string>;

    /**
     * Create a FlagshipApp resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: FlagshipAppArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: FlagshipAppArgs | FlagshipAppState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as FlagshipAppState | undefined;
            resourceInputs["accountId"] = state?.accountId;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["name"] = state?.name;
            resourceInputs["updatedAt"] = state?.updatedAt;
            resourceInputs["updatedBy"] = state?.updatedBy;
        } else {
            const args = argsOrState as FlagshipAppArgs | undefined;
            if (args?.accountId === undefined && !opts.urn) {
                throw new Error("Missing required property 'accountId'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["accountId"] = args?.accountId;
            resourceInputs["name"] = args?.name;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
            resourceInputs["updatedBy"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(FlagshipApp.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering FlagshipApp resources.
 */
export interface FlagshipAppState {
    /**
     * Cloudflare account ID.
     */
    accountId?: pulumi.Input<string | undefined>;
    createdAt?: pulumi.Input<string | undefined>;
    name?: pulumi.Input<string | undefined>;
    updatedAt?: pulumi.Input<string | undefined>;
    /**
     * Email of the actor who last modified the app, or `edge-gateway` for gateway-authenticated changes.
     */
    updatedBy?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a FlagshipApp resource.
 */
export interface FlagshipAppArgs {
    /**
     * Cloudflare account ID.
     */
    accountId: pulumi.Input<string>;
    name: pulumi.Input<string>;
}
