// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Accepted Permissions
 *
 * - `Account: SSL and Certificates Read`
 * - `Account: SSL and Certificates Write`
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cloudflare from "@pulumi/cloudflare";
 *
 * const exampleMtlsCertificateAssociations = cloudflare.getMtlsCertificateAssociations({
 *     accountId: "023e105f4ecef8ad9ca31a8372d0c353",
 *     mtlsCertificateId: "023e105f4ecef8ad9ca31a8372d0c353",
 * });
 * ```
 */
export function getMtlsCertificateAssociations(args: GetMtlsCertificateAssociationsArgs, opts?: pulumi.InvokeOptions): Promise<GetMtlsCertificateAssociationsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("cloudflare:index/getMtlsCertificateAssociations:getMtlsCertificateAssociations", {
        "accountId": args.accountId,
        "mtlsCertificateId": args.mtlsCertificateId,
    }, opts);
}

/**
 * A collection of arguments for invoking getMtlsCertificateAssociations.
 */
export interface GetMtlsCertificateAssociationsArgs {
    /**
     * Identifier.
     */
    accountId?: string;
    /**
     * Identifier.
     */
    mtlsCertificateId: string;
}

/**
 * A collection of values returned by getMtlsCertificateAssociations.
 */
export interface GetMtlsCertificateAssociationsResult {
    /**
     * Identifier.
     */
    readonly accountId?: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * Identifier.
     */
    readonly mtlsCertificateId: string;
    /**
     * The service using the certificate.
     */
    readonly service: string;
    /**
     * Certificate deployment status for the given service.
     */
    readonly status: string;
}
/**
 * Accepted Permissions
 *
 * - `Account: SSL and Certificates Read`
 * - `Account: SSL and Certificates Write`
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cloudflare from "@pulumi/cloudflare";
 *
 * const exampleMtlsCertificateAssociations = cloudflare.getMtlsCertificateAssociations({
 *     accountId: "023e105f4ecef8ad9ca31a8372d0c353",
 *     mtlsCertificateId: "023e105f4ecef8ad9ca31a8372d0c353",
 * });
 * ```
 */
export function getMtlsCertificateAssociationsOutput(args: GetMtlsCertificateAssociationsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetMtlsCertificateAssociationsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("cloudflare:index/getMtlsCertificateAssociations:getMtlsCertificateAssociations", {
        "accountId": args.accountId,
        "mtlsCertificateId": args.mtlsCertificateId,
    }, opts);
}

/**
 * A collection of arguments for invoking getMtlsCertificateAssociations.
 */
export interface GetMtlsCertificateAssociationsOutputArgs {
    /**
     * Identifier.
     */
    accountId?: pulumi.Input<string | undefined>;
    /**
     * Identifier.
     */
    mtlsCertificateId: pulumi.Input<string>;
}
