// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cloudflare from "@pulumi/cloudflare";
 *
 * const exampleZeroTrustDeviceDefaultProfileLocalDomainFallback = cloudflare.getZeroTrustDeviceDefaultProfileLocalDomainFallback({
 *     accountId: "699d98642c564d2e855e9661899b7252",
 * });
 * ```
 */
export function getZeroTrustDeviceDefaultProfileLocalDomainFallback(args: GetZeroTrustDeviceDefaultProfileLocalDomainFallbackArgs, opts?: pulumi.InvokeOptions): Promise<GetZeroTrustDeviceDefaultProfileLocalDomainFallbackResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("cloudflare:index/getZeroTrustDeviceDefaultProfileLocalDomainFallback:getZeroTrustDeviceDefaultProfileLocalDomainFallback", {
        "accountId": args.accountId,
    }, opts);
}

/**
 * A collection of arguments for invoking getZeroTrustDeviceDefaultProfileLocalDomainFallback.
 */
export interface GetZeroTrustDeviceDefaultProfileLocalDomainFallbackArgs {
    accountId: string;
}

/**
 * A collection of values returned by getZeroTrustDeviceDefaultProfileLocalDomainFallback.
 */
export interface GetZeroTrustDeviceDefaultProfileLocalDomainFallbackResult {
    readonly accountId: string;
    /**
<<<<<<< HEAD
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
=======
     * A description of the fallback domain, displayed in the client UI.
     */
    readonly description: string;
    /**
     * A list of IP addresses to handle domain resolution.
     */
    readonly dnsServers: string[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The domain suffix to match when resolving locally.
     */
    readonly suffix: string;
>>>>>>> 5daf78d00237b27958698f41a3d5f5b7e342d580
}
/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cloudflare from "@pulumi/cloudflare";
 *
 * const exampleZeroTrustDeviceDefaultProfileLocalDomainFallback = cloudflare.getZeroTrustDeviceDefaultProfileLocalDomainFallback({
 *     accountId: "699d98642c564d2e855e9661899b7252",
 * });
 * ```
 */
export function getZeroTrustDeviceDefaultProfileLocalDomainFallbackOutput(args: GetZeroTrustDeviceDefaultProfileLocalDomainFallbackOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetZeroTrustDeviceDefaultProfileLocalDomainFallbackResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("cloudflare:index/getZeroTrustDeviceDefaultProfileLocalDomainFallback:getZeroTrustDeviceDefaultProfileLocalDomainFallback", {
        "accountId": args.accountId,
    }, opts);
}

/**
 * A collection of arguments for invoking getZeroTrustDeviceDefaultProfileLocalDomainFallback.
 */
export interface GetZeroTrustDeviceDefaultProfileLocalDomainFallbackOutputArgs {
    accountId: pulumi.Input<string>;
}
